### ISSUE TITLE
Resource usage

### ISSUE THREAD

**Issue by fergsc** [schneebergerlab/syri#10]
Hi, I am looking into using SyRI on a number of genomes I am asembling, but before I do I need to scaffold with chroder. I have run
```
nucmer --maxmatch -c 100 -b 500 -l 50 -t 6 -p alignment reference.fasta query.fasta
delta-filter -m -i 90 -l 100 alignment.delta > alignment.filtered.delta
show-coords -THrd alignment.filtered.delta > alignment.filtered.coords
chroder -n 100 -o test_scaffold alignment.filtered.coords reference.fasta query.fasta 
```
chroder has been running for ~2days and is currently using ~130GB of RAM. Is it normal for chroder to take this long and use this much RAM.

Reference and query genomes ~650 Mbp. Reference has 12 scaffolds and query 1133.

Thanks.

**Comment by mnshgl0110** [comment]
Hi, chroder uses heuristics and in some cases it gets stuck. We are working on a solution which should be available very soon.
In the above command, you did not use `-noref`, so I assume that the 12 scaffolds in the reference are being considered as chromosomes, implying that only query scaffolds need to be concatenated. For such cases, you can try dedicated scaffolding methods (like [RaGOO](https://github.com/malonge/RaGOO)) as they might provide better a pseudo-genome.

**Comment by fergsc** [comment]
Yes, I am using the 12 scaffolds as chromosomes. Ran RaGOO and the results look good, will proceed to using SyRI.

thanks for the help.
