### ISSUE TITLE
Getting sequence divergence for aligned blocks

### ISSUE THREAD

**Issue by owensgl** [schneebergerlab/syri#103]
Hi,
I'm using Syri to identify inversions and get their sequence identity. In the past, I've used mummer as the aligner, which starts me with a delta file that has sequence identity built in. I've switched to minimap, because it seems like it is a better aligner, but in this case I use a SAM file as input, instead of delta. With the delta file, and the output of Syri, I could easily find which blocks were in inversions, and then get their sequence identity from the delta file, but when starting with the SAM file it is not so straight forward. Is there an easy way to get aligned block sequence identity from the Syri output? I'm considering parsing the syri.out file that includes all the variants, but I was hoping there was an easier way. 
Thanks for any help,
Greg

**Comment by mnshgl0110** [comment]
Use the following python code to convert SAM to coords:
```
from syri.pyxFiles.synsearchFunctions import samtocoords
samtocoords(/PATH/TO/SAM)
```
then you can fetch alignment identity easily.

**Comment by mnshgl0110** [comment]
I have restructured the folders. Use the following to import `samtocoords`:
```
from syri.synsearchFunctions import samtocoords
```
Usage is the same.
