### ISSUE TITLE
Which duplication variant result should I use in the syri.summary file?

### ISSUE THREAD

**Issue by pjx1990** [schneebergerlab/syri#106]
I want to know what is the difference between Duplications (reference), Duplications (query) and Copygains, Copylosses in the syri.summary file? Which result should I use?
Thank you!

**Comment by mnshgl0110** [comment]
Check this https://github.com/schneebergerlab/syri/issues/67

Duplications (reference): are regions duplicated in reference, i.e. there is an extra copy in reference compared to query OR the other way around, the query has lost a copy compared to the reference.

Duplications (query) are the vice-versa.
