### ISSUE TITLE
Can HDR be regarded as PAV？

### ISSUE THREAD

**Issue by Weihankk** [schneebergerlab/syri#107]
Hi there,

According to #44 and #87 , I understand the meaning of HDR. Here I have a question that could HDR be regarded as a PAV?

Both HDR and NOTAL are regions that not aligned, but HDR is located in a annotation block. For NOTAL, we can easily classify it as PAV.  

Let's take this HDR as an example for discussion:
`Chr1 322291 322405 GGGTAATG....(115bp segment) TTATCTTTTG(10bp segment) Chr1 372437 372446`

Could I treated the sequence on refgenome as a absence sequence, and the sequence on qrygenome as a presence sequence. That is to say, at Chr1 322291, the qrygenome absence a 115bp segment, and at Chr1 322405, the qrygenome presence a 10bp segment.  As an expert on structural variation, do you think this is reasonable? 

Weihan

**Comment by mnshgl0110** [comment]
I think that the HDR can be considered as PAV if the focus of downstream analysis is on the functional aspect of variations on genomes.
If the focus is to better describe the variation in the genomes or how they evolved, then I think HDR is more apt. PAV implies that two events (one deletion and one insertion) happened at the same loci. I think, this is less probable and could be incorrect description of how the genomes diverged.

**Comment by Weihankk** [comment]
> I think that the HDR can be considered as PAV if the focus of downstream analysis is on the functional aspect of variations on genomes. If the focus is to better describe the variation in the genomes or how they evolved, then I think HDR is more apt. PAV implies that two events (one deletion and one insertion) happened at the same loci. I think, this is less probable and could be incorrect description of how the genomes diverged.

Thank you for your reply. After several days of consideration, I have the same view as you that HDR can be regarded as a PAV.

I am sorry to bother you that I have another question about the breakpoint of TDM:
According to figure S8 of the published paper on GB and #40 : _TDMs annotate regions in the two genomes that correspond to overlapping alignments in both genomes._  However, I didn't understand how the coordinates of TDMs are defined.

For example here is a TDM:
`Chr1	169093	169264	-	-	Chr1	207115	207421	TDM8	SYN4	TDM	-`

This TDM is the overlapping region of the two SYNALs:
`Chr1    150981  169264  -       -       Chr1    189047  207287  SYNAL11 SYN4    SYNAL   -`
`Chr1    169093  190882  -       -       Chr1    207249  229070  SYNAL12 SYN4    SYNAL   -`

Here comes the problem, the TDM coordinate on reference  is easy to understand that is 169093-169264. But on query, why is it 207115-207421 instead of 207249-207287 as the SYNAL? I have checked all TDMs and found their breakponits are only consistent with one of refgenome or qrygenome. I drew a pic for easy to understand and explain.

![image](https://user-images.githubusercontent.com/33243134/143059846-d9bcb914-5cbc-4ef9-8317-46a4c8f19a63.png)

thank you,
Weihan

**Comment by mnshgl0110** [comment]
Check https://github.com/schneebergerlab/syri/issues/108
