### ISSUE TITLE
Coordinates of TDM

### ISSUE THREAD

**Issue by mnshgl0110** [schneebergerlab/syri#108]
> I think that the HDR can be considered as PAV if the focus of downstream analysis is on the functional aspect of variations on genomes. If the focus is to better describe the variation in the genomes or how they evolved, then I think HDR is more apt. PAV implies that two events (one deletion and one insertion) happened at the same loci. I think, this is less probable and could be incorrect description of how the genomes diverged.

Thank you for your reply. After several days of consideration, I have the same view as you that HDR can be regarded as a PAV.

I am sorry to bother you that I have another question about the breakpoint of TDM:
According to figure S8 of the published paper on GB and #40 : _TDMs annotate regions in the two genomes that correspond to overlapping alignments in both genomes._  However, I didn't understand how the coordinates of TDMs are defined.

For example here is a TDM:
`Chr1	169093	169264	-	-	Chr1	207115	207421	TDM8	SYN4	TDM	-`

This TDM is the overlapping region of the two SYNALs:
`Chr1    150981  169264  -       -       Chr1    189047  207287  SYNAL11 SYN4    SYNAL   -`
`Chr1    169093  190882  -       -       Chr1    207249  229070  SYNAL12 SYN4    SYNAL   -`

Here comes the problem, the TDM coordinate on reference  is easy to understand that is 169093-169264. But on query, why is it 207115-207421 instead of 207249-207287 as the SYNAL? I have checked all TDMs and found their breakponits are only consistent with one of refgenome or qrygenome. I drew a pic for easy to understand and explain.

![image](https://user-images.githubusercontent.com/33243134/143059846-d9bcb914-5cbc-4ef9-8317-46a4c8f19a63.png)

thank you,
Weihan

_Originally posted by @Weihankk in https://github.com/schneebergerlab/syri/issues/107#issuecomment-976797951_

**Comment by mnshgl0110** [comment]
@Weihankk
```Q:207115``` corresponds to the coordinate of ```R:169093``` in SYNAL11.  Whereas, ```Q:207421``` corresponds to ```R:169264``` in SYNAL12.
The coordinates in query gives the ends of the region which is TDM.

**Comment by Weihankk** [comment]
> @Weihankk `Q:207115` corresponds to the coordinate of `R:169093` in SYNAL11. Whereas, `Q:207421` corresponds to `R:169264` in SYNAL12. The coordinates in query gives the ends of the region which is TDM.

Thank you for your timely reply. I got it. `Q:207249-Q:207287` is the query SYNAL overlap region, while `Q:207115-Q:207421` is the region that corresponding to reference TDM region.

**Comment by mnshgl0110** [comment]
Exactly.

**Comment by Weihankk** [comment]
Right！I checked it again just now. If the overlap region on refgenome is longer than qrygenome, then the breakpoints of TDM in refgenome are same as SYNAL bounderies on refgenome. While if the overlap region on qrygenome which is longer than refgenome, the breakponits of TDM on qrygenome are same as SYNAL bounderies on qrygenome.
