### ISSUE TITLE
nucmer error

### ISSUE THREAD

**Issue by fergsc** [schneebergerlab/syri#11]
Hi, trying to get SyRI to work on some genomes I am building. I ran nucmer and SyRI with the following commands and got an error
```
~/mummer-4.0.0beta2/nucmer --maxmatch -c 500 -b 500 -l 100 -p nucmer_align $REF $QUERY
~/mummer-4.0.0beta2/delta-filter -m -i 90 -l 100 nucmer_align.delta > nucmer_align_m_i90_l100.delta
~/mummer-4.0.0beta2/show-coords -THrd nucmer_align_m_i90_l100.delta > nucmer_align_m_i90_l100.coords

syri -c nucmer_align_m_i90_l100.coords \
	-r $REF \
	-q $QUERY \
	-d nucmer_align_m_i90_l100.delta \
	--nc 7 \
	--log DEBUG 
```
error
```
syri — WARNING — starting
Namespace(TransUniCount=1000, TransUniPercent=0.5, all=False, bruteRunTime=60, chrmatch=False, cigar=False, delta=<_io.TextIOWrapper name='/media/Pangenome/syri_test/grandis_mel_m_i90_l100.delta' mode='r' encoding='UTF-8'>, dir=None, fout='syri', ftype='T', increaseBy=1000, infile=<_io.TextIOWrapper name='/media/Pangenome/syri_test/grandis_mel_m_i90_l100.coords' mode='r' encoding='UTF-8'>, keep=False, log='DEBUG', log_fin=<_io.TextIOWrapper name='syri.log' mode='w' encoding='UTF-8'>, nCores=7, nosnp=False, nosr=False, nosv=False, novcf=False, offset=5, prefix='', qry=<_io.TextIOWrapper name='/media/Pangenome/honours/E_melliodora.fasta' mode='r' encoding='UTF-8'>, ref=<_io.TextIOWrapper name='/media/Pangenome/E_grandis/chromosomes/E_grandis_chromosomes_simple_names.fasta' mode='r' encoding='UTF-8'>, seed=1, sspath='show-snps')
('Cluster is too big for Brute Force\nTime taken for last iteration ', 1.1920928955078125e-06, ' iterations remaining ', 46)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 3.62396240234375e-05, ' iterations remaining ', 40)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 0.0001552104949951172, ' iterations remaining ', 38)
('Cluster is too big for Brute Force\nTime taken for last iteration ', 0.0008757114410400391, ' iterations remaining ', 28)
Traceback (most recent call last):
  File "/home/syri/syri/bin/syri", line 143, in <module>
    getNotAligned(args.dir, args.prefix, args.ref.name, args.qry.name, chrlink)
  File "syri/pyxFiles/findsv.pyx", line 489, in syri.findsv.getNotAligned
  File "syri/pyxFiles/findsv.pyx", line 528, in syri.findsv.getNotAligned
KeyError: 'NW_010092438.1'
[syri.log](https://github.com/schneebergerlab/syri/files/3567819/syri.log)

```
Log is also attached

After failing with nucmer I ran minimap2 with the same data and SyRI ran sucessfully.

From what I understand of minimap2 and nucmer, the nucmer results should be more accurate and I am hoping someone can help me to get SyRI working with nucmer.

Thanks

[syri.log](https://github.com/schneebergerlab/syri/files/3567826/syri.log)

**Comment by mnshgl0110** [comment]
Hi. Thanks for sharing the details and the log file. Currently, my best guess is that this is a bug in a function which identifies 'not aligned' regions in the two genomes (as also evident from the error message). Problem is, this a new error so I am not exactly sure what can be done here. Would it be possible for you to share you input data or some sample data which throws this error so that I can try to replicate it? I would guess that .coords file and the reference and query chromosome ids and corresponding chromosome sizes should be enough.

**Comment by fergsc** [comment]
Thanks for the help. I have attached (hopefully) the coords, and scaffold names and sizes for both genomes. Happy to provide more data if required.

[error.zip](https://github.com/schneebergerlab/syri/files/3572049/error.zip)

**Comment by mnshgl0110** [comment]
HI Scott, thanks for sharing the data. The function that I thought to have the bug (getNotAligned) seems to be working fine for me and I do get the results (attached). The other possible (however extremely unlikely) cause that I could think of is incorrect reading of the chromosome ids from the fasta files. To test that could you please replace the findsv.pyx file in the syri/pyxfiles/ folder with the one that I have attached. You would need to change the name of this file. Then compile again and re-run it. If there are inconsistencies in how the chromosome ids are being read from the fasta file and from the coords file, then there should be an print statement showing that error.  

If you would prefer not to try to debug it yourself, then could you please share some sample data (including genomes) which results in this error.
[debug.zip](https://github.com/schneebergerlab/syri/files/3573785/debug.zip)

**Comment by fergsc** [comment]
Hi Manish, sent you an email.

**Comment by fergsc** [comment]
Found the problem.

I was filtering my nucmer results to remove SNPs and indels (delta-filter -l 100). SyRI went looking for SNPs and indels and crashed when it didn't find any. I needed to add --nosnp to my SyRI call.
ie
```
/path_to_syri/bin/syri -c blah.coords \
	-r $REF \
	-q $QUERY \
	-d blah.delta \
	--nosnp
```

**Comment by mnshgl0110** [comment]
Hi Scott, thanks for sharing data and log files. First thing that I observed was that the error, that you got now was different from the original error in this thread. So, I assume that the original issue reported here is solved.

Secondly, I do not think that `delta-filter -l 100` would cause this, as it filters out for small alignments, but the larger alignments could still have SNPs and indels (mismatches and gaps in alignments). When I tried SyRI on the data (including the delta file) that you shared, it worked, which also suggest that there should not be any incompatibility between MUMmer 4 output and SyRI. I think the issue could be that `show-snps` utility from mummer is not in your environment PATH or that SyRI is not able to find it correctly. You can set the path to `show-snps` manually using the `-s` option in SyRI.

**Comment by fergsc** [comment]
Hi Manish, your correct. I finally got SyRI to fully work. I added ``` -s /path_to_mummer-4.0.0beta2/show-snps ``` and now it all works beautifully.

Thanks for your help.
