### ISSUE TITLE
package list for syri-1.5 (python3.8) installation

### ISSUE THREAD

**Issue by comery** [schneebergerlab/syri#110]
Hi, many thanks for your development of this useful tool!

I try to install the version of 1.5 based on python3.8 typing using "conda env create -f syRi_v1.5_py3.8.yaml". but it always failed because of package version conflicts, so I am wondering could you give a recommended package list with a specific version that you used or verified. it will be very helpful!

for your information, syRi_v1.5_py3.8.yaml is like this:
---------------------
name: syri_v5
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.8
  - biopython
  - numpy
  - pandas==0.23.4
  - Cython
  - numpy
  - scipy
  - python-igraph
  - biopython
  - psutil
  - pysam
  - matplotlib

-------------------------------- standard error----------------------
conda env create -f syRi_v1.5_py3.8.yaml
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                     /
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                      -                                              /

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package tzdata conflicts for:
biopython -> python[version='>=3.9,<3.10.0a0'] -> tzdata
scipy -> python[version='>=3.10,<3.11.0a0'] -> tzdata
matplotlib -> python[version='>=3.10,<3.11.0a0'] -> tzdata
cython -> python[version='>=3.10,<3.11.0a0'] -> tzdata
python-igraph -> python[version='>=3.9,<3.10.0a0'] -> tzdata
pysam -> python[version='>=3.9,<3.10.0a0'] -> tzdata
psutil -> python[version='>=3.9,<3.10.0a0'] -> tzdata
numpy -> python[version='>=3.10,<3.11.0a0'] -> tzdata

Package icu conflicts for:
python-igraph -> libxml2[version='>=2.9.12,<2.10.0a0'] -> icu[version='>=58.2,<59.0a0|>=69.1,<70.0a0']
matplotlib -> matplotlib-base[version='>=3.3.0,<3.3.1.0a0'] -> icu[version='>=64.2,<65.0a0|>=67.1,<68.0a0']
matplotlib -> icu[version='>=58.2,<59.0a0']
python-igraph -> icu[version='>=64.2,<65.0a0|>=67.1,<68.0a0|>=68.1,<69.0a0']

Package libnsl conflicts for:
cython -> python[version='>=3.7,<3.8.0a0'] -> libnsl[version='>=2.0.0,<2.1.0a0']
pandas==0.23.4 -> python[version='>=3.7,<3.8.0a0'] -> libnsl[version='>=2.0.0,<2.1.0a0']
numpy -> python[version='>=3.10,<3.11.0a0'] -> libnsl[version='>=2.0.0,<2.1.0a0']
psutil -> python[version='>=3.7,<3.8.0a0'] -> libnsl[version='>=2.0.0,<2.1.0a0']
pysam -> python[version='>=3.7,<3.8.0a0'] -> libnsl[version='>=2.0.0,<2.1.0a0']
biopython -> python[version='>=3.10,<3.11.0a0'] -> libnsl[version='>=2.0.0,<2.1.0a0']
matplotlib -> python[version='>=3.10,<3.11.0a0'] -> libnsl[version='>=2.0.0,<2.1.0a0']
scipy -> python[version='>=3.10,<3.11.0a0'] -> libnsl[version='>=2.0.0,<2.1.0a0']
python-igraph -> python[version='>=3.7,<3.8.0a0'] -> libnsl[version='>=2.0.0,<2.1.0a0']

Package gdbm conflicts for:
matplotlib -> pypy3.7[version='>=7.3.7'] -> gdbm[version='>=1.18,<1.19.0a0']
cython -> pypy3.7[version='>=7.3.7'] -> gdbm[version='>=1.18,<1.19.0a0']
biopython -> pypy3.7[version='>=7.3.7'] -> gdbm[version='>=1.18,<1.19.0a0']
numpy -> pypy3.7[version='>=7.3.7'] -> gdbm[version='>=1.18,<1.19.0a0']
psutil -> pypy3.7[version='>=7.3.7'] -> gdbm[version='>=1.18,<1.19.0a0']
python-igraph -> pypy3.7[version='>=7.3.7'] -> gdbm[version='>=1.18,<1.19.0a0']
scipy -> pypy3.7[version='>=7.3.7'] -> gdbm[version='>=1.18,<1.19.0a0']

Package python conflicts for:
psutil -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*']
pandas==0.23.4 -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
cython -> python_abi=3.7[build=*_cp37m] -> python[version='3.10.*|3.7.*|3.9.*|3.8.*']
numpy -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*']
scipy -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*']
biopython -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*']
numpy -> python_abi=3.10[build=*_cp310] -> python[version='3.10.*|3.9.*|3.8.*|3.7.*']
pysam -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*|<3.0.0']
scipy -> python_abi=3.10[build=*_cp310] -> python[version='3.10.*|3.8.*|3.9.*|3.7.*']
psutil -> python_abi=3.7[build=*_cp37m] -> python[version='3.10.*|3.7.*|3.9.*|3.8.*']
python-igraph -> texttable[version='>=1.6.2'] -> python[version='2.7.*|>=3.5|=2.7|>=3.5|3.9.*|3.7.*|3.8.*|>=3.10,<3.11.0a0']
cython -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.*']
pysam -> python_abi=3.7[build=*_cp37m] -> python[version='3.7.*|3.8.*|3.9.*']
python==3.8
python-igraph -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0|3.4.*']
biopython -> python_abi=3.9[build=*_cp39] -> python[version='3.10.*|3.9.*|3.8.*|3.7.*']
pandas==0.23.4 -> numpy[version='>=1.9.3,<2.0a0'] -> python[version='2.7.*|3.5.*|3.6.*|>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|3.4.*|>=3.6|>=3']

Package openblas-devel conflicts for:
numpy -> openblas[version='>=0.3.3,<0.3.4.0a0'] -> openblas-devel[version='0.3.10|0.3.13|0.3.3|>=0.2.20,<0.2.21.0a0|0.3.6|0.3.6|0.3.6|>=0.3.2,<0.3.3.0a0',build='1|2|h06a4308_0|2|3|1|0|0']
scipy -> openblas[version='>=0.3.3,<0.3.4.0a0'] -> openblas-devel[version='0.3.3|>=0.2.20,<0.2.21.0a0',build='2|3|1']

Package blis conflicts for:
numpy -> libblas[version='>=3.8.0,<4.0a0'] -> blis[version='0.5.1.*|>=0.5.2,<0.5.3.0a0|>=0.6.0,<0.6.1.0a0|>=0.6.1,<0.6.2.0a0|>=0.7.0,<0.7.1.0a0|>=0.8.0,<0.8.1.0a0|>=0.8.1,<0.8.2.0a0']
scipy -> libblas[version='>=3.8.0,<4.0a0'] -> blis[version='0.5.1.*|>=0.5.2,<0.5.3.0a0|>=0.6.0,<0.6.1.0a0|>=0.6.1,<0.6.2.0a0|>=0.7.0,<0.7.1.0a0|>=0.8.0,<0.8.1.0a0|>=0.8.1,<0.8.2.0a0']
python-igraph -> libblas[version='>=3.8.0,<4.0a0'] -> blis[version='0.5.1.*|>=0.5.2,<0.5.3.0a0|>=0.6.0,<0.6.1.0a0|>=0.6.1,<0.6.2.0a0|>=0.7.0,<0.7.1.0a0|>=0.8.0,<0.8.1.0a0|>=0.8.1,<0.8.2.0a0']

Package six conflicts for:
numpy -> mkl-service[version='>=2.3.0,<3.0a0'] -> six
pandas==0.23.4 -> python-dateutil[version='>=2.5.*'] -> six[version='>=1.5']
matplotlib -> cycler -> six[version='>=1.5']
scipy -> mkl-service[version='>=2.3.0,<3.0a0'] -> six

Package pypy3.7 conflicts for:
matplotlib -> python[version='>=3.7,<3.8.0a0'] -> pypy3.7[version='7.3.*|7.3.3.*|7.3.4.*|7.3.5.*|7.3.7.*']
matplotlib -> pypy3.7[version='>=7.3.3|>=7.3.4|>=7.3.5|>=7.3.7']

Package libcblas conflicts for:
numpy -> libcblas[version='>=3.8.0,<4.0a0']
pandas==0.23.4 -> numpy[version='>=1.9.3,<2.0a0'] -> libcblas[version='>=3.8.0,<4.0a0']
numpy -> blas=[build=openblas] -> libcblas[version='3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0',build='5_mkl|7_mkl|8_mkl|10_mkl|12_mkl|14_mkl|18_mkl|19_mkl|20_mkl|21_mkl|6_mkl|8_mkl|9_mkl|11_linux64_mkl|2_openblas|5_openblas|8_openblas|9_openblas|10_openblas|11_openblas|13_openblas|16_openblas|8_openblas|9_openblas|12_linux64_openblas|11_linux64_openblas|10_openblas|7_openblas|6_openblas|5_openblas|17_openblas|15_openblas|14_openblas|12_openblas|7_openblas|6_openblas|4_openblas|3_openblas|0_openblas|12_linux64_mkl|10_mkl|7_mkl|5_mkl|16_mkl|15_mkl|13_mkl|11_mkl|9_mkl|6_mkl|4_mkl']
biopython -> numpy -> libcblas[version='>=3.8.0,<4.0a0']
scipy -> blas=[build=openblas] -> libcblas[version='3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0',build='5_mkl|7_mkl|8_mkl|10_mkl|12_mkl|14_mkl|18_mkl|19_mkl|20_mkl|21_mkl|6_mkl|8_mkl|9_mkl|11_linux64_mkl|2_openblas|5_openblas|8_openblas|9_openblas|10_openblas|11_openblas|13_openblas|16_openblas|8_openblas|9_openblas|12_linux64_openblas|11_linux64_openblas|10_openblas|7_openblas|6_openblas|5_openblas|17_openblas|15_openblas|14_openblas|12_openblas|7_openblas|6_openblas|4_openblas|3_openblas|0_openblas|12_linux64_mkl|10_mkl|7_mkl|5_mkl|16_mkl|15_mkl|13_mkl|11_mkl|9_mkl|6_mkl|4_mkl']
matplotlib -> numpy=1.11 -> libcblas[version='>=3.8.0,<4.0a0']
scipy -> libcblas[version='>=3.8.0,<4.0a0']
pysam -> bcftools -> libcblas[version='>=3.8.0,<4.0a0']
python-igraph -> suitesparse[version='>=5.10.1,<6.0a0'] -> libcblas[version='>=3.8.0,<4.0a0']

Package libuuid conflicts for:
numpy -> python[version='>=3.10,<3.11.0a0'] -> libuuid[version='>=1.0.3,<2.0a0|>=2.32.1,<3.0a0']
biopython -> python[version='>=3.10,<3.11.0a0'] -> libuuid[version='>=1.0.3,<2.0a0|>=2.32.1,<3.0a0']
matplotlib -> python[version='>=3.10,<3.11.0a0'] -> libuuid[version='>=1.0.3,<2.0a0|>=2.32.1,<3.0a0']
scipy -> python[version='>=3.10,<3.11.0a0'] -> libuuid[version='>=1.0.3,<2.0a0|>=2.32.1,<3.0a0']
cython -> python[version='>=3.10,<3.11.0a0'] -> libuuid[version='>=1.0.3,<2.0a0|>=2.32.1,<3.0a0']
psutil -> python[version='>=3.10,<3.11.0a0'] -> libuuid[version='>=1.0.3,<2.0a0|>=2.32.1,<3.0a0']

Package libblas conflicts for:
scipy -> libcblas[version='>=3.8.0,<4.0a0'] -> libblas[version='3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0.*|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0.*',build='4_blis|5_blis|5_mkl|8_openblas|8_mkl|9_openblas|9_blis|9_mkl|10_blis|10_openblas|10_mkl|11_openblas|13_mkl|13_openblas|13_blis|14_openblas|14_blis|14_mkl|16_openblas|16_blis|18_mkl|19_mkl|20_mkl|1_blis|1_openblas|2_openblas|3_openblas|5_mkl|6_mkl|7_openblas|7_mkl|8_mkl|9_mkl|10_blis|11_linux64_mkl|12_linux64_blis|12_linux64_mkl|12_linux64_openblas|11_linux64_openblas|11_linux64_blis|10_mkl|10_openblas|9_openblas|9_blis|8_openblas|8_blis|7_blis|6_openblas|6_blis|5_openblas|5_blis|4_mkl|4_openblas|4_blis|3_blis|2_blis|0_openblas|0_blis|21_mkl|17_openblas|16_mkl|15_openblas|15_mkl|15_blis|12_mkl|12_openblas|12_blis|11_mkl|11_blis|8_blis|7_mkl|7_openblas|7_blis|6_mkl|6_openblas|6_blis|5_openblas|4_mkl|4_openblas']
python-igraph -> libblas[version='>=3.8.0,<4.0a0']
matplotlib -> numpy=1.11 -> libblas[version='>=3.8.0,<4.0a0']
biopython -> numpy -> libblas[version='>=3.8.0,<4.0a0']
scipy -> libblas[version='>=3.8.0,<4.0a0']
pandas==0.23.4 -> numpy[version='>=1.9.3,<2.0a0'] -> libblas[version='>=3.8.0,<4.0a0']
python-igraph -> liblapack[version='>=3.8.0,<4.0a0'] -> libblas[version='3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0.*|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0.*',build='4_mkl|5_mkl|7_openblas|8_openblas|8_mkl|9_openblas|9_mkl|10_mkl|11_openblas|12_mkl|13_mkl|13_openblas|14_openblas|14_mkl|15_openblas|18_mkl|19_mkl|20_mkl|21_mkl|1_openblas|5_mkl|6_mkl|7_mkl|8_openblas|9_openblas|9_mkl|10_openblas|10_mkl|11_linux64_openblas|11_linux64_mkl|12_linux64_openblas|12_linux64_mkl|8_mkl|7_openblas|6_openblas|5_openblas|4_mkl|4_openblas|3_openblas|2_openblas|0_openblas|17_openblas|16_mkl|16_openblas|15_mkl|12_openblas|11_mkl|10_openblas|7_mkl|6_mkl|6_openblas|5_openblas|4_openblas']
numpy -> libblas[version='>=3.8.0,<4.0a0']
numpy -> libcblas[version='>=3.8.0,<4.0a0'] -> libblas[version='3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0.*|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0.*',build='4_blis|5_blis|5_mkl|8_openblas|8_mkl|9_openblas|9_blis|9_mkl|10_blis|10_openblas|10_mkl|11_openblas|13_mkl|13_openblas|13_blis|14_openblas|14_blis|14_mkl|16_openblas|16_blis|18_mkl|19_mkl|20_mkl|1_blis|1_openblas|2_openblas|3_openblas|5_mkl|6_mkl|7_openblas|7_mkl|8_mkl|9_mkl|10_blis|11_linux64_mkl|12_linux64_blis|12_linux64_mkl|12_linux64_openblas|11_linux64_openblas|11_linux64_blis|10_mkl|10_openblas|9_openblas|9_blis|8_openblas|8_blis|7_blis|6_openblas|6_blis|5_openblas|5_blis|4_mkl|4_openblas|4_blis|3_blis|2_blis|0_openblas|0_blis|21_mkl|17_openblas|16_mkl|15_openblas|15_mkl|15_blis|12_mkl|12_openblas|12_blis|11_mkl|11_blis|8_blis|7_mkl|7_openblas|7_blis|6_mkl|6_openblas|6_blis|5_openblas|4_mkl|4_openblas']

Package setuptools conflicts for:
python==3.8 -> pip -> setuptools
cython -> setuptools
matplotlib -> setuptools

Package libgfortran5 conflicts for:
scipy -> libgfortran5[version='>=9.3.0|>=9.4.0']
scipy -> libgfortran-ng -> libgfortran5[version='10.3.0|10.3.0|10.3.0|10.3.0|10.3.0|10.3.0|10.3.0|10.3.0|11.1.0|11.1.0|11.1.0|11.1.0|11.1.0|11.2.0|9.4.0|9.4.0|9.4.0|9.4.0|9.4.0|9.4.0|9.4.0|9.4.0|9.3.0.*|8.5.0|8.5.0|8.5.0|8.5.0|8.4.0.*',build='h0ffbd86_8|h0ffbd86_10|h62347ff_4|h62347ff_5|h62347ff_6|h62347ff_8|h62347ff_10|hb56cab1_4|hb56cab1_5|hb56cab1_6|hb56cab1_7|hb56cab1_9|h6c583b3_4|h6c583b3_6|h6c583b3_8|h5c6108e_8|h5c6108e_9|h5c6108e_11|h5c6108e_10|h6c583b3_7|h6c583b3_5|hb56cab1_11|hb56cab1_10|hb56cab1_8|h62347ff_11|h62347ff_9|h62347ff_7|h0ffbd86_11|h0ffbd86_9']

Package gmp conflicts for:
scipy -> libgcc -> gmp[version='>=4.2']
python-igraph -> glpk[version='>=4.65,<4.66.0a0'] -> gmp[version='6.1.*|>=6.1.2,<7.0a0|>=6.1.2|>=5.0.1,<7']
pysam -> libgcc -> gmp[version='>=4.2']
python-igraph -> gmp[version='>=6.2.0,<7.0a0|>=6.2.1,<7.0a0']

Package pillow conflicts for:
matplotlib -> matplotlib-base[version='>=3.5.0,<3.5.1.0a0'] -> pillow[version='>=6.2.0']
biopython -> reportlab -> pillow[version='>=2.4.0|>=4.0.0']

Package isl conflicts for:
pysam -> libgcc -> isl
scipy -> libgcc -> isl

Package matplotlib conflicts for:
matplotlib
pysam -> bcftools -> matplotlib

Package python-dateutil conflicts for:
pandas==0.23.4 -> python-dateutil[version='>=2.5.*']
matplotlib -> matplotlib-base[version='>=3.5.0,<3.5.1.0a0'] -> python-dateutil[version='>=2.1|>=2.7']
matplotlib -> python-dateutil

Package libgcc conflicts for:
matplotlib -> pyqt -> libgcc
pysam -> libgcc
scipy -> libgcc

Package python_abi conflicts for:
matplotlib -> python_abi[version='3.10.*|3.8.*|3.9.*|3.7.*|3.7|3.6|3.6.*',build='*_cp36m|*_pypy37_pp73|*_cp38|*_cp310|*_cp39|*_cp37m|*_pypy36_pp73']
matplotlib -> matplotlib-base[version='>=2.2.5,<2.2.6.0a0'] -> python_abi=2.7[build=*_cp27mu]

Package libgfortran4 conflicts for:
scipy -> libgfortran4[version='>=7.5.0']
scipy -> libgfortran-ng -> libgfortran4=7.5.0

Package pypy3.6 conflicts for:
matplotlib -> pypy3.6[version='>=7.3.2|>=7.3.3']
matplotlib -> tornado -> pypy3.6[version='7.3.*|7.3.0.*|7.3.1.*|7.3.2.*|7.3.3.*|>=7.3.1']

Package certifi conflicts for:
cython -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
matplotlib -> matplotlib-base[version='>=3.5.0,<3.5.1.0a0'] -> certifi[version='>=2016.09|>=2016.9.26|>=2020.06.20']

Package numpy conflicts for:
numpy
biopython -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.8|>=1.11.3,<2.0a0|>=1.9.3,<2.0a0|>=1.14.1,<2.0a0']
pandas==0.23.4 -> numpy[version='>=1.11.3,<2.0a0|>=1.9.3,<2.0a0']
scipy -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11|>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.16.5,<2.0a0|>=1.16.6,<2.0a0|>=1.17.5,<2.0a0|>=1.18.5,<2.0a0|>=1.19.5,<2.0a0|>=1.21.4,<2.0a0|>=1.19.4,<2.0a0|>=1.19.2,<2.0a0|>=1.18.1,<2.0a0|>=1.9.3,<2.0a0|>=1.9|>=1.15.1,<2.0a0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__glibc==2.17=0
  - biopython -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - cython -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - numpy -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - pandas==0.23.4 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - psutil -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - pysam -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - python-igraph -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - python==3.8 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - scipy -> libgfortran-ng -> __glibc[version='>=2.17']

Your installed version is: 2.17

**Comment by mnshgl0110** [comment]
Hi,
Sorry for the issues. I still need to finalise the documentation for python 3.8.
SyRI installs with the following package/versions:
```
biopython                 1.78            py38h7b6447c_0.conda
matplotlib                3.3.4            py38h06a4308_0  
matplotlib-base           3.3.4            py38h62a2d02_0  
numpy                     1.20.2           py38h62767a5_0  
numpy-base                1.20.2           py38he2ba247_0  
pandas                    1.2.4            py38h2531618_0  
psutil                    5.8.0            py38h27cfd23_1  
pysam                     0.16.0.1         py38hf7546f9_3    bioconda
python                    3.8.10               h12debd9_8  
python-igraph             0.9.1            py38h2af5540_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
scipy                     1.6.2            py38hf56f3a7_1
cython                    0.29.23
```
Hope this help. Let me know if still there are issues.
BTW, in your .yaml, numpy as biopython are twice and I think cython should be with a small 'c'

**Comment by comery** [comment]
Hi,

It looks great! I have installed the syri-1.5 successfully!

Thank you very much!
