### ISSUE TITLE
A question about "HDR"

### ISSUE THREAD

**Issue by anxuan-web** [schneebergerlab/syri#112]
Hello!
I want to konw how to evaluate "HDR" in result file.

**Comment by mnshgl0110** [comment]
Hi. What do you mean by "evaluate"? Could you please provide more details? Thanks

**Comment by anxuan-web** [comment]
![image](https://user-images.githubusercontent.com/77531332/147092429-244000e5-bee6-4ebf-823a-7ed44888e028.png)

Hello！
Why is this sequence called "HDR"? 
How is it calculated? For example, the sequence alignment rate is low .

Best wishes!

**Comment by mnshgl0110** [comment]
Check here: https://github.com/schneebergerlab/syri/issues/44 https://github.com/schneebergerlab/syri/issues/87
