### ISSUE TITLE
chroder : No matching contigs for reference chromosome

### ISSUE THREAD

**Issue by mnshgl0110** [schneebergerlab/syri#114]
![image](https://user-images.githubusercontent.com/87321600/147525870-02034f6d-9272-482d-a873-0dc3d90cbb0c.png)
![image](https://user-images.githubusercontent.com/87321600/147525882-26e55f93-1fea-43c9-a2a6-b9c07f6b144d.png)
I tried to simulate pseudochromosomes using Chroder, but I couldn't find a match on any chromosome in the reference genome. At first, chromosome 1 didn't match, so I deleted chromosome 1 in the Coords file and ref.fas, but it kept dropping errors. Should I keep deleting chromosomes down?

_Originally posted by @leyanKk in https://github.com/schneebergerlab/syri/issues/113#issuecomment-1001853966_

**Comment by mnshgl0110** [comment]
This is weird and is indeed unexpected behaviour.
Could you please confirm that the two genomes are closely related, i.e. large parts of the genomes are indeed similar. For this, you can draw the mummerplot. If possible, can you share it as well?

**Comment by leyanKk** [comment]
They're not that far apart, but they belong to two different genera, mouse and zokor
![OUTFig](https://user-images.githubusercontent.com/87321600/147571392-0c0f1545-bc31-4beb-9062-73268352c273.png)
 I wonder if my mummer is running incorrectly

**Comment by mnshgl0110** [comment]
Well, from this plot it is clear that the genomes, or at least the alignments, are not very similar. In case you are using nucmer4, then I would suggest that you try nucmer3 as in my experience that gives better results. You can also try minimap2 (version 2.17 works best for genome comparisons).

**Comment by leyanKk** [comment]
I use the numer3. I try minimap2

**Comment by leyanKk** [comment]
After using Minimap2, errors will still be reported, regardless of the Sam or BAM format
![image](https://user-images.githubusercontent.com/87321600/147577311-2fb0b8e8-569e-4203-90a8-fa0ab8fed06e.png)
![image](https://user-images.githubusercontent.com/87321600/147577365-225c9e18-3e0a-439b-bb07-fe596d4b3a32.png)

**Comment by mnshgl0110** [comment]
It seems pysam is not installed correctly. Installing it should fix the issue.

**Comment by leyanKk** [comment]
![image](https://user-images.githubusercontent.com/87321600/147618091-dc3f770a-68ca-424b-9c48-877806b8f882.png)
![image](https://user-images.githubusercontent.com/87321600/147618123-b47d588d-f40e-4359-a63c-a44d1b52dcc7.png)
Should my pysam be installed successfully before this

**Comment by mnshgl0110** [comment]
Based on the discussion here: https://github.com/bactopia/bactopia/issues/12 upgrading pysam should fix it.
Try upgrading to pysam v0.15.2

**Comment by leyanKk** [comment]
Pysam is upgraded to V0.15.2, or v0.15.3, depending on the upgrade method. The main reason is the Python version. The Syri Python version requires PYTHON 3.5
[nohup.txt](https://github.com/schneebergerlab/syri/files/7791800/nohup.txt)

**Comment by mnshgl0110** [comment]
Have you tried installing v0.15.2? I have that installed with python 3.5.6, so I assume that it should work.

**Comment by leyanKk** [comment]
Installing this version also failed
`conda install -c conda-forge -c bioconda pysam=0.15.2`
`conda list |grep 'pysam'`
`pysam                     0.14.1           py35hae42fb6_1    bioconda`
[nohup.txt](https://github.com/schneebergerlab/syri/files/7795084/nohup.txt)

**Comment by mnshgl0110** [comment]
My best probable guess is that there could be some issues with your working environment. I tried installing from fresh python3.5.6 and pysam0.15.2 and it worked.
```
conda create -n tpy3.5.6 python=3.5.6
conda activate tpy3.5.6
conda install -c bioconda pysam=0.15.2
(tpy3.5.6) 12:05 goel@pc-t7-130 goel:~$ conda list | grep python
python                    3.5.6                hc3d631a_0  
(tpy3.5.6) 12:06 goel@pc-t7-130 goel:~$ conda list | grep pysam
pysam                     0.15.2           py35h0380709_0    bioconda
```
The only thing I can suggest is to try with a new environment and maybe use the above commands.
