### ISSUE TITLE
using other genome aligners

### ISSUE THREAD

**Issue by dcopetti** [schneebergerlab/syri#117]
Hello,
I wonder if you see an advantage in using Winnowmap or lra over minimap2 for aligning repetitive plant genome assemblies.
Especially, regarding finding alignments between genes spaced by large regions of repetitive sequences that can be totally different from a genotype to another.
Thanks,
Dario

**Comment by mnshgl0110** [comment]
Hi. I have not tested those aligners yet, so not possible for me to give a direct answer. However, I would imagine that the genic regions would be aligned by all tools with high accuracy as generally the alignments corresponds to local alignments. Meaning that highly conserved regions (genes) would be aligned well irrespective of the surrounding regions.
The challenge and variation in the alignments would probably come from how these varied regions are aligned. Mummer3 tends to have alignments breaks at these noisy repetitive regions and while minimap2 often span over them. Consequently, I find that mummer3 is much more sensitive than minimap2 but the results could often noisy.

**Comment by pjm43** [comment]
Hi Dario,

Per your comment above regarding using other aligner for repetitive plant genomes, I’m wondering if you had success with any other aligners?  I’m running minimap2, but my oat chromosomes (~500 Mb each) are taking forever to align using the minimap2 -ax asm5 flag.  

Thanks,
Jeff

**Comment by dcopetti** [comment]
Hi Jeff,
No, I did not have time to test different aligners - not even to start doing the alignments for Syri yet. I was just exploring the options before starting to work on it. Once I find out something, I will report it here.
