### ISSUE TITLE
SyRI module error

### ISSUE THREAD

**Issue by ssamberkar** [schneebergerlab/syri#119]
Hi,

I've installed SyRI, I get the help and version when I run it but when I run it on actual bam file, it prompts this error.

`Traceback (most recent call last):
  File "/home/ssa18/local/bin/syri", line 163, in <module>
    from syri.pyxFiles.synsearchFunctions import readCoords
ModuleNotFoundError: No module named 'syri'`

**Comment by mnshgl0110** [comment]
It is not installed properly. What commands did you run for installing? What was the output from the install command? Can you do `import syri` in a python console?

**Comment by ssamberkar** [comment]
I could import it once I deactivated my conda environment.
