### ISSUE TITLE
CIGAR string incorrect

### ISSUE THREAD

**Issue by nicolasalexandre21** [schneebergerlab/syri#120]
It looks like perhaps the more recent minimap2 outputs which include 'M' in the cigar string may not be compatible...

SAM reader - ERROR - Incorrect CIGAR string found. CIGAR string can only have I/D/H/S/X/=. CIGAR STRING: 4009S57M1D29M1D274M2I187M1D155M2D18M6I9M2D12M1I36M7D74M1I14M13I56M11I3M10I144M3I133M1I64M2D95M1I39M1D10M6D475M1I7M587D10M8D207M4D176M11I164M7D536M31I37M10I3M12I177M278D15M1I153M3D256M1I149M263D231M5D99M1D27M8I57M1I57M1D75M2D18M2I149M8I246M4I16M3I63M1I78M1I104M3D92M7D24M1D350M1I64M1I101M1D385M1I67M546S

I generated my sam file like so:

minimap2 -ax asm20 --cs -t 20 Reference.fa Query.fna > Anna.sam
and
minimap2 -ax asm20 -t 20 Reference.fa Query.fna > Anna.sam

**Comment by mnshgl0110** [comment]
Please use the --eqx parameter

बुध, 2 फ़र॰ 2022, 8:57 pm को nicolasalexandre21 ***@***.***>
ने लिखा:

**Comment by nicolasalexandre21** [comment]
Thank you, problem solved.
