### ISSUE TITLE
If the vcf file that syri output can support to construct VG graph genome?

### ISSUE THREAD

**Issue by BRLIA** [schneebergerlab/syri#122]
Hi, I'm going to construct graph genome by VG, and I want to use the SVs detected by SyRI, but I don't know if the VCF file that SyRI output can support it.
Thanks

**Comment by mnshgl0110** [comment]
The output VCF is based on the VCFv4.3 format, so if VG reads that then it should work. However, I am not sure whether VG  handles all the different types of genomic differences that SyRI identifies (for ex: translocations or HDRs) . So, you might need to filter it out. This question is probably better suited for the VG developers.

**Comment by BRLIA** [comment]
OK，I will try it. 
Thank you for your help
