### ISSUE TITLE
large, repetitive genome

### ISSUE THREAD

**Issue by pjm43** [schneebergerlab/syri#123]
Hi,
Just a quick question regarding large (12 Gb), repetitive plant genome.  I'm following your tutorial with `minimap2 -ax asm5` for the alignment, but the alignment is taking quite along time for just a single, albeit large (642 Mb) chromosome (still running after 3 days).  I gave it 8 cpus each with 32 Gb mem.  It's only using a single cpu (even through I flagged `-t 8`) and is currently using 85 Gb of the memory allocated.   Any ideas how to speed up the alignment process?

Thanks in advance for any advice!

**Comment by mnshgl0110** [comment]
Hi Jeff, I think the easiest solution might be to just mask these repeats. In case, analysis of repeats is also required, then maybe try something like `-H -f 100 -q 2k --rmq=no --secondary=no`. But I too am guessing here, so probably it would be better if you also ask this question at the minimap2 repo for better advice.
I am also thinking how syri would handle this highly complex genome. It would be great if you could let me know whether it actually finishes and how long does it take (assuming that alignment would finish).

**Comment by mnshgl0110** [comment]
When you mask the genomes, you would get list of regions that are masked. After running syri, you would need to remove sequence variations (everything other than synteny, inversions, translocations, and duplications), that are overlapping these masked region.

Unfortunately, I do not have any code on how to do that exactly, so cannot help with that.

**Comment by pjm43** [comment]
Thanks for the help!
