### ISSUE TITLE
plostr error

### ISSUE THREAD

**Issue by zhangxn-flower** [schneebergerlab/syri#125]
hi, I'm running syri for analysis of genomes.
syri --version
1.5.4
python3 $PATH_TO_PLOTSR 
usage: Plotting structural rearrangements between genomes [-h] [--sr SR] [--bp BP] --genomes GENOMES [--markers MARKERS] [--tracks TRACKS] [--chrord CHRORD] [--chrname CHRNAME] [-o O] [--itx] [--chr CHR] [--reg REG] [--rtr] [--nosyn] [--noinv] [--notr] [--nodup] [-s S] [--cfg CFG] [-R] [-f F]  [-H H] [-W W] [-S S] [-d D] [-b {agg,cairo,pdf,pgf,ps,svg,template}] [-v] [--log {DEBUG,INFO,WARN}] [--version]

command line is like this : 
python3 $PATH_TO_PLOTSR --sr syri.out --genomes  genomes
cat genomes
/home	A.chr.fa	refgenome
/home	B.chr.fa	refgenome

but the error appear.
ImportError: Incomplete genomic information.
Expected format for the genome file:
path_to_genome1	genome1_id	tags
path_to_genome2	genome2_id	tags

Make sure that the columns are separated by tabs (and not spaces).
so, what should be the format of the input file --genomes 
Could you please guide if there is any solution, how to fix theproblem?

Many thanks,
xn

**Comment by mnshgl0110** [comment]
Hi Xn,
In the genomes.txt file, the first column needs to be the **complete path** to the .fa/.chrlen files whereas the second column should be genome-name. So, in this case, your genomes.txt file would look like:
```
/home/A.chr.fa refgenome
/home/B.chr.fa qrygenome
```
Also, make sure that the columns are separated by tab (and not spaces).

Best
Manish

P.S.:  It is more helpful if the questions for a repo (here plotsr) is asked in that repo only as it allows future users facing the same issue to find the solution quickly.

**Comment by TZM9882** [comment]
hello Manih,

I am very new to this whole process but still trying my best using manuals and similar issues by previous users. Thanks to those unknown users.

I also got below the error for plotsr. I followed the instructions.
Am I still wrong somewhere?
Image 2 is how I prepared genomes.txt for 2 genomes (A is reference).
Please help me with this problem

Thanks,
Mg 

![Screenshot 2023-06-23 at 10 32 26](https://github.com/schneebergerlab/syri/assets/129658757/fb57d2a7-2e22-4516-a624-0de04d059cb1)

![Screenshot 2023-06-23 at 10 35 04](https://github.com/schneebergerlab/syri/assets/129658757/0f1df135-2f64-4a9a-8497-6f2fd82ffa4a)
