### ISSUE TITLE
Merge SyRI VCF results 

### ISSUE THREAD

**Issue by ahishsujay** [schneebergerlab/syri#127]
Hi! I've recently used SyRI and have ~40 VCF files I would like to merge. Would you recommend using SURVIVOR (https://github.com/fritzsedlazeck/SURVIVOR) in order to merge these SVs? I plan on separating SNPs and INDELs, merging them using `bcftools merge` and using SURVIVOR to merge the remaining SVs.

Please let me know if you think this is a good idea, or any suggestions. 

Thanks!

**Comment by mnshgl0110** [comment]
Hi Ahish,

As far as I know, merging of non-SNP and non-indel variants is still not possible. In fact, we are developing methods that can merge complex non-linear rearrangements identified using genome comparisons.

Regarding SURVIVOR, I have not used the merge option of SURVIVOR extensively so I cannot comment on its applicability. However, my impression is that it works best for merging large indels and is designed for read based SV identification. I would suggest that you give it a try. SURVIVOR is quite easy to install and use, and is quite fast, so better to test and see if the output suits your project.

Best
Manish
