### ISSUE TITLE
Large InDel

### ISSUE THREAD

**Issue by jinshangkun** [schneebergerlab/syri#132]
Hello! 
I find that when the INS/DEL length is longer than 100, the columns of Ref/Alt will not display the specific sequence . Is there any parameter for it to display specific sequence information？Thanks!

For example:
A01     201756  INS9    N       <INS>   .       PASS END=201756;ChrB=A01;StartB=244412;EndB=244572;Parent=SYN6;VarType=ShV;DupType=

**Comment by mnshgl0110** [comment]
Currently there is no parameter to display larger indels in VCF. But this is a good idea and I will try to add it.

**Comment by prometheusloong** [comment]
Look forward to the implementation of this feature, and i hope that the sequence cloud also display in VCF format.

**Comment by mnshgl0110** [comment]
Indel printing added https://github.com/schneebergerlab/syri/commit/9b04c6a6383cebb68ac1c67ff0fda4344f5c0918
