### ISSUE TITLE
chroder IndexError: too many indices for array

### ISSUE THREAD

**Issue by Yung-Chien** [schneebergerlab/syri#14]
Hi @mnshgl0110 ,
when I run the chroder module, I got this error like this :

Traceback (most recent call last):
  File "/home1/lyj/software/syri/syri/bin/chroder", line 729, in <module>
    scaf(args)
  File "/home1/lyj/software/syri/syri/bin/chroder", line 337, in scaf
    refdata = getdata(reflength, refid, refdir)
  File "/home1/lyj/software/syri/syri/bin/chroder", line 104, in getdata
    a2 = a2[a2[:, 0].argsort()]
IndexError: too many indices for array

so how could I fix this problem? THanks in advance.

Best Regards,
Yung-Chien

**Comment by mnshgl0110** [comment]
Hi.
Can you please add ```print(a2)``` between the current line 103 and 104 and share the output with me?

**Comment by Yung-Chien** [comment]
Okay, thanks for your reply. I added the code into chroder, and got this :

[]
Traceback (most recent call last):
  File "/home1/lyj/software/syri/syri/bin/chroder", line 730, in <module>
    scaf(args)
  File "/home1/lyj/software/syri/syri/bin/chroder", line 338, in scaf
    refdata = getdata(reflength, refid, refdir)
  File "/home1/lyj/software/syri/syri/bin/chroder", line 105, in getdata
    a2 = a2[a2[:, 0].argsort()]
IndexError: too many indices for array

It seems that a2 was not assigned, so I got confused. Thanks and waiting for your idea :-D.

Yung-Chien

**Comment by mnshgl0110** [comment]
Hi. Sorry for a late reply. Normally, a2 should not be empty. This seems to be a result of non-ideal input or some uncaught exception. Could you please try to remove smaller contigs (<15000kb), and try to run the analysis again? I will try to find what could have caused this error.

**Comment by Yung-Chien** [comment]
Hi, 
Ummm It was still the same result when I removed the smaller contigs,

[]
Traceback (most recent call last):
  File "/home1/lyj/software/syri/syri/bin/chroder", line 730, in <module>
    scaf(args)
  File "/home1/lyj/software/syri/syri/bin/chroder", line 338, in scaf
    refdata = getdata(reflength, refid, refdir)
  File "/home1/lyj/software/syri/syri/bin/chroder", line 105, in getdata
    a2 = a2[a2[:, 0].argsort()]
IndexError: too many indices for array

Could you explain more details about the reason why it's always reported the same error? Maybe my input files were too big ? The two input files are 700MB and 600MB .Thanks for your patience.

Yung-Chien

**Comment by mnshgl0110** [comment]
Hi,
For now, I am not sure exactly why this error is coming up, however, I would not suspect that the input files size would be an issue.
What version of python are you using? I recently found out that few of the libraries used by SyRI have been modified for the newer version of python which is resulting in errors with SyRI. I recommend that you use python3.5 for running SyRI, and that might solve the error.
Another possible cause of error could be that there are highly repetitive contigs for which it was not possible to select any contig in the other genome which align to this repetitive contig better than the other contigs. As a result, it was not possible to select any matches for the original repetitive contig (resulting in empty a2).
What is your use case? Are you creating pseudo-genome using a chromosome-level reference genome or are both of your assemblies incomplete?
Best
Manish
