### ISSUE TITLE
Incorrect CIGAR string found

### ISSUE THREAD

**Issue by m-bogaerts** [schneebergerlab/syri#140]
I had an issue with the CIGAR string, since it is expecting to find  I/D/H/S/X/= but I have also D and M in my CIGAR. Is there any procedure to "clean" the CIGAR?

Thank you in advance.

Reading BAM/SAM file - ERROR - syri:130 - Incorrect CIGAR string found. CIGAR string can only have I/D/H/S/X/=. CIGAR STRING: 231M5D199M6I199M3D112M1I140M138D256M7D703M2I313M497838H

**Comment by mnshgl0110** [comment]
The aligner should have an option to output CIGAR with X/= instead of M.
In minimap2, this can be done using the `--eqx` parameter.
