### ISSUE TITLE
Unequal number of chromosomes in the genomes

### ISSUE THREAD

**Issue by diego-rt** [schneebergerlab/syri#142]
Hello,

Is there a way to have syri process genomes with different numbers of chromosomes? In my case, I basically have 4 "genomes" with a single chromosome, and one in which that single sequence rearranged into 4. When I follow the "Pipeline for visualising genomic differences" section on the plotsr page, I get the following error with syri: `Reading Coords - ERROR - Unequal number of chromosomes in the genomes. Exiting`.

Would be super cool if I could plot this using syri / plotsr!

Thanks and congrats on the cool program!

**Comment by mnshgl0110** [comment]
Syri expects same karyotype across genomes. So, by default, this case cannot be handled. But you can merge the 4 rearranged sequences to get 1 pseduochromosome and then you can analyse them normally. In the plotsr visualisation, you can add markers to point the positions where the sequences were merged. Though not-very elegant, but I think this may work.

**Comment by diego-rt** [comment]
I see, sounds like a good solution. Will try it. Thanks a lot!
