### ISSUE TITLE
Is translocation one kind of duplication variation?

### ISSUE THREAD

**Issue by sen1019san** [schneebergerlab/syri#147]
Hi Manish,
I find translocation regions are not 1:1 in the same chromosome between query and ref genome comparison. Here is an example that SYNAL is overlapping with TRANSAL:

![image](https://user-images.githubusercontent.com/43125963/174051569-81a19ec4-ec29-40e3-a347-fb6831d54bdd.png)
 
I try to explain this variation example:
![image](https://user-images.githubusercontent.com/43125963/174051702-3c274d69-4bc9-4e85-9770-33832f270a32.png)

It means that SYNAL24765 overlapping with TRANSAL38969, SYNAL14400 overlaps with TRANSAL38971, and SYNAL14401 overlaps with TRANSAL38972.

I wonder whether the translocation is 1:1 or 1:much between query and ref genome.

Thanks!

**Comment by mnshgl0110** [comment]
Syri allows some overlap between translocations and other variants. This is overlap is estimated at the translocation block level and not for individual alignments. For example, syri would call the blue region as translocated even though there is some overlap with syntenic (grey) regions
![image](https://user-images.githubusercontent.com/16225647/174248040-142a9959-bb3e-4be1-bfb5-474926e5acb4.png)

When a translocation consists of multiple alignments, then it is possible that some alignments overlap with syntenic regions like below.
![image](https://user-images.githubusercontent.com/16225647/174249322-21e18d12-ec4d-4d14-a4fb-29630897aaca.png)

I think this is the case that you have noticed. If you check the endpoints of TRANS22334 block, then there should be regions that are not overlapping with any syntenic/inverted region effectively making it a translocation. You can regulate the allowed overlap by changing the `--unic` and `--unip` parameters.

**Comment by sen1019san** [comment]
Thanks a lot, Manish. I am confused with the syri output for translocation and duplication definition. May I naively think that translocation is 1:1 between the reference genome and query genome.
