### ISSUE TITLE
missing sequence counts in summary file

### ISSUE THREAD

**Issue by mnshgl0110** [schneebergerlab/syri#148]
Hi @mnshgl0110 ,
In my summary file, structural annotations have values only, but in sequence annotations, all counts are showing 0 only. like attached below

#Structural annotations
#Variation_type Count   Length_ref      Length_qry
Syntenic regions        7188    2535240608      2528221404
Inversions      283     2464865 2439444
Translocations  8547    69687524        66748895
Duplications (reference)        955     6718295 -
Duplications (query)    6400    -       26763094
Not aligned (reference) 13165   82618600        -
Not aligned (query)     21911   -       80606870

#Sequence annotations
#Variation_type Count   Length_ref      Length_qry
SNPs    0       0       0
Insertions      0       -       0
Deletions       0       0       -
Copygains       0       -       0
Copylosses      0       0       -
Highly diverged 0       0       0
Tandem repeats  0       0       0

the command that I used was:
syri -c out.filtered.coords -d out.filtered.delta -r reference.fasta -q query.fasta -f --nc 50 --prefix new --all

Thank you

_Originally posted by @sahu-git in https://github.com/schneebergerlab/syri/issues/144#issuecomment-1157556576_

**Comment by mnshgl0110** [comment]
@sahu-git for my runs it is working. Maybe try reinstalling syri and running it again in an empty folder. Also, check whether there are SNPs or indels in the syri.out file.

**Comment by AS11-git** [comment]
hi thanks for your quick response @mnshgl0110 ,
snp.txt file was generated as an intermediate file with SNPs but in syri.out file no SNPs or indels are present.

Thank you

**Comment by mnshgl0110** [comment]
Could you please run syri with `--log debug` and share the syri.log file?

**Comment by AS11-git** [comment]
Thanx,
I attached the log file below 
[syri.log](https://github.com/schneebergerlab/syri/files/8926128/syri.log)

**Comment by mnshgl0110** [comment]
SNPs/indels are identified and processed for writing as clear by this log line (snps = ShV): `All annotation count. SR anno: 1412 SV anno: 102 ShV anno: 117903 notal anno: 403`. But there is no hint on what could be going wrong.

Could you share a minimal example for me to check (input genome files, alignments, and the commands)?

**Comment by AS11-git** [comment]
I attached files below (I run on the example file)
[out.filtered.delta.gz](https://github.com/schneebergerlab/syri/files/8926436/out.filtered.delta.gz)
[reference.fasta.gz](https://github.com/schneebergerlab/syri/files/8926437/reference.fasta.gz)
[newsyri.summary.gz](https://github.com/schneebergerlab/syri/files/8926428/newsyri.summary.gz)
[out.filtered.coords.gz](https://github.com/schneebergerlab/syri/files/8926429/out.filtered.coords.gz)
[query.fasta.gz](https://github.com/schneebergerlab/syri/files/8926430/query.fasta.gz)

**Comment by mnshgl0110** [comment]
I ran syri using these files and the command that you mentioned above and got complete [newsyri.summary.gz](https://github.com/schneebergerlab/syri/files/8927221/newsyri.summary.gz) file.

So, I still have no idea why it is not working for you.

Did you install syri from bioconda or github, and if github then you which branch?

**Comment by AS11-git** [comment]
I get the repository by git clone from the GitHub master branch.
ok, I will try to recheck again by bioconda.

thank you
