### ISSUE TITLE
Unable to Read SAM file

### ISSUE THREAD

**Issue by jasonbhn** [schneebergerlab/syri#15]
```
syri - WARNING - starting
Reading Coords - ERROR - Error in reading the SAM file
```
When I tried the following command: 
```
syri --cigar -c HG002PM_GRCh38.sam -r grch38.fa -q ragoo_output/ragoo.fasta -F S
```

**Comment by jasonbhn** [comment]
Does the SAM file need to be sorted in a particular manner?

**Comment by mnshgl0110** [comment]
Sorting should not be required.
Did you align only chromosomes-level assembly or contigs as well? This issue could be a result of unaligned contigs in the SAM file.
Also, what version of python are you using?
