### ISSUE TITLE
VCF4.2

### ISSUE THREAD

**Issue by zhoudreames** [schneebergerlab/syri#150]
I only need INS and DEL information， but the software requires the VCF4.2 format. can I get the VCF4.2 output result with syri ?

**Comment by zhoudreames** [comment]
@mnshgl0110 I am so sorry to disturb you, could you help me? thanks

**Comment by mnshgl0110** [comment]
Which tool are you trying to use? You can try changing the first line in the syri.vcf from `##fileformat=VCFv4.3` to `##fileformat=VCFv4.2`. Most probably, that would already work.
