### ISSUE TITLE
Inversion breakpoint definition

### ISSUE THREAD

**Issue by Chenglin20170390** [schneebergerlab/syri#152]
Hi Manish

I have a question about the defination of breakpoint of inversion in syri.  

Indeed, syri is a good tool for detecting genome rearrangement.  I noticed that syri report the breakpoint of inversion  base on the length of inversion alignment(first figure  and blue line). for some situation, we want to know the breakpoint of the synteny region which including this inverion(second figure and red line).

     Does syri can report the breakpoint of inverison like the red line in the second figure ?  What's your suggestions for accurate  breakpoint checking   of inversion?  
     
  Thanks  for advance!
![image](https://user-images.githubusercontent.com/33062118/177146639-8d85bec5-3d3a-441f-808e-c60c9092898e.png)
![image](https://user-images.githubusercontent.com/33062118/177147175-a6b9263f-aeb3-45c3-92da-2cc3793fa158.png)

**Comment by mnshgl0110** [comment]
It is not possible to get breakpoints as shown by the red line. In this example, the region between the horizontal red and blue line, is not aligned and would be annotated as such.
![image](https://user-images.githubusercontent.com/16225647/177149968-d676c4a9-760b-4349-b7ff-9657a81e672d.png)

If you want breakpoints as shown by red lines, then you can consider post-processing syri's output to add NOTAL (not aligned) regions to inversions.

**Comment by Chenglin20170390** [comment]
Thank you very much for your quick reply!
