### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rac266** [schneebergerlab/syri#154]
Hello,

I am using minimap2 output to run SyRi on a fishing cat and Asian leopard cat genome and am running into the following error: IndexError: list index out of range. The commands used, error output, and log file are below. I understand that SyRi needs homologous sequences to run, and these two are different species, however, they are closely related in the same clade. Any advice on how to go about fixing this error is greatly appreciated. Thank you for your help!
[syri.log](https://github.com/schneebergerlab/syri/files/9184068/syri.log)

Commands:
Python version 3.9.13
minimap2 -t 40 -ax asm5 --eqx final-al.fa final-fc.fa | samtools view -bh - | samtools sort - > al_vs_fc_alignment.bam

syri -c al_vs_fc_alignment.bam -r final-al.fa -q final-fc.fa -F B

Error:
Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - WARNING - Matching them automatically. For each reference genome, most similar query genome will be selected. Check mapids.txt for mapping used.
Reading Coords - WARNING - Reference chromosome NC_057345.1 has high fraction of inverted alignments with its homologous chromosome in the query genome (NC_062568.1). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
Reading Coords - WARNING - Reference chromosome NC_057350.1 has high fraction of inverted alignments with its homologous chromosome in the query genome (NC_062569.1). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
Reading Coords - WARNING - Reference chromosome NC_057352.1 has high fraction of inverted alignments with its homologous chromosome in the query genome (NC_062575.1). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
Reading Coords - WARNING - Reference chromosome NC_057359.1 has high fraction of inverted alignments with its homologous chromosome in the query genome (NC_062573.1). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/rac266/mambaforge/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/rac266/mambaforge/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 803, in syri.synsearchFunctions.syri
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rac266/mambaforge/bin/syri", line 6, in <module>
    main(sys.argv[1:])
  File "/home/rac266/mambaforge/lib/python3.9/site-packages/syri/scripts/syri.py", line 319, in main
    syri(args)
  File "/home/rac266/mambaforge/lib/python3.9/site-packages/syri/scripts/syri.py", line 209, in syri
    startSyri(args, coords[["aStart", "aEnd", "bStart", "bEnd", "aLen", "bLen", "iden", "aDir", "bDir", "aChr", "bChr"]])
  File "syri/pyxFiles/synsearchFunctions.pyx", line 505, in syri.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 506, in syri.synsearchFunctions.startSyri
  File "/home/rac266/mambaforge/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/rac266/mambaforge/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: list index out of range

**Comment by aaannaw** [comment]
Hello
I met the same error. Have you solved the problem? Could you give me any suggestion?
Thanks!

**Comment by mnshgl0110** [comment]
Please ensure that same strands are being compared for the homologous chromosomes. Check https://github.com/schneebergerlab/syri/issues/48

**Comment by aaannaw** [comment]
@mnshgl0110 
Thanks so much! I will check the strand.
Could you give me any suggestion about the issue #156 ?
