### ISSUE TITLE
Inversion missed

### ISSUE THREAD

**Issue by biozzq** [schneebergerlab/syri#155]
Dear @mnshgl0110 

If one contig mapped near the center of the chromosome and then split and mapped in reverse orientation to the beginning of the chromosome, it should be a inversion. However, syri missed it in my demo data. I have attached the fasta and BAM files here [demo.zip](https://github.com/schneebergerlab/syri/files/9205644/demo.zip), and the command i used is as follows, 

`syri -F B -r ref.fa -c demo.bam -q query.fa -k --nosnp --prefix demo`

Looking forward to your reply, thanks.

Sincerely,

Zheng zhuqing

**Comment by mnshgl0110** [comment]
Syri filters small/low-quality alignment. Using `-f` stops this filtering and you can find this small inversion.
```
(mgpy3.8) 11:05 goel@pc-t7-130 netscratch:issue155$ syri -f -F B -r ref.fa -c demo.bam -q query.fa -k --nosnp --prefix demo > garb 2> garb
(mgpy3.8) 11:05 goel@pc-t7-130 netscratch:issue155$ cat demosyri.out
ref	1	70	-	-	query	1	70	INV2	-	INV	-
ref	1	70	-	-	query	70	1	INVAL2	INV2	INVAL	-
ref	71	1820	-	-	-	-	-	NOTAL1	-	NOTAL	-
ref	1821	1960	-	-	query	71	210	SYN1	-	SYN	-
ref	1821	1960	-	-	query	71	210	SYNAL1	SYN1	SYNAL	-
ref	1961	3290	-	-	-	-	-	NOTAL2	-	NOTAL	-
```
