### ISSUE TITLE
can not output Syri.out

### ISSUE THREAD

**Issue by aaannaw** [schneebergerlab/syri#156]
Hello,Professor
I  am running the Syri with my two genome according to the example.sh:
```
nucmer -l 40 -c 200 -b 50 -p out A.fasta B.fasta -t 10(note: because of the parameter --maxmatch costs too much time,so I delete it)
delta-filter -m -i 90 -l 100 out.delta  > out.filtered.delta
show-coords -THrd  out.filtered.delta  >out.coords
python3 ~/miniconda3/envs/syri_env/bin/syri -c out.coords -d out.filtered.delta -r A..fasta -q B.fasta -s ~/miniconda3/envs/mummer4/bin/show-snps --nc 10
```
The results is `*dupOut.txt ,*invDupOut.txt,*invOut.txt by chromosome `like the following the picture and there is no *dupOut.txt ,*invDupOut.txt,*invOut.txt of several chromosomes.   At the same time, I  can not produce the `syri.out`  either by chr or whole genome like the example. I have successfully run the example.
Could you give me any suggestions? Thanks so much!
![image](https://user-images.githubusercontent.com/109299053/181733070-3581e276-f312-4835-8cb1-f29585171715.png)
[syri.log](https://github.com/schneebergerlab/syri/files/9218798/syri.log)

**Comment by mnshgl0110** [comment]
There is not anything obviously wrong in the log file. Are there any error messages?

**Comment by aaannaw** [comment]
The task I submit by SLURM `"python3 ~/miniconda3/envs/syri_env/bin/syri -c out.coords -d out.filtered.delta -r A..fasta -q B.fasta -s ~/miniconda3/envs/mummer4/bin/show-snps --nc 10" `is still ruuning, but it has produced nothing for two hours after poroducing the above files. In my submit task, the .err file storing standard error has nothing and the .out file storing standard out has the message:
```
Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - WARNING - Matching them automatically. For each reference genome, most similar query genome will be selected. Check mapids.txt for mapping used
```
I am not sure if it it the normal. I have tried several times, the above  files occurs for a short time, and then the task seems to be sleeping, nothing to produce.

**Comment by mnshgl0110** [comment]
For large, highly repetitive genomes, it can take some time for jobs to finish. It is expected and not an error.

**Comment by lrauschning** [comment]
Hm, the log file looks like it's everything is going alright, except SyRI does not proceed to SV identifications.
But the previous steps run quite fast, so I'm assuming the genome isn't too large or repetitive.
What are the exact parameters you are using, and have you checked if the SyRI job got killed because of insufficient memory on the node or something else?

**Comment by fanhuan** [comment]
> Hm, the log file looks like it's everything is going alright, except SyRI does not proceed to SV identifications. But the previous steps run quite fast, so I'm assuming the genome isn't too large or repetitive. What are the exact parameters you are using, and have you checked if the SyRI job got killed because of insufficient memory on the node or something else?

Hi Leon, 

I am comparing different assembly of the same species, though I am pretty sure they are from different individuals. Here are the cmd I ran:

1. Remove the small contigs and keep chromosomes only for both assemblies. 
2. Renamed the tags so the matching chromosomes have the same id chr1...chr16.
3. In a trial run it complained about some chromosomes are reverse-complement of each other so I fixed that.
5. minimap2 -c -x asm5 -t 20 --eqx ref_chr.fasta query_chr.renamed.rcfixed.fna > ref_query.paf 2> ref_query.paf.log
6. syri -c ref_query.paf -r ref_chr.fasta -q query_chr.renamed.rcfixed.fna -k -F P

Please help to check. 

Yes I was monitoring the syri run several times and the ram usages were low (like 1% on this standalone workstation). Anything else you could think of?

Thank you.

Best,
Huan

**Comment by lrauschning** [comment]
Weird, this might be an internal error in SyRI. It's crashing right before writing the calls to disk.
Can you try running a single chromosome of your species, and see if you get the same error?
As an aside, if not working in human its usually a safer bet to use asm10 as regions of the genome may have higher divergence, but that shouldn't affect the output much.
