### ISSUE TITLE
re-arragement between two Eukaryotic genomes

### ISSUE THREAD

**Issue by Karimi-81** [schneebergerlab/syri#157]
Hi there,
I am interested to find the number of re-arrangements between two large genomes. Naturally, the number of chromosomes (or scaffolds) is not equal for different species. Accordingly, if you use the same number of chromosomes for two species, some part of the data would not be captured. In addition, the names of chromosomes are also different. I wonder if you have any solution for these issues? 
Thanks

**Comment by mnshgl0110** [comment]
Check https://github.com/schneebergerlab/syri/issues/142 and https://github.com/schneebergerlab/syri/issues/136
