### ISSUE TITLE
different names of sequences

### ISSUE THREAD

**Issue by selmanurk** [schneebergerlab/syri#158]
Hi everyone, 
I have wild type and mutant transcriptome assemblies that I want to compare for  transcript rearrangements. I read on the site that the names should be same but assembler did not name same sequences as the same, I have tested this. I see you suggest merging files but I dont understand how this helps because even if I merged mutant and wt files and compare the same file with itself the names wouldn't be the same. Any suggestions?
thanks 
S

**Comment by mnshgl0110** [comment]
Firstly, syri was not designed and have not been tested for comparing transcriptomes. So I am not sure that this would even work. Theoretically, each assembled transcript can be considered as a chromosome and can be analysed similarly. However, these "chromosomes" would be very small and could void the assumptions that syri makes when annotating SRs.

Nevertheless, the primary requirement is that the chromosomes in the two genomes are homologous. You can try using the [fixchr](https://github.com/schneebergerlab/fixchr) which tries to automatically select and orient homologous chromosomes (in this case transcripts). This would create filtered reference and query genomes fasta that can be used with syri. However, fixchr was also developed keeping genomes as target so it might require some tweaking as well.
In case this works, it would be great if you could share the results.
