### ISSUE TITLE
ERROR - Numerical chromosome id

### ISSUE THREAD

**Issue by biozzq** [schneebergerlab/syri#160]
Dear all,

I found that syri will report an error if the chromosome name is a number, is this right?

Running SyRI - ERROR - Numerical chromosome id: 30 found in alignments. Please change it to string. Example: for chromosome 1, ">Chr1" is valid but ">1" is invalid. Exiting.

Looking forward to your reply, thanks.

Sincerely yours,
Zheng zhuqing

**Comment by mnshgl0110** [comment]
Yes. Adding some text to the chromosome name would solve this.

**Comment by hyBio** [comment]
> Yes. Adding some text to the chromosome name would solve this.
Why not try to add a parameter to avoid this? The user needs to modify both the .fa and .bam files, which is a time consuming task.It would be great if you could increase the parameters, but if not,  that's fine too. hahaha!😀
