### ISSUE TITLE
Inversion disappears after running chroder 

### ISSUE THREAD

**Issue by aaannaw** [schneebergerlab/syri#162]
Hello
We have two chromosomal level assemblies from two species and the two species has fission/fusion events and thus is different in chromosomal numbers  (A:31, B:32). I have used `chroder` to merge B species chromosomal to be equal to the A species.  `~/miniconda3/bin/chroder -o 05.chroder -F T A-B.coord A.fasta B.fasta (note: A is reference fasta)`. Then I got the `chroder.qry.fasta` and `chroder.ref.fasta`. The `chroder.ref.fasta `file is empty and I guess the `chroder.qry.fasta` is the B merged assemblies. Then I used the `initial A.fasta` and `chroder.qry.fasta` to run` nucmer `and `syri` to indetity SVs.  But when I compare the collinear between two species, I found before using chroder( A picture ) , Chr1 from A species assembly has a large invesion with Chr1 from B species assembly. But after running chroder(B picture) , the inversion disappear.
I guess the chroder software not only concatenate the two chromosomes into one chromosome,  maybe automatically deal with reverse complement ? Could you give me any suggestions?
looking forward with your reply!
Thanks very much!
![7](https://user-images.githubusercontent.com/109299053/194763381-2090e40c-0b75-4ece-860c-caf28d04fdd5.jpg)
![8](https://user-images.githubusercontent.com/109299053/194763399-1a82d4d2-08d9-441e-a6c0-7ec2ba9aab65.jpg)

**Comment by mnshgl0110** [comment]
Yes, chroder reverse complements the chromosomes that it thinks are from
different strands. So this output looks correct.

रवि, 9 अक्तू॰ 2022, 8:19 pm को aaannaw ***@***.***> ने लिखा:

**Comment by aaannaw** [comment]
Thanks for your prompt response!
I am still confused if we should accept the reverse complements by chroder. As you said  "SyRI expects that the homologous chromosomes being compared would be closely related i.e. largely syntenic. It performs an initial check to see if number of inversely aligned bases is more than directly aligned bases for a reference chromosome. If yes, then it warns to ensure same strandedness, but this warning does not mean that the chromosome must be reverse complemented as currently SyRI cannot identify that.", are chroder and fixchr  you recommend to me correctly identify whether the sequence is from  different strands or a real inversion?
Looking forward with your reply!

**Comment by mnshgl0110** [comment]
Sorry for the delayed response.
It is not trivial to predict whether super large inversions (>50% of chromosome length) are real inversions or because of different strands. So to be conservative, both chroder and fixchr reorient the chromosomes to get maximum directed alignments. Of course, if there is external evidence supporting such large inversions, then you can choose that strand. For running syri, as long as there is a syntenic path, it should work.
