### ISSUE TITLE
the parameter --reg can not show Translocation

### ISSUE THREAD

**Issue by aaannaw** [schneebergerlab/syri#167]
Hello
I wang to plot only a specific region. So my command is: `software/plotsr/bin/plotsr --sr 03.syri.out --genomes 04.genomes.txt --reg B:Chr1:150000000-191956155 -o 1.Chr1fission.output_plot.pdf`. But I can not get the Transloction around 160M on the Chr1. However the Transloction can be plotted when I use --chr Chr1 with the command：`software/plotsr/bin/plotsr --sr 03.syri.out --genomes 04.genomes.txt --chr Chr1 -o 1.Chr1fission.output_plot.pdf.`
Could you give me any suggestions?
Thanks very much!
![image](https://user-images.githubusercontent.com/109299053/199404088-9d1b47bf-d733-43c3-b1f1-c3ff00047590.png)
![image](https://user-images.githubusercontent.com/109299053/199404117-937ed58b-8975-4f4c-96b8-9ded9ef8434e.png)

**Comment by mnshgl0110** [comment]
Unrelated to syri. Closing.
