### ISSUE TITLE
The question with "Unequal number of chromosomes in the genomes" error

### ISSUE THREAD

**Issue by fengzt0629** [schneebergerlab/syri#168]
Hello syri developer:
I used SyRI for two-genome comparison. But when I run the SyRI, there is an error with it:

`syri -c HG00421_chroder_hg38.delta.coords -d HG00421_chroder_hg38.delta -r mainChr_hg38_UCSC.fa -q HG00421_chroder.fa.qry.fasta`

- Reading Coords - WARNING - Chromosomes IDs do not match.
- Reading Coords - ERROR - Unequal number of chromosomes in the genomes. Exiting

Then, I tried to delete the inconsistent chromosomes, leaving only the chromosomes shared by the two genomes,and sorted them, but it still made the same error.
After that, I add the --no-chrmatch  parameter to try to run syri again. At this time, the error is described as:

- Reading Coords - WARNING - Chromosomes IDs do not match.
- Reading Coords - WARNING - --no-chrmatch is set. Not matching chromosomes automatically.
- Reading Coords - WARNING - chr18,chr22.chrX,chr17,chr19,chrY,chr21,chr20 present in only one genome. Removing correponding alignments

But after checking, chr18,chr22.chrX,chr17,chr19,chrY,chr21,chr20, these chromosomes are truly contained in our two genomes.

Could you help me figure out it ?
Thanks,
Feng

**Comment by mnshgl0110** [comment]
Hi Feng,

If these chromosomes are indeed present and have homologous alignments then, this error should not happen.
Have you checked whether there are directed alignments between the homologous genomes? Maybe you can try https://github.com/schneebergerlab/fixchr to first find homologous chromosomes and also to check how the genomes are aligned (using the dotplot tool).
