### ISSUE TITLE
Issue of choice of aligner for whole genome alignment of two set of genomes

### ISSUE THREAD

**Issue by aamirwkhan06** [schneebergerlab/syri#169]
Hi Manish,

I have a few questions regarding getting the whole genome alignments of two set of plant genomes. My understanding is that nucmer is generally more sensitive while that is not the case with minimap2.
1. For SNPs and short InDels identification between two genomes does nucmer perform better than minimap?
2. For large insertions, deletions and inversions minimap2 is a better choice than nucmer?
3. nucmer --maxmatch generally takes forever to run with the parameters usually recommended for aligning two plant genomes and usually ends up with memory usage issues. What do you suggest is the closest possible solution in this case?
4. Is there a way that the query can be split up into smaller sequences and aligned in parallel to get this issue resolved? Can you suggest the best possible way to achieve this?

Looking forward to your suggestions.

Thanks!

Best regards,
Aamir

**Comment by mnshgl0110** [comment]
Hi Aamir,

1 & 2) In my experience, in the simpler genomic regions, both tools perform well. Differences occur in repetitive regions and sometimes in regions that are highly diverged. Unfortunately, it such regions it is difficult to assert whether a called SNP is correct or not.

Both tools should identify large inversions clearly. Minimap2 is more accepting to very large indels, but that can have lower sensitivity for translocations and duplications. 

I do not think that one tool would strictly be better than the other in terms of SNP calling, so the choice of alignment is generally based on other factors.

Also, in case you are interested in very large indels (10s Kbp), I would suggest that you try the `-r` parameter from minimap2 (similar option would be available for nucmer) and `-f` from syri. Also, in some cases (mostly in tandem duplicated regions), winnowmap generates better alignments, so you can try that out as well.

3 & 4) There is not much one can do to improve nucmer's performance. You can try decreasing alignment sensitivity to speed thing up. You can split the chromosomes, align homologous chromosomes, and then merge them. This pipeline would not call cross-chromosomal translocations though. Or you can use minimap2.

Best
Manish

**Comment by aamirwkhan06** [comment]
Thanks a lot, Manish, for these suggestions. Appreciate it.

Best regards,
Aamir
