### ISSUE TITLE
The difference between SYN and SYNAL

### ISSUE THREAD

**Issue by hui-liu** [schneebergerlab/syri#17]
Hi,

I have carefully read the manual (https://schneebergerlab.github.io/syri/fileformat.html) as well as your preprint paper (https://www.biorxiv.org/content/biorxiv/early/2019/08/20/546622.full.pdf). I still can not tell the difference between SYN and SYNAL. Could you give me more tips?
Thank you very much.

Best regards,
Hui Liu

**Comment by mnshgl0110** [comment]
Hi Hui Liu. SYNAL is for syntenic alignment. SYN is syntenic region. A syntenic region is defined as the set of consecutive un-interrupted syntenic alignments. That is, multiple syntenic alignments together constitute the syntenic region.
