### ISSUE TITLE
Cython package not detected

### ISSUE THREAD

**Issue by sghuete** [schneebergerlab/syri#171]
Hello,

I am trying to install SyRI and I am getting the following error:

```
python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython' 
```

However, if I check, Cython is properly installed in my system:

```
pip3 install Cython
Requirement already satisfied: Cython in /home/user/.local/lib/python3.8/site-packages (0.29.32)
```

It seems to me that SyRI does not detect Cython, how could I fix this?

Best regards

Samuel

**Comment by mnshgl0110** [comment]
Hi Samuel, this happens when there are inconsistencies in the local python environment and as such it would be very difficult for me to suggest what is causing this. You can try to open a python console and try to import cython in it using `import cython `, to check whether the python3 and pip3 you are using here corresponds to same environment.

Alternatively, it might be easier to install syri using conda.

**Comment by sghuete** [comment]
Thanks @mnshgl0110 !

I definitely will have a look at the Python inconsistencies. I tried before using conda to install Syri but I got the following error that I could not sort out myself as well:

```
conda create -n syri_env -c bioconda syri

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - syri -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31
```

If there is a way to bypass that error, I would be happy to try it.

Thank you for your time again,

Best regards

Samuel

**Comment by mnshgl0110** [comment]
This was solved recently https://github.com/schneebergerlab/syri/issues/164#issuecomment-1312671863
