### ISSUE TITLE
Erro in reading BAM file. reference_id -1 out of range

### ISSUE THREAD

**Issue by anandravi95** [schneebergerlab/syri#172]
Hi @mnshgl0110 , I am writing this issue related to #41.
Is there any workaround for it? How to work with mutilple assembly files if everytime one has to remove the unplaced contigs in query genome and reference genome.  
 
Thanks.

**Comment by mnshgl0110** [comment]
Answered here https://github.com/schneebergerlab/syri/issues/41#issuecomment-1329285616
