### ISSUE TITLE
Synteny differs between same set of assemblies

### ISSUE THREAD

**Issue by genmor** [schneebergerlab/syri#173]
Hi,

I'm assessing synteny between a reference genome (chromosome-level) and three assemblies. Using SyRi and plotsr, I was able generate some neat synteny plots, but I noticed something odd—using a different order of genomes leads to different outcomes. That is, if I have my reference and three assemblies (A, B, and C) and run SyRi + plotsr, the synteny of one order (ref + A; A + B; B + C) differs from a different one (ref + C; C + A; A + B). This might be confusing so I've attached both plots here. 

![Nmex03_synteny](https://user-images.githubusercontent.com/98834815/205375213-8c24751c-bb62-4c0e-b692-5cddd9f440bb.png)

![Nmex03_syteny2](https://user-images.githubusercontent.com/98834815/205375268-1c6fdded-2c8c-4521-8288-8845c0493f9b.png)

Is this expected behavior? I would appreciate any insight on this.

Just to add some detail in case it helps: the assemblies are of the same individual output from three different assemblers. The reads we are working with are HiFi. The assemblies have been purged and scaffolded and those scaffolds to chromosomes (using my reference genome).

**Comment by genmor** [comment]
Hi again.
I appreciate your quick response! I isolated Chr 2 for each of my assemblies and my reference, aligned each assembly to the reference using minimap -x asm5 to create paf files, and produced dotplots as you mentioned. 

![image](https://user-images.githubusercontent.com/98834815/206041970-4d61cf54-72f2-470f-904d-a2ea9441eac0.png)

There doesn't appear to be any inversions based on the dotplots. I also isolated what I think is the offending inverted region from the vcf file and it appears there are multiple <INVAL> annotations  always paired with <HDR> regions.

Can you provide some insight on how to proceed?

**Comment by mnshgl0110** [comment]
Based on these alignments, the hifiasm chromosome 2 should be syntenic as well. Can you please share the structural annotations by syri. You can get them using `grep -P '(SYN|INV|TRANS|INVTR|DUP|INVDP|NOTAL)\t' syri.out`

Also, try running syri with `-f` to disable automatic alignment filtering.

**Comment by genmor** [comment]
Hi Manish,

I appreciate you quick turnaround on addressing my issues, and I apologize for my delay in updating you about this.
As you suggested, I've used grep to pull the annotations. You can find them below: 
[check.txt](https://github.com/schneebergerlab/syri/files/10211118/check.txt)

I also re-ran SyRi on just my hifiasm assembly with the -f flag.
![ref-hifiasm_test](https://user-images.githubusercontent.com/98834815/207128321-dab7c443-42d4-4534-92fa-fae0f76398c8.png)

**Comment by mnshgl0110** [comment]
In the check.txt file, the 100-150MB region in Chr2 is mostly NOTAL. But the dotplot suggests that these regions are aligned. Is this file from the syri run using `-f`? Other than this filtering, I cannot think of any other reason for having these many large gaps.
