### ISSUE TITLE
Genome specific sequences

### ISSUE THREAD

**Issue by AS11-git** [schneebergerlab/syri#174]
Hi @mnshgl0110 ,
is NOTAL sequence are genome specific sequences ?
or any other criteria was there.

**Comment by mnshgl0110** [comment]
Check this: https://github.com/schneebergerlab/syri/issues/54

In addition to that, NOTALs can also be affected by filtering of low quality alignments by syri. You can toggle the `-f` parameter to disallow alignment filtering.

**Comment by AS11-git** [comment]
thank you for your response.
While calculating total genome specific sequences, should we consider only NOTAL sequences or any other category of the sequences?

**Comment by mnshgl0110** [comment]
Genome specific sequences should include NOTALs and INDELs. They can also include HDRs but that would depend on your downstream analysis.
