### ISSUE TITLE
Error when using .SAM file

### ISSUE THREAD

**Issue by JesseBNL** [schneebergerlab/syri#179]
Hi,

First of all: great tool to visualize the rearrangements! 

It works all perfectly fine as long as I use Mummer for the alignment, and the .coords and .delta files. However, when I try to use a .sam file (see below), it gives an error:

```
 from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

My .SAM file looks like this:
`@HD	VN:1.6	SO:unsorted
@SQ	SN:C6_H82_LILRA6-FCAR_annotated	LN:116808
@RG	ID:Unpaired_reads_assembled_against_C6_H82_LILRA6-FCAR_annotated	SM:Nucleotide alignment
@CO	samfixcigar. compilation:20230217104639 githash:367afc41f htsjdk:3.0.4 date:20230217115728. cmd:--reference ../../../H82.fasta ../../../H82vH7A.sam
H7-A_A46_consensus_LILRA6-FCAR_refined2	0	C6_H82_LILRA6-FCAR_annotated	1	255	2251I49=2X1=2X1=2X16=1I146=1X180=1I22=1X49=1I350=1I83=1I54=2I37=1I327=2D287=1X82=1I57=1X1=1I109=1D23=1X61=1D20=1X60=1X159=1I135=1X16=1X21=1D31=1D19=1I173=1X25=1I140=1X21=1X76=1D74=1X261=1X277=1X226=55D48=1D67=1X93=1X306=1X108=1X74=1X190=1X11=1X48=4I2=1X16=1X165=1I22=1X213=1X140=1X145=5I18=1X46=1X322=19I244=1X54=1X68=1X308=1X107=1X20=1X42=1X78=1D196=1D755=1X494=1D259=1X13=1I425=1D615=1D402=2I7=1X249=1X240=1X156=1X267=1X139=1X541=2D448=1X1795=2D2443=1I759=1D1694=1I907=1D3191=1D878=1D796=1D779=1D602=1D531=1D668=1D198=1D44=1X562=1D401=1X1316=1D796=2D3362=1D2263=1D1232=1I563=1I24=1I109=1D180=1X241=1X13=1D39=1X9=3I31=1X47=1X6=1X207=1X19=1X12=3I71=1X91=1X5=1X115=1X41=2X27=1D121=1X3=1X5=1X32=1X41=1X118=1X1=1X125=1X7=1X31=1X53=1X13=1X32=1D152=1X13=1X23=1D2=1X27=1D131=1X19=1X129=1I93=1X16=1D4=2X37=5D10=3D24=1X76=1X149=1X79=2I15=2I135=1X46=8I103=1D46=1I10=1X263=2X88=1X390=2X64=1X189=1D45=1X10=1X23=1D103=1D294=1X119=1X427=1X133=1D66=1X1=1X44=1X100=1X44=1X10=1X25=1X103=1X79=306I38=328I203=1X170=1X22=1X10=1X34=1X41=1X15=1X9=1X15=1X61=1D245=2X23=1I23=1X40=1X7=1X1=1X19=1D1=1X25=1X232=1X197=1X27=2D37=1X10=1X37=1X240=1X59=1X6=1X25=1X21=1X114=1X166=1X2I26=1X8=1X1=1X7=1X8=5I66=1X24=1D38=1X75=1X1153=1X254=1D768=1X1=1X299=7D199=2D52=1X470=1D116=1X218=1D206=1I68=1X125=1D130=1D119=1X2=1X5=1D40=1X36=1X44=2X180=1X35=1X144=1D42=1D145=1X2=1X135=6D48=1X160=1X2=1X12=1X13=1X286=2X7=1D280=6D113=1X170=1X10=1I21=3D212=1D211=1X48=1X61=1X17=1X41=1X7=1X23=1X85=1X67=1X35=3D9=1X114=1X16=1X69=1X163=1X26=1X108=1X45=4D27=1X55=1X101=1X5=1X7=1X16=1X9=1X3=1X11=1X58=1X175=1X43=1X1=2X3D2X55=1X9=1X19=1X6=1X50=1X49=1X19=1X3=1X17=1X23=1X52=1X1D12=1X8=1X62=1X19=1X52=1I14=1X8=9D1=1X20=1X24=1X3=2X34=1X38=1X2=1X30=1X9=2X21=1X29=1X17=1X13=1X24=1X3=1X48=1X1=1D2X4=1X7=1X2=1X39=1I43=1X9=1X44=1X21=1X2=1X2=1X10=1X21=1X45=1X45=2X2=1X1D1=1X2=1X10=1X25=1X17=1X12=1X30=1X1=1X7=1X42=8D30=1X1=1X97=1X20=1X156=1X29=1X216=1X24=1X947=1D2674=1I32=1I973=1D1245=1D717=1X454=1D331=1D195=1I135=1I912=1D941=1D703=1D397=1I275=1D797=1D633=19I19=19I13=38D228=1D932=3X1=3X1=9D2018=1X1079=1X1=1X2=6X1=1X193=1I1051=1D391=8I145=1I367=1X1495=1X3009=1I543=1D584=1X141=1X160=1I301=1D374=1X988=1I227=1I4142=1D513=1X395=1X147=1D266=1I409=1D891=1X428=1X464=1I1220=1D1235=5D644=1D2494=1D786=1I70=1D399=1X199=2X4=6X513=1D3381=1I258=1X8=1X8=1X19=1X2=12I28=1X17=1X153=1X27=1I284=1D117=1D1271=1D130=1D138=1D67=1D520=1X551=1X1620=3X32=1X4=44213I1X23=1X10=1X215=1X10=1X276=1I88=1X258=1X4D4=1X1=1X7=2X2D2=1X767=1D202=1I1089=1D1X147=1I40=2I86=21I420=4I797=1I539=1I551=1X94=2D985=1D1X182=1D71=1X260=1X2520=1X10=1D415=	*	0	0	GGGAGATTGTGCATCTGCTCACTGCAGCAATGCAGGCAAATATTCAACAGCAAACCTCGTGCGCAATTCCTTTCTGTCCTTTATTTTTTACGTCCACGTATCTATTGTTTCTCTTTCTGTTTCTGAAGATTTCAAAGCAATGCTGGCATTTATAATTTACACATTTAATTTGGTAGGTAGCGTTATGATGTAAAATGACTGTGCTCTGATTTTCTTTGGGATTAAATTAAATATGTGCATTCATGATGGAGAATAACTTCTTATTAATAATGTCTGTTTATCCAATACATTTAAAATTAAACTTTATACATTTATATCAGCAGGCTTTTGAAGTTATGTTCATAACAACTGTGGACATTGTGAATTTTAAGGATTGTTTTACTACTTGAATAATTTGAAAGGCTTTGATTCCTTTCTATCTTCTAAAATTAGTTAAGTATAGATGAGAAAGTTCTTGGTTTGAGTATGCTAATTTTAGTTCCCATTAACTTACCCCTGACACACTCCCTTTCAATCCTTTCCCAAATGATCTCTTCTGATTTATTGATAATAATTACATTAACCACAAGAAAATGGAGGACAAACTTGTTTCTAAATTTTATAATACTCTTCCCACTTCAAATTTGTATGTATGTGTTTATACATACCCCACACACCATTATCTATCTTATAATGTATACTATGTATTATATATTTATATATACCTACACACTATTATCTATCCTATAATATATATTATGTATTATATATTTATATATACCCACACACTATTATCTATCTTATTATGCACTGTGTATTATATATTTATGTATACACAATTATATATCTTATTATATATTTTGTATTATTTATGTATATACACCCACACAGTATTATATATCTTATAATATATATTATGCATTACATATATGCACACTATTATATATCTTATGTATTATTTATTATATATTTATATATTAACATATATGTTATACATAAATATATATATCAATATATTTATTATATATATCAATATATTTATATATAACATATAAATATATAAATATATTTATATACAATATATAAATACATAAAGTATATATATTTATATATTAATATATAATATATAAAATATATAAATATTTGATATATTATATTAAATAAATATATCATTAATATAATAAATATATTTATATATTAATAAATAAATAATATTTATATATTTATAAATATATAAATTAATAAATAAATATATATTTATTATTATATAAATATATTTGATATATTATATTAAATAAATATATGATATTTATATATTATATATTATATATAAATATATTACATATTTATATATGACATATATTAACACACTATTATATATTGTATTATATATTTAGAGATACACATACTATCATACATCTTATTATA  etc.`

What could go wrong?

**Comment by mnshgl0110** [comment]
This is caused by pysam not installed correctly. Please check the solutions mentioned here: https://github.com/schneebergerlab/plotsr/issues/39#issuecomment-1432782912

**Comment by JesseBNL** [comment]
Thank you, I got that fixed now.

Now I get the following:
ERROR: CIGAR string starting with non-matching base
SAM reader - ERROR - Error in reading SAM file: local variable 'qs' referenced before assignment

**Comment by mnshgl0110** [comment]
How did you generate the sam file?

**Comment by JesseBNL** [comment]
I used MAFFT aligner as it is the only way to get a proper alignment of this genome region. Then I had to convert the CIGAR string to replace the 'M' with 'X/='. So it is an unusual way but both Minimap2 and Mummer are not giving alignments.

I have a region with a variable number of highly similar genes, like the MHC region, and I want to see the rearrangements on the haplotypes. The SAM file generated with Minimap2 works, but it is a wrong representation of the rearrangements.

**Comment by JesseBNL** [comment]
As an overview:
<img width="1037" alt="Schermafbeelding 2023-02-17 om 15 21 25" src="https://user-images.githubusercontent.com/42739379/219680527-8929ec37-cc5c-4a08-a61f-4b8eb514ee79.png">

KIR3DL01 is present on the reference sequence once, and on the other haplotype twice. I would like Syri/plotsr to show that KIR3DL01 is duplicated, and that 3DS02 and 3DS06 represent an insertion.

**Comment by mnshgl0110** [comment]
In the sam file, the issue is caused by the `2251I` at the beginning of the CIGAR. As generally, the CIGAR strings ends are either clipped (S/H) or a match (=), but in this case the CIGAR beginning corresponds to a 2251 bp insertion which does not make sense for an alignment. If you can fix this then the SAM should work.

In the specific biological case, I would imagine that the default minimap2 parameters might result in an indel for the gene of interest instead of a duplication. You can try with a smaller value for  `-r` ( r < your gene size).

**Comment by JesseBNL** [comment]
Thank you for the fast solutions. Also this solved the problem, but raising another directly:
ValueError: Length mismatch: Expected axis has 0 elements, new values have 7 elements

I think my work around to use a MAFFT alignment is a but too farfetched and I will try to tune the Minimap2 and Mummer parameters a bit more. With Mummer I was able to generate the image below. However, as you can see, it says there is a duplication at the region that shows 91% similarity, but neglecting the duplicated 3DL01 gene with 98% similarity.

![IMG_2260](https://user-images.githubusercontent.com/42739379/219686178-95dc1cc3-d390-477a-9b3e-08694360a534.jpg)

**Comment by mnshgl0110** [comment]
You can decrease the value for `-s` for plotsr. If the duplication still does not show, then check the syri output to confirm that the duplication is indeed identified. If it is not identified by syri, then indeed you would need to increase the sensitivity of alignments.

**Comment by JesseBNL** [comment]
Now I try to use Minimap2 again for the alignments, but I get the following error when using Syri:

`../syri -c out.sam -r H82.fasta -q H7A.fasta -F S
Traceback (most recent call last):
  File "../syri", line 6, in <module>
    main(sys.argv[1:])
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/syri/scripts/syri.py", line 326, in main
    syri(args)
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/syri/scripts/syri.py", line 214, in syri
    startSyri(args, coords[["aStart", "aEnd", "bStart", "bEnd", "aLen", "bLen", "iden", "aDir", "bDir", "aChr", "bChr"]])
  File "syri/pyxFiles/synsearchFunctions.pyx", line 516, in syri.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 911, in syri.synsearchFunctions.outSyn
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/pandas/core/generic.py", line 5915, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/pandas/core/generic.py", line 823, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 230, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 7 elements`

While I used this to generate the alignment:
`minimap2 -ax asm5 --eqx H82.fasta H7A.fasta > out.sam`

**Comment by JesseBNL** [comment]
Also with minimap2 .sam files it gives this error now:

`../syri -c out.sam -r H82.fasta -q H7A.fasta -F S
Traceback (most recent call last):
  File "../syri", line 6, in <module>
    main(sys.argv[1:])
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/syri/scripts/syri.py", line 326, in main
    syri(args)
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/syri/scripts/syri.py", line 214, in syri
    startSyri(args, coords[["aStart", "aEnd", "bStart", "bEnd", "aLen", "bLen", "iden", "aDir", "bDir", "aChr", "bChr"]])
  File "syri/pyxFiles/synsearchFunctions.pyx", line 516, in syri.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 911, in syri.synsearchFunctions.outSyn
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/pandas/core/generic.py", line 5915, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/pandas/core/generic.py", line 823, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 230, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 7 elements`

I have looked into the other support issues here and tried chrfix, but this tool was unavailable. Any idea what might be the problem?

**Comment by JesseBNL** [comment]
To add on this, the DEBUG log file gives:

`2023-02-21 07:30:41,485 - Reading Coords - DEBUG - syri:135 - S
2023-02-21 07:30:41,485 - Reading Coords - INFO - syri:135 - Reading input from SAM file
2023-02-21 07:30:41,505 - Reading Coords - INFO - syri:135 - No Inverted alignments present.
2023-02-21 07:30:41,507 - syri - INFO - syri:214 - starting
2023-02-21 07:30:41,507 - syri - DEBUG - syri:214 - memory usage: 0.10258865356445312
2023-02-21 07:30:41,507 - syri - INFO - syri:214 - Analysing chromosomes: []
2023-02-21 07:30:41,516 - getCTX - INFO - syri:214 - Identifying cross-chromosomal translocation and duplication for chromosome2023-02-21 07:30:41.516341
2023-02-21 07:30:41,516 - getCTX - DEBUG - syri:214 - Reading Coords2023-02-21 07:30:41.516447
2023-02-21 07:30:41,532 - getCTX - DEBUG - syri:214 - CTX identification: ctxdata size(0, 13)
2023-02-21 07:30:41,532 - getCTX - DEBUG - syri:214 - Making Tree
2023-02-21 07:30:41,561 - getCTX - DEBUG - syri:214 - finding Blocks
2023-02-21 07:30:41,561 - getCTX - DEBUG - syri:214 - Preparing for cluster analysis
2023-02-21 07:30:41,564 - getCTX - DEBUG - syri:214 - Getting clusters
2023-02-21 07:30:41,564 - getCTX - DEBUG - syri:214 - Finding ME Blocks
2023-02-21 07:30:41,564 - getCTX - DEBUG - syri:214 - Finding best subset of clusters`

**Comment by mnshgl0110** [comment]
I suspect that this is happening because of old files from an earlier syri run. Could you please try in a new directory, or removing old syri output files, or by using some unique `--prefix` for the syri run.

**Comment by JesseBNL** [comment]
I have tried the run in a new folder, making a new alignment using minimap2 (minimap2 -ax asm5 --eqx H82.fasta H7A.fasta > out_new.sam), but the error is still the same:

Traceback (most recent call last):
  File "../syri", line 6, in <module>
    main(sys.argv[1:])
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/syri/scripts/syri.py", line 326, in main
    syri(args)
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/syri/scripts/syri.py", line 214, in syri
    startSyri(args, coords[["aStart", "aEnd", "bStart", "bEnd", "aLen", "bLen", "iden", "aDir", "bDir", "aChr", "bChr"]])
  File "syri/pyxFiles/synsearchFunctions.pyx", line 516, in syri.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 911, in syri.synsearchFunctions.outSyn
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/pandas/core/generic.py", line 5915, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/pandas/core/generic.py", line 823, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 230, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 7 elements

And this is the .sam header:
`@SQ	SN:KIR_region	LN:116808
@PG	ID:minimap2	PN:minimap2	VN:2.24-r1122	CL:minimap2 -ax asm5 --eqx H82.fasta H7A.fasta
KIR_region	0	KIR_region	1	60	2251S48=1I8=1D16=1I146=1X180=1I22=1X49=1I350=1I83=1I4=2X48=2I37=1I327=2D2X224=1X60=1X82=1I43=1X13=1X1=1I105=1X3=1D20=1X2=1X61=1D20=1X60=1X11=1X147=1I135=1X16=1X21=1D2=3X26=1D19=1I98=1X74=1X25=1I140=1X21=1X76=1D74=1X261=1X277=1X226=55D48=1D2X65=1X25=1X67=1X306=1X108=1X74=1X190=1X11=1X48=4I2=1X16=1X165=1I22=1X67=1X145=1X140=1X145=5I18=1X46=1X322=19I244=1X54=1X68=1X307=2X107=1X20=1X42=1X78=1D196=1D755=1X494=1D259=1X13=1I425=1D615=1D402=2I7=1X249=1X240=1X156=1X267=1X139=1X541=2D448=1X1795=2D5X413=1X548=1X1475=1I142=1X616=1D399=1X532=1X337=1X307=1X4=1X110=1I907=1D3191=1D878=1D796=1D175=1X603=1D602=1D531=1D668=1D198=1D44=1X562=1D11=1X389=1X434=1X881=1D796=2D3362=1D883=1X60=1X902=1X415=1D1232=1I563=1I24=1I109=1D180=1X241=1X13=1D39=1X9=3I31=1X47=1X6=1X207=1X14=1X4=1X12=3I26=1X44=1X91=1X5=1X115=1X41=2X27=1D121=1X3=1X5=1X32=1X41=1X118=1X1=1X125=1X7=1X31=1X53=1X13=1X32=1D152=1X13=1X23=1D2=1X27=1D131=1X19=1X129=1I93=1X16=1D4=2X37=5D10=3D24=1X76=1X149=1X79=2I15=2I135=1X8=8I141=1D46=1I10=1X263=2X88=1X390=2X64=1X189=1D45=1X10=1X23=1D25=1X77=1D294=1X119=1X427=1X133=1D66=1X1=1X44=1X100=1X44=1X10=1X25=1X103=1X79=306I28=1X9=328I203=1X170=1X22=1X10=1X34=1X41=1X15=1X9=1X15=1X61=1D245=2X23=1I23=1X40=1X7=1X1=1X19=1D1=1X25=1X232=1X197=1X27=2D37=1X10=1X37=1X240=1X59=1X6=1X25=1X21=1X114=1X17=1X148=2I1X26=1X8=1X1=1X7=1X8=5I66=1X24=1D38=1X75=1X880=1X272=1X254=1D768=1X1=1X1=1X297=7D59=1X139=2D52=1X67=1X327=1X3=1X70=1D116=1X218=1D205=1I30=1X1=1X36=1X35=1X55=1X33=1D10=1X76=1X1=1X40=1D18=1X100=1X2=1X5=1D40=1X36=1X44=3X112=1X31=1X34=1X35=1X144=1D15=2X25=1D1X144=1X2=1X135=6D48=1X34=1X125=1X2=1X12=1X13=1X286=2X7=1D35=1X244=6D113=1X170=1X10=1I21=3D212=1D92=2X117=1X48=1X61=1X17=1X41=1X7=1X23=1X67=1X17=1X67=1X35=3D1X8=1X40=2X13=1X58=1X16=1X59=1X9=1X121=1X41=1X26=1X108=1X45=4D27=1X55=1X101=1X5=1X7=1X16=1X9=1X3=1X11=1X58=1X175=1X43=5I1=8D55=1X9=1X19=1X6=1X50=1X49=1X19=1X3=1X17=1X23=1X37=1D15=1X12=1X8=1X62=1X19=1X52=1I14=1X8=9D1=1X20=1X24=1X3=2X34=1X38=1X2=1X30=1X9=2X21=1X29=1X17=1X13=1X24=1X3=1X48=1X1=1D2X4=1X7=1X2=1X39=1I43=1X9=1X44=1X21=1X2=1X2=1X10=1X21=1X45=1X45=1D1X3=1X1=1X2=1X10=1X25=1X17=1X12=1X30=1X1=1X7=1X42=8D30=1X1=1X97=1X20=1X156=1X29=1X216=1X24=1X947=1D431=1X376=1X547=1X4=1X1312=1I32=1I789=1X183=1D411=1X5=1X827=1D402=1X314=1X182=1X11=1X259=1D247=1X83=1D77=1X117=1I135=1I123=1X733=1X54=1D941=1D76=1X212=1X95=1X317=1D154=1X242=1I275=1D281=1X230=1X14=1X23=1X245=1D931=1D931=6D1=2X6=3D307=1X1092=1X617=1X1076=1I13=1D1=1X193=1I447=1X152=1X192=1X229=1X27=1D367=8I32=1X136=1I27=1X126=1X12=1X122=2X75=1X711=1X579=1X203=1X1228=1X112=1X1667=1I543=1D495=1X88=1X141=1X160=1I301=1D138=1X235=1X593=1X50=1X343=1I227=1I1094=1X1696=1X618=1X731=1D513=1X395=1X147=1D82=1X183=1I409=1D891=1X354=2X72=1X464=1I678=1X541=1D466=1X183=1X584=5D644=1D1346=1X1147=1D786=1I70=1D399=1X199=2X4=6X513=1D1306=1X429=1X899=1X744=1I258=1X8=1X8=1X19=1X2=12I28=1X17=1X153=1X27=1I284=1D117=1D176=1X31=1X1=1X1060=1D130=1D138=1D67=1D163=1X356=1X331=1X11=1X207=1X1620=3X32=1X4=1D22=2X11=44214I215=1X10=1X276=1I88=1X223=2X31=4D2=3X2=1X1=1X6=2D4X1=1X767=1D202=1I1089=1D1X147=1I26=2I100=21I420=4I797=1I323=1X215=1I551=1X94=2D985=1D1X182=1D71=1X260=1X2520=1X10=1D415=	*	0	0	GGGAGATTGT`

**Comment by mnshgl0110** [comment]
It seems that there are errors in this SAM. As syri is not able to find alignments corresponding to any chromosome. So the line below (from your example):
```2023-02-21 07:30:41,507 - syri - INFO - syri:214 - Analysing chromosomes: []```
should be something like:
``` 2023-02-15 17:19:03,076 - syri - INFO - syri:214 - Analysing chromosomes: ['chr4']```
Try converting it to bam. You can also try the PAF output from minimap2. Also, in the SAM header that you pasted above, the alignment seems to be starting in the header line @SQ. I think, that is incorrect.

**Comment by JesseBNL** [comment]
I have tried PAF output but it gets an error as well when trying Syri:
Traceback (most recent call last):
  File "syri/pyxFiles/synsearchFunctions.pyx", line 293, in syri.synsearchFunctions.readCoords
  File "syri/pyxFiles/synsearchFunctions.pyx", line 221, in syri.synsearchFunctions.readPAF
  File "syri/pyxFiles/synsearchFunctions.pyx", line 224, in syri.synsearchFunctions.readPAF
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../syri", line 6, in <module>
    main(sys.argv[1:])
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/syri/scripts/syri.py", line 326, in main
    syri(args)
  File "/home/jesse/miniconda/envs/syri_env/lib/python3.8/site-packages/syri/scripts/syri.py", line 135, in syri
    coords, chrlink = readCoords(args.infile.name, args.chrmatch, args.dir, args.prefix, args, args.cigar)
  File "syri/pyxFiles/synsearchFunctions.pyx", line 295, in syri.synsearchFunctions.readCoords
TypeError: can only concatenate str (not "IndexError") to str

I don't know what I am doing wrong.. Can I send you the 2 fasta files and that you try to make a .sam file and see if it works? I use H82.fasta (now txt to send it) as reference.

[H82.txt](https://github.com/schneebergerlab/syri/files/10792353/H82.txt)
[H7A.txt](https://github.com/schneebergerlab/syri/files/10792354/H7A.txt)

**Comment by mnshgl0110** [comment]
Hi @JesseBNL. Thanks for sharing the files. Syri filters out small low quality alignments. As it turns out, in this case, there is only alignment and that too was getting filtered out while reading the alignments resulting all the weird errors. I ran syri with the `-f` parameter to not filter alignments and that it worked as expected.

**Comment by JesseBNL** [comment]
Yes!! That did the job. Thank you for the very quick support.

**Comment by JesseBNL** [comment]
Well, here I am again. It generates the plot perfectly fine now:
![plot1](https://user-images.githubusercontent.com/42739379/220372207-d24b6c5d-ef53-4a1a-931e-4e093cdf878b.png)

However, there should be a 44 kb insertion, which is listed in the syri.out file, but is not showing. Has this also to do with the very small alignment I am running? What parameters do I have to adjust to make this insertion show? Also, as explained earlier in this topic I expect a duplication, which is also not showing.
[syri.out.txt](https://github.com/schneebergerlab/syri/files/10794445/syri.out.txt)

Sorry to bother you again.

**Comment by mnshgl0110** [comment]
Please open new issue in plotsr repository for questions related to that.
Nevertheless, plotsr plots syntenic and SR (inversions, translocations, and duplications) regions. If you want to visualise indels (or other smaller local variations), then you can pass the coordinate of indels of interest in the marker file.
