### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by pvanheus** [schneebergerlab/syri#18]
Firstly, I presume this is the SyRI mentioned in [this paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1911-0). Secondly, can you please tag a release? That would make it easier to package the software for projects like [bioconda](https://bioconda.github.io/index.html).

Thank you.

**Comment by mnshgl0110** [comment]
Hi. Thanks for the suggestion. That is indeed on the checklist. But, I am still working in improving the performance of some functions and I am not sure how that could be done in conjunction with the packaging. Though, I must admit, my knowledge is limited regarding this, so I am open to suggestions if there some standard practices to follow to combine development with releases. Thanks.

**Comment by tseemann** [comment]
Making a release at https://github.com/schneebergerlab/syri/releases
will not affect any work you do.
It will just enable a proper versioned snapshot to be used by people.
This is important given you have published it in a high impact journal.

**Comment by mnshgl0110** [comment]
Thanks for the input. I have added it.
