### ISSUE TITLE
Incorrect CIGAR string found.

### ISSUE THREAD

**Issue by ylevmirom** [schneebergerlab/syri#180]
Hi, 
I'm trying to use syri to look for structural variations between two genomes. 
for alignment I'm using minimap2 (tried -ax and -cx options), and when running syri I get this error: 
`Reading BAM/SAM file - ERROR - Incorrect CIGAR string found. CIGAR string can only have I/D/H/S/X/=. CIGAR STRING: 1424M25D75M`

i tried to run minimap again but still same error, 
pls help

Thanks, 

Yael

**Comment by JesseBNL** [comment]
Hi Yael,

You have to use the `--eqx` command in your minimap2 line to replace the M for X/= in your CIGAR string.

**Comment by ylevmirom** [comment]
Thanks!

**Comment by marade** [comment]
It's worth pointing out that not all SAM files come from minimap2, and 'M' is correct CIGAR under the SAM specification:

https://samtools.github.io/hts-specs/SAMv1.pdf

Therefore in my opinion this a bug that isn't fixed.

**Comment by mnshgl0110** [comment]
Syri uses CIGAR string to call SNPs and short indels. In CIGAR, `M` is used for both matches and mismatches, which means that using it for calling SNPs would require checking the bases in both genomes at all positions that have an `M`. This could result in significant computational overhead. Using `=/X` solves this issue as only positions with `X` needs to fetched.

I am also not aware of other popular whole-genome alignment methods that do not produce SAM files with `=X`.
