### ISSUE TITLE
unequal chromosomes

### ISSUE THREAD

**Issue by bijendrabio** [schneebergerlab/syri#181]
Hello,
Curious, if there's a way to deal with two genomes containing unequal number of chromosomes. kindly suggest!

Regards,
B

**Comment by emmannaemeka** [comment]
Hello, Thanks for this tool. I would want to use chroder to create pseudo chromosomes for my genome. I ran this command

chroder -o a9_scaffold ref.fasta  a9_spades.fasta -F B a9.bam        
it returned this error Error in opening BAM/SAM file. file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False

I then changed to 
chroder -o a9_scaffold ref.fasta  a9_spades.fasta

It returned this error

chroder: error: the following arguments are required: qry

Please what am i not getting right?

**Comment by mnshgl0110** [comment]
Answered here: https://github.com/schneebergerlab/syri/issues/185
