### ISSUE TITLE
Why snp file produced by syri is empty and followed by error

### ISSUE THREAD

**Issue by InfiniteLaugh** [schneebergerlab/syri#190]
Hello,
I tried to run syri to obtain SV, SNP, Indel, etc., All SV files seem normal, but the program dropped out at the SNP step, leading to an empty file. The input file alignment coordinates file was obtained from mummer4, using the code as follows:
```
nucmer --prefix qry ref.fa qry.fa -t 10 -l 50 -c 100 --maxmatch
delta-filter -i 90 -l 100 -m qry.delta  > qry.i90_l100_m.filter.delta
show-coords -THrd qry.i90_l100_m.filter.delta > qry.i90_l100_m.filter.THrd.coords
```
But error occurs at the step of SNP, I am wondering if I should replace parameter `-m` with `-1`, is this the reason for this issue?
![Snipaste_2023-04-18_00-53-24](https://user-images.githubusercontent.com/62791785/232558094-3bce0566-6efe-402d-b1f9-00554478c7e8.jpg)

**Comment by mnshgl0110** [comment]
The error implies that show-snps (from mummer) could not be run correctly. Please check that show-snps is in the bash working environment. Alternatively, try using the `-s` parameter of syri to parse the path to show-snps.
