### ISSUE TITLE
Unexpected character `-' in string Chr10

### ISSUE THREAD

**Issue by ZhaoHang-bio** [schneebergerlab/syri#191]
Hi,

I'm running syri with the delta file of two species using nucmer. The following is my command line:

            nucmer -l 200 ref.Chr.fasta query.Chr.fasta -p out -t 20
            delta-filter -m -i 90 -l 100  out.delta > m_i90_l100.delta
            show-coords -THrd m_i90_l100.delta > m_i90_l100.coords
            syri -c m_i90_l100.coords -d m_i90_l100.delta -r ref.Chr.fasta -q query.Chr.fasta

and I'm getting this error:

ShV - ERROR - Error in finding SNPs using show-snps: Unexpected character \`-' in string Chr10
Unexpected character \`-' in string Chr10
Unexpected character \`-' in string Chr17
Unexpected character \`-' in string Chr17

Any way to resolve this issue?

Thanks.

**Comment by mnshgl0110** [comment]
The error is resulting from show-snps of mummer. Can you try running `show-snps -HrT m_i90_l100.delta` to see if it works. Also, try using the `-s` parameter of syri to parse the path of `show-snps`.

**Comment by ZhaoHang-bio** [comment]
Thank you for your reply. I have run this command line and get the same error. But the difference is that shoow-snp2 has a normal output. It seems to be problem with the software, but I don't find any problem with the two of input genome data. I don't know how to solve it.

![image](https://user-images.githubusercontent.com/58715839/233235174-392a1a71-4162-4479-ba96-b45d548ad96f.png)



![image](https://user-images.githubusercontent.com/58715839/233235116-fe16b10a-86ef-4a17-a947-452106e0b6f4.png)

**Comment by mnshgl0110** [comment]
What is show-snp2?

**Comment by ZhaoHang-bio** [comment]
Sorry, this is a typo. It should be show-snps

**Comment by mnshgl0110** [comment]
Ok. Can you please share what commands have you tried?

**Comment by ZhaoHang-bio** [comment]
Sure! Thank you for your help.
The following is my command lines:
            nucmer -l 50 ./ref.Chr.fasta ./quary.Chr.fasta -p out -t 16
            delta-filter -m -i 90 -l 100 out.delta > out_m_i90_l100.delta
            show-coords -THrd out_m_i90_l100.delta > out_m_i90_l100.coords
            syri -c out_m_i90_l100.coords -d out_m_i90_l100.delta -r ./ref.Chr.fasta -q ./quary.Chr.fasta -s ~/software/bin/show-snps --nc 16 --nosnp
            plotsr syri.out ./ref.Chr.fasta ./quary.Chr.fasta -H 8 -W 5

and the error is :

![image](https://user-images.githubusercontent.com/58715839/233313296-0697354d-042b-4f5c-a292-5d5c0ec00b0c.png)

**Comment by mnshgl0110** [comment]
And you checked this command `~/software/bin/show-snps -HrT m_i90_l100.delta` and it worked?

**Comment by ZhaoHang-bio** [comment]
I ran this command ~/software/bin/show-snps -HrT m_i90_l100.delta and got the same error:

![image](https://user-images.githubusercontent.com/58715839/233317600-78fb49f2-dc70-45cf-bb15-3fd660086bca.png)

This error seems to point to my input .delta file. But I didn't find anything in the input file. 

[out_m_i90_l100.zip](https://github.com/schneebergerlab/syri/files/11284446/out_m_i90_l100.zip)

**Comment by mnshgl0110** [comment]
And what command did you run to get the correct output?

In any case, this is an issue with mummer (as the error is not caused by syri) and it would be best to get help from the developers of Mummer.

**Comment by ZhaoHang-bio** [comment]
OK I'll resolve this error somewhere else. This is indeed the mummer's part.
