### ISSUE TITLE
Another python version issue--syri thinks I'm using an older version than is actually running

### ISSUE THREAD

**Issue by DaRinker** [schneebergerlab/syri#193]
Installed syri in a conda environment (as described here https://github.com/schneebergerlab/syri/issues/134#issuecomment-1109202440). Everything seemed to proceed without a problem.

However I cannot run syri due to the following error:

```
Running SyRI - ERROR - 
SyRI uses Python >=3.8. Currently using Python3.6. Exiting

$ python --version
Python 3.9.12

```

Why might syri think I'm using 3.6?

**Comment by mnshgl0110** [comment]
Probably because python3.6 is installed somewhere in the environment and shell is using that to run syri. The following should work:
```
$ which python3.9
/PATH/TO/PYTHON3.9

$ which syri
/PATH/TO/SYRI

$  /PATH/TO/PYTHON3.9 /PATH/TO/SYRI <syri_arguments>
```

On a side note, check whether `/usr/bin/env python3 --version` results in 3.6 or 3.9. This is the python version that syri (when ran as an executable) would use.

**Comment by DaRinker** [comment]
Thank you. While this particular fix didn't work, it _did_ clue me in to where I should look. Turns out the problem was in the conda environment itself when I installed syri.  Even though my default python is 3.9, conda defaults to python 3.6 for new environments, So I  just needed to be explicit about specifying the python version when building the environment.
