### ISSUE TITLE
getTSV - ERROR - Error in finding parent for SNP getTSV - ERROR - #      566892  2624868 1       2058353 chr01   chr1    Series([], )

### ISSUE THREAD

**Issue by karrysorry** [schneebergerlab/syri#194]

**Comment by karrysorry** [comment]
Hello，Manish Goel.
I'm running syri with the delta file of two species using nucmer. The following is my command line:
         nucmer  --prefix=name    ref.Chr.fasta    query.Chr.fasta   -p out -t 20
        delta-filter -1 -l 100  out.delta > m_i90_l100.delta
        show-coords -THrd yy92.delta.filiter > [yy92.delta.filiter.coords
       python3  syri    -c yy92.delta.filiter.coords -d yy92.delta.filiter -r ref.Chr.fasta -q query.Chr.fasta  -k --prefix=name  -s show-snps  --lf name.log

and I'm getting this error:
getTSV - ERROR - Error in finding parent for SNP
getTSV - ERROR - #      566892  2624868 1       2058353 chr01   chr1    Series([], )

Any way to resolve this issue?

Thanks.

sincerely 
Karrysorry

**Comment by mnshgl0110** [comment]
Can you try running syri in a new directory containing only the .fasta, .delta, and .coords file? If that does not work, please run syri with the log level set to debug and then share the syri.log file.

**Comment by karrysorry** [comment]
Okay, thanks, I ran Nucmer again before and the results are not yet in. After the results come out, I will try your method. Again, express my sincere gratitude.

sincerely
Karrysorry

**Comment by karrysorry** [comment]
I followed your method and the result has already run out, thank you


sincerely
Karrysorry

**Comment by karrysorry** [comment]
However, a new error has occurred。
Running SyRI - ERROR - <module>:202 - Length of reference sequence of chr10 is less than the maximum coordin
ate of its aligned regions. Exiting.
