### ISSUE TITLE
ERROR - Incorrect CIGAR string found

### ISSUE THREAD

**Issue by Jokendo-collab** [schneebergerlab/syri#196]
I am getting the following error even though I followed the minimap2 aligmnent and sorted my bam file. How can I go around this?
```bash
syri -c macOpe2.sorted.bam -r Betta_splendens.fa -q macOpe2.fasta -F B --prefix Betta_macOpe2 --dir syri/
Reading BAM/SAM file - ERROR - Incorrect CIGAR string found. CIGAR string can only have I/D/H/S/X/=. CIGAR STRING: 6879966H441M13805544H
```

**Comment by marade** [comment]
Same error here. Note that error continues to happen even if you 'fix' your SAM file with something like this:

awk '{gsub("M","=",$6)}1'

Of course 'M' is perfectly valid CIGAR in the SAM specification, so this error shouldn't happen.

**Comment by mnshgl0110** [comment]
Duplicated https://github.com/schneebergerlab/syri/issues/180

**Comment by asan-emirsaleh** [comment]
> error continues to happen

@marade try to replace delimiter to "\t"
`-F $'\t'` did not worked but `'BEGIN { FS=OFS="\t" } <expression>`  did the job.

**Comment by mnshgl0110** [comment]
@asan-emirsaleh this will probably result in incorrect output. Recommended strategy is to run minimap2 with the `--eqx` option.
