### ISSUE TITLE
syri issues

### ISSUE THREAD

**Issue by MaOrsucci** [schneebergerlab/syri#200]
Hi Syri user,
I'm trying to used Syri between 2 pacBio genomes of fungi. There is a huge amount of rearrangement between these two genomes.
I'd like to be able to visualize them with Syri, but when I run syri I get warnings and this error:

Reading BAM/SAM file - WARNING - No primary alignment found for reference sequence JAETXR010000012.1. This could mean that the entire chromosome JAETXR010000012.1 is reapeated.
Reading BAM/SAM file - WARNING - No primary alignment found for reference sequence JAETXR010000014.1. This could mean that the entire chromosome JAETXR010000014.1 is reapeated.
Reading BAM/SAM file - WARNING - No primary alignment found for reference sequence JAETXR010000015.1. This could mean that the entire chromosome JAETXR010000015.1 is reapeated.
Reading BAM/SAM file - WARNING - No primary alignment found for reference sequence JAETXR010000008.1. This could mean that the entire chromosome JAETXR010000008.1 is reapeated.
Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - WARNING - Matching them automatically. For each reference genome, most similar query genome will be selected. Check mapids.txt for mapping used.
Reading Coords - ERROR - JAETXS010000003.1 in genome B is best match for two chromosomes in genome A. Cannot assign chromosomes automatically.

Someone can help me with this issue?
Thanks.

**Comment by mnshgl0110** [comment]
Unfortunately, plots are not visible when replying through email.

**Comment by mnshgl0110** [comment]
@MaOrsucci On the face of it, these genomes are too diverged and violates the assumptions made by syri, and hence can't be analysed by syri directly.

In fact, it is the first time I have seen such genomes and find them super weird and have quite some questions. I would like to know more about this system. Would you have time for a zoom chat? Maybe, we can come up with some ideas about what to do with this!

**Comment by MaOrsucci** [comment]
Hi,

So if you are always interested we can plan to zoom.
I will explain you more about these genomes.

Best regards,

From: Manish Goel ***@***.***>
Reply to: schneebergerlab/syri ***@***.***>
Date: Wednesday, 14 June 2023 at 10:34
To: schneebergerlab/syri ***@***.***>
Cc: Marion Orsucci ***@***.***>, Mention ***@***.***>
Subject: Re: [schneebergerlab/syri] syri issues (Issue #200)


@MaOrsucci<https://github.com/MaOrsucci> On the face of it, these genomes are too diverged and violates the assumptions made by syri, and hence can't be analysed by syri directly.

In fact, it is the first time I have seen such genomes and find them super weird and have quite some questions. I would like to know more about this system. Would you have time for a zoom chat? Maybe, we can come up with some ideas about what to do with this!
