### ISSUE TITLE
Syri not detecting inversions from dgenies

### ISSUE THREAD

**Issue by Harper75** [schneebergerlab/syri#201]
Hello,

Thank you for this great tool. I have been using syri to find inversions in sex chromosomes between different species of insects and so far syri has been of great help. However I have been having trouble with one of my species where  inversions prevously detected in dgenies will not appear in syri. I read about minimap issues and try to use version 2.17 and again, inversions are not detected. What do you think it can be happening ? I am joining you the plot made by dgenies and the plot made with plotsr after getting results with syri.

Thanks a lot!

![inversions_h_vs_r](https://github.com/schneebergerlab/syri/assets/96175710/d3d9cc07-90d6-4c3c-b43b-7942bbfa57fe)
<img width="589" alt="map_rh_to_he" src="https://github.com/schneebergerlab/syri/assets/96175710/1aac54b0-3404-43a6-aee5-8ddacef50884">

**Comment by mnshgl0110** [comment]
Hi @Harper75. Thanks for sharing the plots. These plots are very inconsistent and my first "gut feeling" is that these are not even from the same data. For example: the 3' end of rh should be syntenic to hec, however, the plotsr plot shows large gap.
Could you please check the syri.out file and describe what is the annotation for the 3' end of rh? And what is happening in the missing inverted regions.
Also, please regenerate and share dotplot using the executable provided with [fixchr](https://github.com/schneebergerlab/fixchr). For generating the dotplot, use the same alignment file that you use for running syri. I have not used dgenies but I have experienced dotplot visualisers that pre-process alignments for better visualisation, but sometimes the output becomes mis-leading.
What are the minimap2, syri, plotsr commands that you used?

**Comment by Harper75** [comment]
Thanks for you quick answer!

I should have explained myself better. My genomes do not have the same number/names of contigs, so I always start by doing whole genome comparaisons via dgenies to identify the sex chromosome in each genome. I then manually produce a fasta file from the sex chromosome and this is what I use for syri. 

The dgenies plot I shared is the zoomed section corresponding to the sex chromosomes. What I am realising with the plot produced by plotrs is that the contig that is suppose to be the sex chromosome is much shorter in rhe than in hec, so I think I did not get the section of the genome containing the inversion. 

I tried to use fixchr and I got the following error: Reading Coords - ERROR - Error in reading the alignment filelist index out of range. I tried to RC one of the sequences and the error persists.

My commands:

minimap2:

minimap2 -ax asm5 --eqx $pri_asm/hec.fa $pri_asm/rh.fa > hec_rh.sam 

syri:

syri -c hec_rh.sam  -r $pri_asm/hec.fa -q $pri_asm/rh.fa  -F S --prefix hec_rh_

plotsr:

plotsr \
    --sr hec_rh_syri.out \
    --genomes genomes.txt  \
    -o inversions_hec_rh.png


I am also including the output produced by syri.


[hec_rh_syri.out.zip](https://github.com/schneebergerlab/syri/files/11982602/hec_rh_syri.out.zip)

Thank you very much for your help!

**Comment by mnshgl0110** [comment]
The syri.out file has large not aligned regions (`NOTAL`), so the output of plotsr is consistent with that. You can try running syri with the `-f` parameter. If you still get such large NOTALs, that you think should not  be there, then these are probable assembly errors and you would need to fix those.

**Comment by Harper75** [comment]
Thank you very much. It is still not working, so I will try to fix the assembly errors.
