### ISSUE TITLE
How can I get location information for unalignable regions?

### ISSUE THREAD

**Issue by Wenwen012345** [schneebergerlab/syri#202]
Hello! @mnshgl0110 

I applied the software to get matching maps for two species. Now I want to get the location information of unalignable regions for circos plotting. How can I get the location information of unalignable regions? Something like gff3 format or bed format should work.

![image](https://github.com/schneebergerlab/syri/assets/63379795/c9884a14-5a09-427d-8416-ea972410fb5f)

Best！
Wen

**Comment by mnshgl0110** [comment]
The NOTAL aligned regions for both, the reference and the query, genomes are outputted in the syri.out file. You can grep them out and convert to bed files. The file-format for syri.out is described [here](https://schneebergerlab.github.io/syri/fileformat.html).

**Comment by Wenwen012345** [comment]
Okay. Thanks for the guidance. That's really the approach. Maybe I can think of some ways to do this without guidance, but you know, maybe you experts can offer some more precise advice.
