### ISSUE TITLE
colour to non-aligned region 

### ISSUE THREAD

**Issue by ABDULLAHGUJJAR** [schneebergerlab/syri#203]
Hi Plotsr Team,

I am currently using your amazing tool. Can I give color to non-aligned regions that are labeled as "NOTAL" in the syn.out file?

As for my second question, my top chromosomes' size appears to be bigger only at the end of the chromosomes, but I am also interested in showing the chromosome size difference at both ends.

Thank you for your assistance.

**Comment by mnshgl0110** [comment]
Hi @ABDULLAHGUJJAR. Please ask questions related to plotsr in the plotsr repo. I have created a new issue for you and closing this one.
