### ISSUE TITLE
i was trying to install syri but it ended up with too many warnings and error

### ISSUE THREAD

**Issue by Hemaprasanth24** [schneebergerlab/syri#206]
Compiling syri/pyxFiles/synsearchFunctions.pyx because it changed.
Compiling syri/pyxFiles/inversions.pyx because it changed.
Compiling syri/pyxFiles/tdfunc.pyx because it changed.
Compiling syri/pyxFiles/findshv.pyx because it changed.
Compiling syri/pyxFiles/findsv.pyx because it changed.
Compiling syri/pyxFiles/writeout.pyx because it changed.
[1/6] Cythonizing syri/pyxFiles/findshv.pyx
[2/6] Cythonizing syri/pyxFiles/findsv.pyx
[3/6] Cythonizing syri/pyxFiles/inversions.pyx
warning: syri/pyxFiles/function.pxd:17:37: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:37: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:73: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:73: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:125: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:125: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:164: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:164: Buffer unpacking not optimized away.
warning: syri/pyxFiles/inversions.pyx:162:46: Index should be typed for more efficient access
[4/6] Cythonizing syri/pyxFiles/synsearchFunctions.pyx
warning: syri/pyxFiles/function.pxd:17:37: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:37: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:73: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:73: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:125: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:125: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:164: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:164: Buffer unpacking not optimized away.
[5/6] Cythonizing syri/pyxFiles/tdfunc.pyx
warning: syri/pyxFiles/function.pxd:17:37: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:37: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:73: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:73: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:125: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:125: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:164: Buffer unpacking not optimized away.
warning: syri/pyxFiles/function.pxd:17:164: Buffer unpacking not optimized away.
[6/6] Cythonizing syri/pyxFiles/writeout.pyx
running install
/home/hemaprasanth/anaconda/envs/syri/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/hemaprasanth/anaconda/envs/syri/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating syri.egg-info
writing syri.egg-info/PKG-INFO
writing dependency_links to syri.egg-info/dependency_links.txt
writing top-level names to syri.egg-info/top_level.txt
writing manifest file 'syri.egg-info/SOURCES.txt'
reading manifest file 'syri.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'syri.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-cpython-311
creating build/lib.linux-x86_64-cpython-311/syri
copying syri/__init__.py -> build/lib.linux-x86_64-cpython-311/syri
creating build/lib.linux-x86_64-cpython-311/syri/scripts
copying syri/scripts/syri.py -> build/lib.linux-x86_64-cpython-311/syri/scripts
copying syri/scripts/__init__.py -> build/lib.linux-x86_64-cpython-311/syri/scripts
copying syri/scripts/chrrev.py -> build/lib.linux-x86_64-cpython-311/syri/scripts
copying syri/scripts/chroder.py -> build/lib.linux-x86_64-cpython-311/syri/scripts
copying syri/scripts/func.py -> build/lib.linux-x86_64-cpython-311/syri/scripts
copying syri/scripts/test_validatation.py -> build/lib.linux-x86_64-cpython-311/syri/scripts
copying syri/scripts/aligner.py -> build/lib.linux-x86_64-cpython-311/syri/scripts
running build_ext
building 'syri.synsearchFunctions' extension
creating build/temp.linux-x86_64-cpython-311
creating build/temp.linux-x86_64-cpython-311/syri
creating build/temp.linux-x86_64-cpython-311/syri/pyxFiles
gcc -pthread -B /home/hemaprasanth/anaconda/envs/syri/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/hemaprasanth/anaconda/envs/syri/include -fPIC -O2 -isystem /home/hemaprasanth/anaconda/envs/syri/include -fPIC -I/home/hemaprasanth/anaconda/envs/syri/lib/python3.11/site-packages/numpy/core/include -I/home/hemaprasanth/anaconda/envs/syri/include/python3.11 -c syri/pyxFiles/synsearchFunctions.cpp -o build/temp.linux-x86_64-cpython-311/syri/pyxFiles/synsearchFunctions.o
In file included from /home/hemaprasanth/anaconda/envs/syri/lib/python3.11/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                 from /home/hemaprasanth/anaconda/envs/syri/lib/python3.11/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/hemaprasanth/anaconda/envs/syri/lib/python3.11/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from syri/pyxFiles/synsearchFunctions.cpp:1130:
/home/hemaprasanth/anaconda/envs/syri/lib/python3.11/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
g++ -pthread -B /home/hemaprasanth/anaconda/envs/syri/compiler_compat -shared -Wl,--allow-shlib-undefined -Wl,-rpath,/home/hemaprasanth/anaconda/envs/syri/lib -Wl,-rpath-link,/home/hemaprasanth/anaconda/envs/syri/lib -L/home/hemaprasanth/anaconda/envs/syri/lib -Wl,--allow-shlib-undefined -Wl,-rpath,/home/hemaprasanth/anaconda/envs/syri/lib -Wl,-rpath-link,/home/hemaprasanth/anaconda/envs/syri/lib -L/home/hemaprasanth/anaconda/envs/syri/lib build/temp.linux-x86_64-cpython-311/syri/pyxFiles/synsearchFunctions.o -o build/lib.linux-x86_64-cpython-311/syri/synsearchFunctions.cpython-311-x86_64-linux-gnu.so
building 'syri.inversions' extension
gcc -pthread -B /home/hemaprasanth/anaconda/envs/syri/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/hemaprasanth/anaconda/envs/syri/include -fPIC -O2 -isystem /home/hemaprasanth/anaconda/envs/syri/include -fPIC -I/home/hemaprasanth/anaconda/envs/syri/lib/python3.11/site-packages/numpy/core/include -I/home/hemaprasanth/anaconda/envs/syri/include/python3.11 -c syri/pyxFiles/inversions.cpp -o build/temp.linux-x86_64-cpython-311/syri/pyxFiles/inversions.o
In file included from /home/hemaprasanth/anaconda/envs/syri/lib/python3.11/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                 from /home/hemaprasanth/anaconda/envs/syri/lib/python3.11/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/hemaprasanth/anaconda/envs/syri/lib/python3.11/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from syri/pyxFiles/inversions.cpp:1130:
/home/hemaprasanth/anaconda/envs/syri/lib/python3.11/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
In file included from /home/hemaprasanth/anaconda/envs/syri/include/python3.11/Python.h:11,
                 from syri/pyxFiles/inversions.cpp:30:
syri/pyxFiles/inversions.cpp: In function ‘int __pyx_import_star_set(PyObject*, PyObject*, char*)’:
/home/hemaprasanth/anaconda/envs/syri/include/python3.11/patchlevel.h:19:33: error: lvalue required as left operand of assignment
   19 | #define PY_MAJOR_VERSION        3
      |                                 ^
syri/pyxFiles/inversions.cpp:37949:5: note: in expansion of macro ‘PY_MAJOR_VERSION’
37949 |     PY_MAJOR_VERSION = __Pyx_PyInt_As_int(o); if (unlikely((PY_MAJOR_VERSION == (int)-1) && PyErr_Occurred())) __PYX_ERR(1, 203, __pyx_L2_error)
      |     ^~~~~~~~~~~~~~~~
error: command '/usr/bin/gcc' failed with exit code 1

**Comment by mnshgl0110** [comment]
It seems that you are using anaconda. Please try installing directly with conda using the following commands:
```
# Create a new environment and install syri with all dependencies
conda create -n syri_env -c bioconda syri
# Activate the environment
conda activate syri_env
```

**Comment by Hemaprasanth24** [comment]
thanks for your response
