### ISSUE TITLE
i have installed syri using conda but after running iam getting error in reading sam file i have used minimap2 to convert fna file to sam file

### ISSUE THREAD

**Issue by Hemaprasanth24** [schneebergerlab/syri#207]
syri -c align.sam -r GCA_020546685.1_ASM2054668v1_genomic.fna -q GCA_002198095.1_ASM219809v1_genomic.fna -k -F S
SAM reader - WARNING - NHMK01000003.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000021.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000015.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000029.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000016.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000012.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000009.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000023.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000018.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000006.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000004.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000034.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000001.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000040.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000039.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000019.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000020.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000027.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000002.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000007.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000013.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000008.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000035.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000031.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000011.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000036.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000033.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000005.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000037.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000038.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000024.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000010.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000017.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000026.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000014.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000028.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000025.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000030.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000022.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
SAM reader - WARNING - NHMK01000032.1 do not align with any reference sequence and cannot be analysed. Remove all unplaced scaffolds and contigs from the assemblies.
Reading BAM/SAM file - ERROR - Unexpected error in opening BAM/SAM file. 6

**Comment by Hemaprasanth24** [comment]
In syri is it possible to apply more than one genome as query genome

**Comment by mnshgl0110** [comment]
Syri performs pairwise comparisons. So, one query vs one reference at a time. Of course, you can run syri multiple times with different query genomes.

**Comment by Hemaprasanth24** [comment]
Awesome, thanks for the update!
