### ISSUE TITLE
Inversion OR Duplication ?

### ISSUE THREAD

**Issue by jxlabWzZ** [schneebergerlab/syri#209]
Hi, I have checked the INV of several super large fragments, and I think it should be a DUP. 
So how to adjust parameters to judge it as DUP?
<img width="1364" alt="截屏2023-08-11 下午7 59 14" src="https://github.com/schneebergerlab/syri/assets/54127791/ec38a464-8aee-4bae-bbf0-faa108e42e25">
<img width="825" alt="截屏2023-08-11 下午7 48 43" src="https://github.com/schneebergerlab/syri/assets/54127791/2ebdb193-5351-47c5-978f-46c568393dbe">

**Comment by mnshgl0110** [comment]
Hi @jxlabWzZ. I agree, this does not seem to be a inversion. Could you please share the syri.out file for the chr10 and the parameters that you used?

**Comment by jxlabWzZ** [comment]
./miniconda3/envs/syri/bin/syri --version
1.6.3

My script is :
./miniconda3/bin/nucmer --batch 1 -l 50 -c 100 -b 200 -t ${Threads} ref.fa qry.fa
./miniconda3/bin/delta-filter -m -i 90 -l 100 out.delta > ${output}.filtered.delta
./miniconda3/bin/show-coords -THrd ${output}.filtered.delta > ${output}.filtered.coords
./miniconda3/envs/syri/bin/python ./miniconda3/envs/syri/bin/syri -c ${output}.filtered.coords -d ${output}.filtered.delta -r ref.fa -q qry.fa

The coord and syri.out:
[p20mb.coords.txt](https://github.com/schneebergerlab/syri/files/12332994/p20mb.coords.txt)
[p20mb.out.txt](https://github.com/schneebergerlab/syri/files/12332998/p20mb.out.txt)

Thanks for your reply!

**Comment by mnshgl0110** [comment]
Thanks for sharing. Syri seems to be over-fitting these tandem repeat regions. It finds 56 alignments that supports this large inversion, but these alignments have large gaps between them.
```
$ grep INV1015 p20mb.out.txt | grep INVAL
```
You can manually filter out such inversions. You can also try setting a smaller value for the `--invgaplen` option.
