### ISSUE TITLE
Reading Coords - ERROR

### ISSUE THREAD

**Issue by farhan-lab** [schneebergerlab/syri#21]
Hi,

I  aligned reference and query genomes and successfully executed the following commands as given in your example. 
nucmer --maxmatch -c 100 -b 500 -l 50 refgenome qrygenome
delta-filter -m -i 90 -l 100 out.delta > out.filtered.delta
how-coords -THrd out.filtered.delta > out.filtered.coords

But I get the following error running syri
python3 $PATH_TO_SYRI -c out.filtered.coords -d out.filtered.delta -r refgenome -q qrygenome

syri - WARNING - <module>:115 - starting
Reading Coords - INFO - <module>:115 - Reading input from .tsv file
Reading Coords - WARNING - <module>:115 - Chromosomes IDs do not match.
Reading Coords - ERROR - <module>:115 - Unequal number of chromosomes in the genomes. Exiting

Why should I get this error although I have the same Chromosomes IDs and an equal number of chromosomes in both genomes? I appreciate your help. Thank you.

[out.filtered.coords.txt](https://github.com/schneebergerlab/syri/files/3997093/out.filtered.coords.txt)

**Comment by mnshgl0110** [comment]
Hi. The coords file contains alignments from scaffolds as well. SyRI cannot differentiate between ids corresponding to chromosomes and those corresponding to scaffolds. Please filter out the alignments from these scaffolds and then try again.

**Comment by farhan-lab** [comment]
Hi. Many thanks for your response. I eliminated the scaffolds considering only chromosomes and this time the SyRI run successfully without any problem. But I want to keep these unplaced scaffolds as they represent around 200MB of my genomes. I wonder whether it would be a correct approach to concatenate these scaffolds into a pseudo-scaffold and name their headers as a single header in a way like the chromosomes number? I am comparing two genomes of the same species, in which the query genome has an extra (B) chromosome whereas the reference genome lack this B chromosome. Therefore, I think I could merge the unplaced scaffolds of the reference genome in as additional pseudo-chromosome to balance the number of chromosomes in two genomes for this analysis?  This way Syri may detect putative B associated rearrangements as well. Do you recommend if this would be a good strategy? Many thanks in advance!

**Comment by mnshgl0110** [comment]
If the unplaced scaffolds (200 MB) represent the chromosome B, then, I assume that it would be OK to generate a pseudo-chromosome and then compare genomes using SyRI. However, this could result in false negative as scaffolds originating from biologically rearranged could be orientated linearly while pseudo-chromosome generation.

**Comment by erickmikwa** [comment]
Hi.Thanks for the great codes. I am very raw with scripting and bioinformatics. Could you please share an example chroder command that is working. Thanks

**Comment by mnshgl0110** [comment]
Hi. There is a small manual available at https://schneebergerlab.github.io/syri/. I assume that it might help you in running chroder. If there is still some confusion, then feel free to email me directly.

**Comment by erickmikwa** [comment]
Dear Manish,
Thanks for your reply and the nice work you re doing. The following is my
challenge:
I have a reference assembly (ref.fa), which has been assembly to
chromosome level and 36 separate de novo assemblies (e.g qry.fa)
re-sequences of the particular plant am working on.
The following is how I have been trying to run chroder to get
pseudo-assembly to use for synteny anaylysis;

**Comment by erickmikwa** [comment]
Dear Manish,
Thanks for your reply and the nice work you are doing. The following is my
challenge:
I have a reference genome (ref.fa), which has been assembly to
chromosome level and 36 separate de novo assemblies (e.g qry.fa)
re-sequences of the particular plant am working on.
The following is how I have been trying to run chroder to get
pseudo-assembly to use for synteny analysis;
              ./syri/bin/chroder ref.fa qry.fa -o OUT
#ref.fa(my reference genome-chromosomes), qry.fa(one of the de novo
assembly done using spades to scaffolds level-from ion torrent reads)
    And the following is the error;
    chroder: error: the following arguments are required: qry
Is there something am not doing right?


Thanks,
Erick Mikwa

**Comment by mnshgl0110** [comment]
Hi Erick,
I apologise for the delayed reply. There was some confusion with the status of the issue.
Please try running chroder as:
`./syri/bin/chroder  coords ref qry`
Where, `coords` is the alignment output in TSV format (as

**Comment by Fei5536** [comment]
> 

Hi,
I’m also experiencing this error, I realize it's because there exit some scaffolds, but I don't know how to deal with them, can I ask how you handle it?
