### ISSUE TITLE
syri reported an error:Reading coords - ERROR - aDir can only have values 1

### ISSUE THREAD

**Issue by zzzzzzzy7** [schneebergerlab/syri#211]
Hi!
According to the following code, I compared the two genomes with mummer to get out.delta, processed them with syri to get filter and coords file, and then tested sv with syri to get the error: Reading coords - ERROR - aDir can only have values 1.

`nucmer --mum -c 100 -b 500 -l 50 /home/zzy/Genome/Red_crucian_carp.genome.fasta /home/zzy/Genome/common_carp.genome.fna`
`delta-filter -1 -m -i 90 out.delta > out.filtered.delta`
`show-coords -THrcld out.filtered.delta > out.filtered.coords`
`syri -c out.filtered.coords -d out.filtered.delta -r ref.fasta -q qur.fasta`

I wonder if it's because the reference genome is chromosomal and the other one is not.
Thank you!

**Comment by mnshgl0110** [comment]
The parameters for the `show-coords` command are inconsistent with the requirements for syri. Please check the [readme](https://schneebergerlab.github.io/syri/pipeline.html)

**Comment by zzzzzzzy7** [comment]
> The parameters for the `show-coords` command are inconsistent with the requirements for syri. Please check the [readme](https://schneebergerlab.github.io/syri/pipeline.html)

Thank you！
