### ISSUE TITLE
Reading Coords - WARNING - Chromosomes IDs do not match.

### ISSUE THREAD

**Issue by renmiaozhen** [schneebergerlab/syri#213]
I know this question has been asked for many times, but I try those solutions, it doesn't work.

The two genomes share homologous, but their homologous chromosome IDs don't match (such as chr1 homologous with chr6). See the picture as follows:

![image](https://github.com/schneebergerlab/syri/assets/119120093/ab3f8df4-8e78-4d3e-9edb-45928cc7dca2)

So, I renamed the chrIDs to make them match for subsequent analysis. 
At the same time, between these two genomes, their chrs were reversed strands like the picture shows. Thus, I use `seqkit seq -r`  to reverse the strand direction. After preparing these, I follow the instructions normally until I run Syri.
I received the Syri error info:
Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - ERROR - Unequal number of chromosomes in the genomes. Exiting

I don't know how to fix these errors, would you be able to help me?

**Comment by mnshgl0110** [comment]
Does any of the genomes contain contigs/scaffolds? Removing them should solve this.

**Comment by renmiaozhen** [comment]
> Does any of the genomes contain contigs/scaffolds? Removing them should solve this.

My genomes have no contigs/scaffolds

**Comment by renmiaozhen** [comment]
> How many DNA molecules are there in the reference and query genome fasta files? You can check that using using : `grep -c '>' [REFERENCE].fasta`

I check my fasta file using `grep -c '>' [REFERENCE].fasta` , they are same.

**Comment by mnshgl0110** [comment]
This error happens when there are different number of chromosomes with informative alignments. If the genomes have same number of sequences, then the issue can happen if:
1) not all sequences (in both reference and query) are aligned: you can check the alignment file for this
2) for one (or more) sequence, all alignments are low quality and filtered out by syri: you can use syri's  `-f` parameter to stop alignment filtering

**Comment by renmiaozhen** [comment]
> This error happens when there are different number of chromosomes with informative alignments. If the genomes have same number of sequences, then the issue can happen if:
> 
> 1. not all sequences (in both reference and query) are aligned: you can check the alignment file for this
> 2. for one (or more) sequence, all alignments are low quality and filtered out by syri: you can use syri's  `-f` parameter to stop alignment filtering

OK, thank your answer.
