### ISSUE TITLE
What's the header of SyRI output

### ISSUE THREAD

**Issue by njliangdong** [schneebergerlab/syri#215]
Hi, everyone, 
I am curious about what the abbreviation of rearrangement events type, such as :CPG	CPL	DEL	DUP	DUPAL	HDR	INS	INVDP	INVDPAL	INVTR	INVTRAL	NOTAL	SNP	SYN	SYNAL	TRANS	TRANSAL (in penultimate column)

**Comment by mnshgl0110** [comment]
Described [here](https://schneebergerlab.github.io/syri/fileformat.html)
