### ISSUE TITLE
delta-filter unsecssful

### ISSUE THREAD

**Issue by ABDULLAHGUJJAR** [schneebergerlab/syri#216]
Hi Syri Team,
i am trying to run delta-filter step after nucmer alignment. 
delta-filter step killed after 1 or 2 days.
Any other solution please suggest me.
So we can't use number of threads/cpu in delata-filter step? Thanks

**Comment by lrauschning** [comment]
Hi,
from how you describe the issue, this sounds like either a problem with your compute infrastructure or with delta-filter.
In both cases, it is hard for us to help you.
Have you tried running your analysis on a smaller subset of the data and/or checking that you have an up-to-date version of mummer installed?

**Comment by mnshgl0110** [comment]
@ABDULLAHGUJJAR As the name suggests, `delta-filter` filters the alignments generated by nucmer. Based on the genome size, genome complexity, or alignment resolution, there could be millions of individual alignments that can take super long to filter. Some suggestions to overcome this:
1. As @lrauschning suggested, try the latest version of mummer 
2. Decrease alignment resolution
3. Use other whole-genome alignment tools like minimap2
4. Align and analyse homologous chromosomes separately

I hope this helps. Also, please contact the mummer developers (https://github.com/mummer4/mummer) as they might be able to provide more concrete information on how to speed-up delta-filter.
