### ISSUE TITLE
SAM read error for BAM file from minimap2

### ISSUE THREAD

**Issue by pdimens** [schneebergerlab/syri#218]
Hello,

Following the guide on the Syri documentation, when trying to load the alignments into Syri, this error is immediately shot out:
```
SAM reader - ERROR - Error in reading SAM file: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

The command to generate the alignment was
```
minimap2 -a -x asm5 -t 10 --MD --eqx reference.fasta query.fasta | samtools sort
```

Samtools reads the file no problem with `samtools view` and `samtools view -h` (or `-H`). Minimap version:
```
minimap2 --version
2.26-r1175
```

**Comment by alistairhockey** [comment]
Hi, I have also had this issue. Would be good to know how to fix!

**Comment by lrauschning** [comment]
Hi,
thanks for reporting this! Syri uses pysam to read SAM files.
Can you check which version of pysam you have installed on your system? you can do this by opening a python command line and typing `print(pysam.__version__)` after importing `pysam` with `import pysam`.

**Comment by lrauschning** [comment]
Ah also, try calling syri with `-F B`. Maybe your samtools call is automatically converting the file to BAM format (you can also check by trying to open the file in a text editor).

**Comment by pdimens** [comment]
Ah, thank you. It seems `-F B` was the trick.
