### ISSUE TITLE
ERROR - No syntenic region found for chromosome: chr15. This is potentially caused by the two assemblies having different strands for this chromosomes. Reverse complement the chromosome to ensure that the same strands are analysed. Exiting

### ISSUE THREAD

**Issue by ShirelyI** [schneebergerlab/syri#221]
Hi syri term,
when I run syri after align the genomes by using minimap2, it showed that " syri.chr15 - ERROR - No syntenic region found for chromosome: chr15. This is potentially caused by the two assemblies having different strands for this chromosomes. Reverse complement the chromosome to ensure that the same strands are analysed. Exiting. " ,Do you know how to solve it? Could the chroder command ignore chromosome orientation?
My genomes are chromosome-level, and syri version is 1.6.5.
the command is as follows:
![image](https://github.com/schneebergerlab/syri/assets/103233242/479d33fc-d59d-4d13-b457-2b8c53e9fbe3)
the log file is as follows:
![image](https://github.com/schneebergerlab/syri/assets/103233242/dd6360f6-375d-49f9-8b77-433c4ed46973)
Best,
Lily

**Comment by mnshgl0110** [comment]
This can be solved using [fixchr](https://github.com/schneebergerlab/fixchr). But as you have already tried that, I am closing this issue. Please start a new issue if you have more questions.
