### ISSUE TITLE
Sequence length calculation error

### ISSUE THREAD

**Issue by jiadong324** [schneebergerlab/syri#226]
Hi,

Thanks for developing this nice tool! 

Here is my error message for single chromosome comparison:
```
Running SyRI - ERROR - Length of query sequence of chr16_hap2 is less than the maximum coordinate of its aligned regions.
```

However, I checked the maximum alignment coordinate, which is smaller than the length of my query sequence. 

Then, I added ```record_dict = SeqIO.to_dict(SeqIO.parse(qry_fa, "fasta"))
print(len(record_dict['chr16_hap2']))``` for debug. The query length calculated by my code is the same as the one calculated by ```samtools faidx```, which is 13bp longer than the query length calculated by your ```readFasta()``` function. 

Looking forward to your reply!

**Comment by mnshgl0110** [comment]
Are there white spaces or special characters in the fasta sequence? Other than that I cannot thing of any other reason for this discrepancy. Please check and remove (if any) such characters.
If this does not work then, please share the sequence for me to test.

**Comment by jiadong324** [comment]
Please download the sequence at: https://drive.google.com/file/d/1Cqs1MF8x_WEuy9ZYZqiR2L0UQQbyh93c/view?usp=drive_link

**Comment by jiadong324** [comment]
I also have the warning and error below:

 ```
Reading Coords - WARNING - Reference chromosome haplotype1-0000038 has high fraction of inverted alignments with its homologous chromosome in the query genome (haplotype1-0000031). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.

...

IndexError: list index out of range 
```

According to the existing issues, I first made the dotpot with minimap2 alignment. It has several short inverted repeats highlighted in red.
<img width="1606" alt="image" src="https://github.com/schneebergerlab/syri/assets/6951612/97c0e1a8-3c89-41ee-8367-4ae3460c8706">.

Once I changed to wfmash, most of the short inverted segments are gone. But I still got the same warning and error.

<img width="1595" alt="image" src="https://github.com/schneebergerlab/syri/assets/6951612/d16182f4-da25-480d-b8e7-f9a150fb1e61">

Is the index error caused by these inverted segments?

**Comment by jiadong324** [comment]
You are correct, the blue lines are inverted. I found people do reverse complementary, what is your best suggestion for such case.  

Please check the new link https://drive.google.com/file/d/1Cqs1MF8x_WEuy9ZYZqiR2L0UQQbyh93c/view?usp=sharing.
