### ISSUE TITLE
translocation ascross chromosomes 

### ISSUE THREAD

**Issue by nicolo-tellini** [schneebergerlab/syri#227]
Hello @mnshgl0110,

nice tool! I saw the example plot here https://schneebergerlab.github.io/syri/plotsr.html .
I am wondering if there is the possibility to plot translocation across different chromosome. 

thanks 

nic

**Comment by mnshgl0110** [comment]
Yes.
https://github.com/schneebergerlab/plotsr
https://doi.org/10.1093/bioinformatics/btac196
