### ISSUE TITLE
error running syri: IndexError: list index out of range

### ISSUE THREAD

**Issue by QuintoHe** [schneebergerlab/syri#231]
Hi,
Thanks for the handy tool.
I encountered an error that prevented me from successfully running syri.
the error information is as the pics show
I completely follow this example pipeline for running SyRI（https://schneebergerlab.github.io/syri/pipeline.html），but remain confused why can't successfully go through this pipeline
my two genomes are pretty homologous and both have 12 Chr, also these two fasta file are fine prepared for the minimap2 run and syri.
eager to receive your reply！ 
![error](https://github.com/schneebergerlab/syri/assets/107121725/2a409de3-49f9-4e57-8473-81ed4590bc0e)
![output](https://github.com/schneebergerlab/syri/assets/107121725/82480a1e-f63c-4fdd-95f4-7f06317a4528)

best wishes
Quinto

**Comment by mnshgl0110** [comment]
Duplicate https://github.com/schneebergerlab/syri/issues/48 https://github.com/schneebergerlab/syri/issues/176
Check README -> Current Limitations

**Comment by QuintoHe** [comment]
> Duplicate #48 #176 Check README -> Current Limitations

many thanks
