### ISSUE TITLE
How to identify breakpoint of large inversion 

### ISSUE THREAD

**Issue by bijendrabio** [schneebergerlab/syri#232]
Hello,
Just curious to know if there is a method to identify a breakpoints coordinates within the genomes for large inversions (INV) from the syri output? Kindly suggest!

Regards,
B

**Comment by mnshgl0110** [comment]
I am not sure I get this. What breakpoints do you mean? Syri's output consists of start/end positions of rearrangements, so those are the breakpoints.

**Comment by Wenwen012345** [comment]
Hello, has this problem been solved?

**Comment by mnshgl0110** [comment]
It is not clear what the actual question is. Could you please provide more information?
