### ISSUE TITLE
Aligning bacterial genomes with different number of contigs

### ISSUE THREAD

**Issue by mbhall88** [schneebergerlab/syri#233]
This is a really awesome tool. I would love to be able to use it more generally on bacterial genomes. It works great if I have the same number of contigs, but sometimes I want to align two genomes where one genome might have 3 plasmids and the other genome might only have 1. 

Is there a way to deal with this in syri already? Or is this something when you can add a flag that says ignore contigs that don't align. In my example the names of the contigs aren't necessarily going to be the same.

**Comment by mnshgl0110** [comment]
Ideally, syri requires the two genomes to have homologous chromosomes. In
your case, that would mean comparing 1 plasmid to its homologous
counterpart among the three plasmids from the other genome. If you want nt
to do this, then you can just filter out the non homologous contigs either
manually or using fixchr.

You can also consider concatenating the three plasmids to get one long
plasmid and then running the syri pipeline. But this would be a bit less
elegant and require some post-processing of syri output.

**Comment by mbhall88** [comment]
Great, I'll give this a go. Thanks!
