### ISSUE TITLE
longer processing time for large genome?

### ISSUE THREAD

**Issue by bijendrabio** [schneebergerlab/syri#235]
Hello, 
The Syri is taking a significantly longer time during the 'INFO - mapstar:48 - Identifying Inversions' step. The input aligned genomes are each 700Mb in size. Do you have any suggestions as to why it is taking longer to process?

Regards,
B

**Comment by mnshgl0110** [comment]
This could happen if there are very large inversions. Try using a smaller value for `--invgaplen`.
