### ISSUE TITLE
VCF format

### ISSUE THREAD

**Issue by owensgl** [schneebergerlab/syri#24]
In the final VCF syri produces it outputs both the mummer alignments and the larger regions that syri puts together. As I understand it, a single region can be made of multiple alignments. In the VCF each alignment has a parent ID (e.g. Parent=SYN3080), but the parent regions aren't labelled. To get what region SYN3080 corresponds to I have to compare the maximum start and stop of all the alignments with that parental region. Could you include an ID field in the region lines? 

Also, could the VCF file be sorted numerically by position? Right now its alphabetically so ordering is a bit weird. 

Thanks for making this program!

**Comment by mnshgl0110** [comment]
Hi Greg! Thanks for the nice suggestions. I have added the ID of each annotation in the ID column of the VCF. Also, when all chromosomes have integer ids, then they would be sorted numerically as well.
Best
M
