### ISSUE TITLE
Removes 'low-quality alignments' - what does this mean?

### ISSUE THREAD

**Issue by c-hazel-f** [schneebergerlab/syri#240]
Hello,
I was just wondering what parameters count as 'low quality alignments' for SyRi, if you are able to provide or point me in the direction for more information?

**Comment by mnshgl0110** [comment]
Sorry, for a delayed response. Syri selects alignments which are longer than 100bp and have alignment identity >90%. This is reported in the syri.log file as well with the message:
```Filtering low-quality alignments (alignment quality < 90, alignment length < 100)```

Currently, these thresholds are hard-coded:
https://github.com/schneebergerlab/syri/blob/cc575be17c69b8ff10e768327f1826a8b837acfa/syri/pyxFiles/synsearchFunctions.pyx#L388

but users are encouraged to adjust it as per their requirements.
