### ISSUE TITLE
complicated region not detected correctly

### ISSUE THREAD

**Issue by KewinOgink** [schneebergerlab/syri#241]
Hello,

We have a chromosome for which we have markers that show the following (r=ref, q=qry, i=INV, s=syntenic)
![image](https://github.com/schneebergerlab/syri/assets/46783201/3c028d36-1d44-46c7-b5da-0bfd011a7233)

This is also seen in the paf file [paf.txt](https://github.com/schneebergerlab/syri/files/14852015/paf.txt)

However in Syri it is detected as a single inversion
![image](https://github.com/schneebergerlab/syri/assets/46783201/31225f1b-8045-4f9e-8619-774616202a89)

I cannot provide the assemblies, but just wanted to let you know. Is there anything that can be done about it, like different settings?

I ran pretty default settings:

unimap -t $threads --eqx -c -o $wga_dir/$base.paf $ref.umi $sample

syri \
    -c $sample \
    -r ${refbase}.filtered \
    -q ${base}.filtered \
    --nc $threads -F P -f --prefix $base.

**Comment by mnshgl0110** [comment]
I guess, in this particular case, selecting the large inversion would have probably outscored other possible annotations. Decreasing the value of `--invgaplen` should make syri not find this large inversion.

However, it is not trivial to say whether this large inversion is correct or not. This complex region could have evolved as:

1) One large inversion and then couple of smaller inversion within this large region (these smaller region appearing syntenic now)
2) The large syntenic region is actually syntenic and then multiple inversions/translocations happened around it

In terms of simplicity, the large inversion might be the correct annotation, but of course, difficult to be sure about.
