### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by Hemaprasanth24** [schneebergerlab/syri#245]
Good afternoon,
Myself hemaprasanth iam encountering a key error while comparing 2 chromosomes

(major_project) hema@hema-Aspire-A715-51G:~/major_project$ syri -c /home/hema/major_project/sam_file/Human_mouse/human_mouse_ch10/human_ch10_mouse_ch3.sam -r /home/hema/major_project/Fasta_files/GRCh38/GRCh38_ch10.fasta -q /home/hema/major_project/Fasta_files/GRCm39/GRCm38_ch3.fasta -k -F S --dir /home/hema/major_project/syri_output/human_mouse_ch10/human_ch10_mouse_ch3 --prefix human_ch10_mouse_ch3
Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - WARNING - Matching them automatically. For each reference genome, most similar query genome will be selected. Check mapids.txt for mapping used.
Reading Coords - WARNING - Reference chromosome NC_000010.11 do not have any directed alignments with its homologous chromosome in the query genome (NC_000069.7). Filtering out all corresponding alignments.
Traceback (most recent call last):
  File "/home/hema/anaconda3/envs/major_project/bin/syri", line 6, in <module>
    main(sys.argv[1:])
  File "/home/hema/anaconda3/envs/major_project/lib/python3.8/site-packages/syri/scripts/syri.py", line 326, in main
    syri(args)
  File "/home/hema/anaconda3/envs/major_project/lib/python3.8/site-packages/syri/scripts/syri.py", line 183, in syri
    if len(seq) < bchr_size[chrlink[chrid]]:
KeyError: 'NC_000010.11'

**Comment by mnshgl0110** [comment]
Are you comparing only Human-Chr10 vs Mouse-Chr03 ? If so, are these chromosomes homologous to each other? Syri, needs homologous chromosomes as it needs to find synteny. Check the documentation here: https://schneebergerlab.github.io/syri/

**Comment by Hemaprasanth24** [comment]
Good morning,
Thanks for the replay 
actually I am try to identify variants between human and mouse 
actually the gene location between human and mouse differs so i decided the compare like this such as
human-chr10 vs mouse-chr01
human-chr10 vs mouse-chr02
human-chr10 vs mouse-chr03
human-chr10 vs mouse-chr04
.
.
.
human-chr10 vs mouse-chr0Y

**Comment by mnshgl0110** [comment]
I do not think this would work as syri requires homologous chromosomes. Please check the [documentation](https://schneebergerlab.github.io/syri/).
