### ISSUE TITLE
translocated to different chromosomes

### ISSUE THREAD

**Issue by liu3c** [schneebergerlab/syri#247]
Dear @mnshgl0110 

Is it normal to identify translocation variants in multiple samples that are in the same reference genome coordinates but translocated to different chromosomes? For example, some samples transpose to Chr10 and others to Chr2
How can I fix it?
Thanks for your time and help.
best regards.

**Comment by mnshgl0110** [comment]
Yes, it is possible to find such translocations, specially for transposable elements.
It is unclear to me why you need to fix it? And what would be the "fixed" output?

**Comment by liu3c** [comment]
Thank you for your reply, I mean is such a variant not being used as a translocation, does it need to be removed?

**Comment by mnshgl0110** [comment]
Sorry, I am unable to understand the question. Can you please share some more information, and maybe some examples?
