### ISSUE TITLE
Wrong CIGAR string

### ISSUE THREAD

**Issue by MatteoSebastianelli** [schneebergerlab/syri#252]
Hello,

I want to use syri to detect SV by running the following commands:

minimap2 -ax asm5 -eqx file.HiC.fa file.hap1.fa > out.sam

syri -c out.sam -r file.HiC.fa -q file.hap1.fa -F S -k --prefix syri_output

However, I immediately get an error about the CIGAR string. As you can see from the minimap command, I don't include any flags to modify the CIGAR (e.g. -c or -L). Can this error be related with this? I'd appreciate any suggestion 
Erorr message:
SAM reader - ERROR - Incorrect CIGAR string found. CIGAR string can only have I/D/H/S/X/=. CIGAR STRING: 13687204S40M6I588M1D508M1D1669M2D1304M2I3877M1D850M6D1132M7D380M17I1560M1D889M1D1233M9D2832M1D1333M7I688M1D1106M3D1274M1D505M7D143M1I429M3I1194M4I1457M1D769M56I905M1D68M1D1334M4D231M1I167M471I242M1I405M1I2623M1I2M4D992M1D517M2I2996M1D461M2I1026M1D325M1I477M1D1516M3D675M1I470M1I2176M3D700M2D291M1I195M4I230M8D21M3I162M2I789M20D90M8D839M1D1724M2D440M5I402M6D1882M4D1022M1I170M3I613M1I65M5D468M3I1681M24D1624M1I549M2D114M1D754M1I198M1D5094M8D215M2D3728M1I282M3I1077M1I1338M1D303M2D379M7D690M15I1145M1I2630M2D3957M7I79M1I719M1I885M4D1766M2I45M1I8M13I2534M1I324M21I29M1D2241M15I3355M4D257M2D48M70D271M3D61M1D58M1I647M1D1838M2D372M4D826M4I1988M1I3696M23I425M3D3471M8I1778M6D353M1D3764M1D344M1D688M3D29M6I11M4D1867M1D57M2I704M2D777M3I178M1I27M1I2494M7D392M17I8D487M2D1476M2D718M7D1346M1I67M1I2634M1D202M2D2123M2I2102M1D2502M5I1161M1I511M6D387M1I397M1D3712M2D148M1I758M8I144M1D2014M1I1420M2D74M1D299M18I350M1I3379M1I1476M6D304M2I190M1I230M4D44M12D37M1I395M6I680M4D840M6D615M5I815M1D561M1D412M1I99M1I1310M2D1216M7I1166M29I482M12D20M2D666M1D433M1D17M4D499M1D1661M2I36M1D1730M57D703M1I478M2D2061M7D18M5D569M5I1572M1I351M2D58M1I81M1I669M6D1846M1I1860M1I1606M2I3045M1I65M10D815M2I249M1I509M1I20M5D384M1I543M1D619M2D627M27I3014M10I428M7I288M8I2566M2D1913M1D1058M1I1168M1I644M1D30M1D714M1D316M1D346M21I295M1I1154M1I1645M1D1228M50D1M9I2647M8D548M6I248M34D146M22I1289M1I1982M1I650M1D202M1D499M16I1065M4D2480M12D1378M4D2030M1D2243M34D83M2I73M3I1110M6D610M1D663M1D1549M2I1601M8I2197M6D3270M3I1040M3I3306M3I951M14D817M1I106M7I185M1I30M4D5M2I254M1D1192M54D1231M5D42M20D636M1I1554M3I415M1I1375M121D836M3D468M12I431M3I120M2I478M1D17M150D1814M10I407M1I336M17D1808M8D206M2D657M2I425M1D538M6D2162M2I1746M1D424M2D557M1I198M1D429M3D292M1D744M3D612M1I677M3I639M8I42M1D152M12D2625M1D4480M1D2164M4D527M31D271M2I71M21I9M6D1790M1D1846M1D3474M1I1733M1D1494M2D539M2I326M1I1088M1I176M1I178M2D932M1D1408M9I1923M1D3599M2I78M1D924M1I1961M1D202M1D13M1D498M2D252M1I1815M1I1031M1I2987M2I793M20I279M1D9M6I1183M1D569M1D1621M1I2276M49D5933M1I536M1I150M4I552M1D293M1I1404M108I69M1I1721M5D2027M1D4065M6D1160M2I28M15D14M7I205M3D2366M1D1726M1I1134M3D868M2D2781M1I58M1I2894M1D792M1D8428M1I181M5D104M3D102M4I64M12I171M1I295M17D943M15D651M6I211M11I805M22I3290M7D246M1D3073M3D586M5I532M4I102M9D3689M1D4022M2D3133M1I1543M1D930M1D1095M2I471M15D8M1I64M1D9M4I924M1I679M2I358M1D268M6D72M1I441M6D1976M3D302M6D761M1I125M1I1062M1I3773M6D953M3D667M1D393M1I1843M2D287M10D384M1D855M1D500M2I2206M1I353M10D423M1D1282M1I1161M1I1083M2I978M53D1M3I709M2D626M2D152M6D302M3D242M3D112M4I2981M2I1298M14D272M13D1337M2I15M1I832M1D2465M1I31M1D268M11I762M1D812M1I227M1D377M1I1460M6I374M1I486M1D710M1D335M1D1327M1D408M1D2117M2D235M25I500M31D651M17I438M2D2928M1D48M1I316M1D488M2D3087M1I520M13D1355M12D2231M4D338M4D179M15I591M1D17M14D1415M1D1527M1I1327M2D912M2I399M2I181M3I170M1I911M28I395M36I39M4D194M8I123M8I1353M45D368M1D1163M7D162M3D510M1I1968M1D130M1D526M4D2889M3D50M1I2820M1D80M106I1779M18D99M3D541M1D3917M18D65M4D1227M4D203M1D401M1I842M5D1983M1I2461M1I1556M9I308M1I2880M2D2115M9D640M3I7M1D4M2D1823M18I1454M66D941M28D2360M3D95M1D2577M1I1118M1I126M1I1515M14D17M1D2267M1I1248M15D1761M2I820M1D1077M4I2076M1I524M3D1526M8D1582M2D234M3I828M1D524M1D30M1D152M1D416M3D1641M1D98M2D69M2D1807M1D3185M3I420M1I734M2D86M620D273M4D174M4D889M2I611M56D782M10I28M4D5679M396D83M5I472M1D2065M1D254M2D1256M2I112M4D631M2I512M1D496M4I7800M3D2149M3D46M8D9M1D32M1D811M1D900M57I491M2I205M1D840M1D672M2D408M1I815M1I107M17I865M3I1748M1D1021M2D12M2D546M1D6110M6I2635M1D4440M3I111M1I3645M7I726M2D3144M1D396M3I317M1D106M5I1167M13D832M4I330M7D301M10I438M3I246M7I2167M3D1472M4D815M1I35M1I810M1D202M2D1066M2I894M9I187M1D255M1I37M5I793M1I663M1I478M1D325M12D1154M1I5204M1D2276M9I679M17D605M6D328M14I1M8D60M3I2929M100D3607M4I1864M3D135M1I471M3I690M3I838M4I1441M14I387M4D299M1D1267M3D128M4D655M5D1100M2I101M3I997M1I1354M4D1791M13I57M1I710M4D1711M3D1504M1I61M9D1478M1D23M7I412M2I1241M1D176M9I315M1D20M1D3569M1D3618M1D181M4I358M5D640M9I778M1I1442M14I4771M1I5852M1I1835M1D585M1D3955M1I945M2I578M4D259M7I3460M2D204M3I4M108D23M16D1001M16D707M2D75M1D1209M24I4189M1I1790M10D109M1I66M3I378M1D14M2D935M2D372M36D542M1I1306M10D451M3D1232M3I3186M2D1821M3I2595M1D2628M1D696M5D262M1I1201M1D64M1I492M1I841M1D3470M1D336M1I120M1I995M19D200M46I547M1D526M1D176M1D299M1I1615M5D451M1D58M3D2302M3I3622M1I65M1I2902M2D201M1I2771M1I281M1I14M8D1339M1D3603M691D45M2D678M1D875M11D241M19I822M5I197M7D774M12I97M3I207M5D362M17I129M5D401M4D626M1I4M7I6121M1D32M4I925M4D1232M104D484M1I262M1I578M4D163M1I19M1I3804M2I180M1D550M1I865M4D755M1D531M3I1692M5I1469M1I500M8I535M4I379M1D4116M1I39M1I2168M3I751M1I187M1I439M1D242M10I2076M1I752M1D45M3I196M6D344M93D212M1D189M3I2354M2I50M2D1084M1I2038M12I1891M2I2187M1D3000M2I6298M1D421M2D1463M1D117M9I700M1I448M1D1275M14D2115M3I6440M1I1090M3I2706M2D19M1D685M1I294M1D178M8D15M163I2232M1I534M1D167M10D90M12I166M4I1780M3I386M1D106M4I466M1D132M5D780M154D152M1D145M2I2651M10I1777M1I3857M1I63M2D324M1I1192M2I1365M1I1109M2D592M11D478M4D260M1D671M1I1545M24I1257M1D269M29I54M1D2848M1D2771M2D40M5D302M1D2275M1D184M1D1329M3I2918M1I163M6D2884M172D21M1D803M1I1700M4I402M1I655M2I335M4D158M9D442M1I590M5I14M6D1045M3I546M1D815M1I142M1I3320M14I76M1D623M1I321M3I278M1D866M3D1881M1D534M1I1410M1I1626M14I3700M1D1643M16I1030M1I448M4D52M3D2107M1I1535M8D1997M1D336M2I466M6I465M1D203M1D634M1D1008M1I525M1I206M1I1627M2D4665M3I32M1I390M1D1118M1D285M2I168M1D521M2D149M2I841M10I1886M8D2412M9D277M2I442M1D316M5I2M7D105M3I509M11I353M42D1353M6I213M1D1263M2D633M1D1270M1D3625M2I596M1I106M1I2033M6I1364M2I442M1I190M1I904M1D951M4D462M2D5195M1I896M1I899M1I563M2I259M2D2010M2I3330M6I2208M2I15M1I2089M1D737M1D1952M4D357M1I46M1I3243M21I2002M1D209M1D317M1D3162M1I31M2I400M52D1830M1D778M1D1254M2D350M1D438M2D1371M6I2335M2D93M2D3103M21D5187M1D59M3I565M1I2476M1I1543M1D875M1I1178M1I122M1D321M1I1533M2D4094M5I155M8I362M2D639M1I805M14I1M11D176M293D57M121D1825M2I378M9I209M8D46M18I493M1D163M19I110M21D899M7I1250M6D3253M4I284M1I1853M5D1107M3D281M1D180M1I470M6I1272M2D759M3D315M2I324M1D1121M2D755M2I391M1I767M63D197M4D817M1I608M2I734M5I111M1D409M4I1914M2I120M2D132M3D67M4I27M8D39M4D98M1D281M2D649M7D109M7D336M9I917M19D613M4D4117M27I87M1D2263M5I384M6I59M1D3168M4D268M4D630M2D125M10D796M2I1829M1I23M5D316M2D122M1I40M2D1004M1D91M2D550M1D629M1D367M1D1108M1I418M30I103M5I593M1D3034M1D586M1D745M2D461M1I195M8I19D597M10I2620M4D1727M1I613M1I157M1I1083M1D712M1D1569M2D834M2I4270M1I145M6D1394M1I584M3D432M4I50M12D2M5D366M1I1225M1I67M2I1022M2D750M1D871M4I748M84I4308M1D2108M7I275M3I1008M60I965M1I214M25I89M1D44M1I1179M1I516M2I4124M1I118M1I1537M1D181M9I2345M9D211M1D800M5I214M27I2372M1I3130M1D1220M45I1571M2I2942M1D215M2D3260M3D35M1D865M1D1302M2I403M1D704M6D1325M1D380M2I1548M1D138M1I496M17D1123M5D194M2D188M2D1106M6D188M1I202M1D714M1D229M1I127M1I967M2I1226M2I1108M1D1072M1D4085M1D802M4D642M2I538M3I1442M1D1023M5D105M4D196M3D278M10D1810M1I2630M3D2588M1D652M2I258M4I1268M2I3116M2I2943M1I1417M2I6M1I53M3I276M1I244M7I446M1I880M8I329M1D846M2I2310M6I2536M2D323M1I485M1D3031M1D446M5D1658M3I1669M1I1306M20I962M1I193M1I692M28D14M1D390M1D3009M1I813M1D44M2D1384M2D111M1I352M1I103M2D135M3D1050M10I1554M1D235M749D180M2D785M9I818M1I24M1D1531M3I1M5D675M4I125M1I270M1I283M1D716M2I4282M1I1010M32D36M20D5087M1D1343M5I2952M6I286M1D841M5D2578M2I1468M4I2118M2D2760M1I639M2D503M2D1391M16D2471M6D20M1I448M17D10M2I8M5I71M2I3951M11D2195M1D1372M10D114M2I386M1D749M2I1062M1I5183M6D856M1I213M1I1321M2I32M4D2692M12I3308M2I341M5I107M3I83M12D1339M1D688M3D3M4D57M2D1204M1D1090M2I308M2D3998M1D246M1D892M8I796M1D1473M1D495M1I850M3I1688M2D2800M1I505M5I300M5I77M2D315M1D732M2D473M1I254M2D1220M1D1625M1D738M1I1707M1D974M3I154M5I129M1D880M7D1900M3D775M3I29M1D163M23I52M1D2048M3I30M7D654M1I4776M1I747M2D5M6D503M1D1786M5I2732M12D19M1I497M1D246M1D1123M1D453M7D38M5I936M4D5460M1D673M1D879M1I53M1I3484M1D94M2I631M1D3295M1D686M1D420M1I3000M6I2043M5D2404M1I290M4D1288M1I1069M1D151M5D2423M9D411M2D1800M2D648M11D137M3I2145M11D1769M1D750M5I555M7D1397M2I525M2I1438M1D575M1I117M2D802M4I942M2I1444M5I2185M1D1668M1I739M2D180M1I815M3D1075M14D1155M2I4709M6I997M1D1388M4D1374M2I374M1I98M5I50M1D30M1D709M1D567M1D3182M1I6209M1D233M9D118M1D1617M1D11M1D2227M1I152M29D1837M28D396M1D307M4I207M7I2005M1D143M2D827M2I914M16D723M1D3722M49I1159M1D1302M5D254M3D159M1I792M1D2911M2I1345M2D1911M1I1717M1D1695M5I2847M401I397M1D145M12I439M1I238M1D64M581I913M1I882M1I1299M1I975M1I968M1D1631M2D670M1I916M2I314M9I1448M1I1186M4I570M40I321M1D1588M1I3556M2I1317M21I1070M1I97M1I2230M1I305M7D122M1I49M1I1058M5D1603M5I1M2D792M3I476M5D726M1D1081M1I1230M4I2448M2I629M1I385M1D45M3D821M5D1220M1D2447M1D1020M1D506M2I268M1D437M1D607M1I364M1D1273M5D1067M4D1452M1D377M3I681M2D2488M1D1059M3I524M12I374M2I190M4I192M2D1462M1D39M2I182M4D1632M1I449M6I919M1I668M1D74M1D780M4I2547M1I1236M1D1965M1D827M1I971M1I460M3I312M8D136M1I69M4D1520M1I41M3I420M1D722M13I1783M2D6M2D322M3I367M13I1825M1D612M1I4498M14I19M1D828M1I8M1I999M1D471M2I103M2I1247M1D1845M4I451M1I882M1I28M1D257M1D466M1I399M13I429M2I410M3I82M1I1359M1I123M4I859M6I1132M3D678M4D1952M1D4076M1D2063M4D338M1D181M4D1027M1D454M1D1456M1I5562M34I224M9D789M1D4201M3D580M10D1672M1I3608M2I356M1I4330M1D1130M1D42M1I654M2D976M3D26M2D996M1D1267M2D820M1I596M8I2318M1I3625M2D936M1D152M1I53M5D37M3D1092M1I397M1I2914M4I1230M1I907M1I820M26D188M15I289M3D5355M2I341M3D1059M4D945M1D694M2I740M1D1636M1D1066M3I942M2I1391M10D468M5I2742M1D3M2D607M6D141M2D771M1D1271M24D2376M1I1042M2D1140M2I3M2I893M1I399M1D93M1I177M4I52M17I7M1D497M3D100M1D346M4D5146M10D887M1I2245M1D2609M1I130M12I2288M1D1273M1D5737M3D211M1D471M9D865M21D2764M1I39M4D6981M2I48M1D305M2D505M1D14M16D835M2D239M4D91M9I41M1D973M517D1048M2I506M2I286M1D22M5I179M2I990M2D425M10D870M1I582M3I330M1D94M1I577M6D1465M1D2091M1I984M1D1298M5D84M2I1027M2I767M1D871M1I583M1I2659M1I353M8I1753M1I2874M1I366M8D2217M2I10M35I1665M1I485M2I6M2I436M13D725M1D626M1I361M1D522M1D402M2D29M1D20M1I5991M21I2438M1D182M1D459M4D731M1D1129M1I282M2I692M2D378M4D264M15D1026M1D1356M1I418M37D1220M1I375M1D77M1D270M1D530M2I60M1I259M2D289M1D3073M1I664M2D53M10D767M1I181M2I1189M8D387M1D770M1I403M2D717M1I313M10I605M1D969M1I1043M1I161M2D472M1I978M1D1393M3D2400M5I2313M1I933M3D2671M5D1093M1I216M5D272M3D157M1D1058M1D151M2I1234M1D512M1I52M4I200M3I2298M7D82M2I808M2I2199M2I20M1I382M20D357M1D149M1I571M1D1616M4D396M2D1050M2I577M1I1516M3I441M17I2927M1D1479M2D1233M11I105M2I40M5I9M2D53M1D315M1I943M1D799M1I209M6I2579M1I249M1I2652M2I398M1I17M2D664M6I1322M5D2210M27D1072M1I288M6D1073M1I69M2I1094M2I666M6I318M12D805M2I147M1D2034M4D257M3D16M3D148M1D100M1D406M3D1767M4D964M13I51M22D1458M434D2434M6D260M1D250M3I314M1D486M5D136M1D454M4D221M3I255M2I452M3D113M2I663M3D590M2I328M2D457M2I47M6D126M1D312M1D1482M9I1983M1D779M1D486M3I363M5I217M1D185M1D1876M1D631M9I452M5D309M1I1697M1D715M1D2248M1I1085M1D552M3D4363M4D1748M1I796M16D741M1D285M14D2549M20I1996M1D882M2I1411M1D941M13I7D751M2I407M45I923M2D625M6I92M1I1392M1I76M5I1954M7D1836M7D65M1D1641M1D1537M2D3000M1D255M1I251M1D610M10D470M1D1098M3D1402M6D1304M4I461M1I329M1D2319M1D1534M1D52M2D378M3D75M1I341M2D451M3I390M1D135M9D494M15D748M4D80M1I185M1I191M1D791M5I63M1D1560M32D86M1I401M6D34M19D141M1I968M1I477M1I105M5I260M2I225M11D259M6D198M1D2953M1I478M1I1653M3D3657M8D1970M175I231M1I1004M1D126M46830924S

**Comment by mnshgl0110** [comment]
You need to use `--eqx`, currently you have `-eqx`. https://lh3.github.io/minimap2/minimap2.html
