### ISSUE TITLE
IndexError: list index out of range   syri

### ISSUE THREAD

**Issue by lifannn11** [schneebergerlab/syri#254]
Hi:
When I run syri, some of them can successfully run, but some encounter a problem. I've tried for a long time but still can't solve it. Does anyone know how to fix it?
![image](https://github.com/schneebergerlab/syri/assets/166804257/529285d7-cf58-4aba-8589-4db3210e6504)

**Comment by lrauschning** [comment]
Hi @lifannn11 
can you be more specific as to how you are calling syri, and when it runs for you/when it produces the error in the screenshot?

**Comment by lifannn11** [comment]
> Hi @lifannn11 can you be more specific as to how you are calling syri, and when it runs for you/when it produces the error in the screenshot?

Hi:
Here are the specific details.
![image](https://github.com/schneebergerlab/syri/assets/166804257/b03aa0be-587b-4c29-9e61-6a7440701c4f)

Thanks

**Comment by lrauschning** [comment]
And which samples fail for you vs which ones run successfully?
Sorry, from the screenshot I don't really know what is failing here. Is there any other output, or something printed to the log file (should be `syri.log` with how you're calling it)?

**Comment by lifannn11** [comment]
> 哪些样本失败了，哪些样本成功运行了？对不起，从屏幕截图中我真的不知道这里有什么失败。是否有任何其他输出，或者打印到日志文件的内容（应该与你的调用方式相同）？`syri.log`

Hello, this is the generated SV.syri.log file.
[SV.syri.log](https://github.com/user-attachments/files/15610786/SV.syri.log)

Thanks.

**Comment by mnshgl0110** [comment]
Hi @lifannn11,
This issue is typically caused when the genomes have different strands for homologous chromosomes (https://github.com/schneebergerlab/syri/issues/48). Have you checked whether that for the homologous chromosomes the assemblies have same strand? You can try plotting a dotplot using [fixchr](https://github.com/schneebergerlab/fixchr) to check that.

**Comment by lifannn11** [comment]
> Hi @lifannn11, This issue is typically caused when the genomes have different strands for homologous chromosomes (#48). Have you checked whether for the homologous chromosomes the assemblies have the same strand? You can try plotting a dotplot using [fixchr](https://github.com/schneebergerlab/fixchr) to check that.

Hi:
Here are three files generated by fixchr. Could you please check if there are any issues with them?
[homologous.pdf](https://github.com/user-attachments/files/15756512/homologous.pdf)
[newfixchr.homologous_strand_corrected.pdf](https://github.com/user-attachments/files/15756513/newfixchr.homologous_strand_corrected.pdf)
[newfixchr.input.pdf](https://github.com/user-attachments/files/15756514/newfixchr.input.pdf)

Thanks.

**Comment by mnshgl0110** [comment]
Hi @lifannn11. From the dotplots, it seem that the genomes are highly rearranged/diverged. As a result, fixchr could not orient them the chromosomes. All of the chromosomes look in correct orientation, except chr09. You can try reverse complementing Chr09 in the query genome manually and then realign and rerun syri.

**Comment by lifannn11** [comment]
> Hi @lifannn11. From the dotplots, it seem that the genomes are highly rearranged/diverged. As a result, fixchr could not orient them the chromosomes. All of the chromosomes look in correct orientation, except chr09. You can try reverse complementing Chr09 in the query genome manually and then realign and rerun syri.

Hi;
Thank you for your solution, I've solved the problem, but how should I change it if the result of fixchr is like this?
[homologous.pdf](https://github.com/user-attachments/files/15881193/homologous.pdf)
[new2fixchr.homologous_strand_corrected.pdf](https://github.com/user-attachments/files/15881194/new2fixchr.homologous_strand_corrected.pdf)
[new2fixchr.input.pdf](https://github.com/user-attachments/files/15881195/new2fixchr.input.pdf)
Thanks.

**Comment by hyBio** [comment]
If I want to compare more than 2 genomes at the same time, when they are inverted that means I need to run fixchr twice. Some chromosomes will be inverted twice. I don't think that using fixchr is a good solution.

**Comment by mnshgl0110** [comment]
@hyBio  Please start a new issue for questions that are not related to the original posts. `fixchr` inverts only the query genomes. So, aligning multiple genomes to a reference genome and then running fixchr should orient all chromosomes.

**Comment by mnshgl0110** [comment]
@lifannn11 I am not sure I understand your question. If you are unsure how to interpret dotplots, then maybe read some guides present online (like this: https://omicstutorials.com/interpreting-dot-plot-bioinformatics-with-an-example/). In the dotplots generated by fixchr, the alignments near the bottom-left to top-right diagonal corresponds to syntenic/directed alignments, while those near the top-left to bottom-right diagonals are inverted.
