### ISSUE TITLE
SYRI:IndexError: list index out of range

### ISSUE THREAD

**Issue by lifannn11** [schneebergerlab/syri#255]
Hi:
When I run syri, some of them can successfully run, but some encounter a problem. I've tried for a long time but still can't solve it. Does anyone know how to fix it?
![image](https://github.com/schneebergerlab/syri/assets/166804257/8d4c2177-c5c9-4f2e-9e42-adea868f6ef9)
Thanks,
LIli

**Comment by lrauschning** [comment]
Seems to be a duplicate of #254 ?
