### ISSUE TITLE
how to merge SyRI vcfs

### ISSUE THREAD

**Issue by ChuanzhengWei** [schneebergerlab/syri#256]
Hi，
SyRI is a very useful tool. I recently used SyRI to obtain about 60 VCF files. I attempted to forcibly merge them using the bcftools merge command but failed because bcftools does not support VCF version 4.3. 
Although I can change the VCF file version, I am also unsure whether bcftools is suitable for merging SyRI outputs. 
For merging outputs from SyRI, what method would you recommend? Would you suggest isolating different variant types before merging?

I look forward to your reply！
thank you.

**Comment by mnshgl0110** [comment]
Hi @ChuanzhengWei, indeed merging VCFs with complex structural rearrangements as identified by syri is not easy and I am unaware of a method that does that efficiently and correctly. You can fetch SNPs/Indels and then try merging those using bcftools. For larger variants, you can consider fetching them and use some heuristics to merge them. Unfortunately, this will require some scripting.

**Comment by ChuanzhengWei** [comment]
Thanks for your reply, I think I know how to do it.
