### ISSUE TITLE
Questions about 'NOTAL'

### ISSUE THREAD

**Issue by ChuanzhengWei** [schneebergerlab/syri#257]
Hi,
In the manual, you define 'NOTAL' as 'Un-aligned region', but when I use igv to visualize these regions, I found that it is not completely unaligned, but there are a large number of SNPs, and this situation is very common. Some screenshots are placed below for display. I want to know if this is normal? Or are there any ways to improve this situation? This is my code.
```
refgenome=HYZ.TCJ.fasta
qrygenome=353.chr.fasta
minimap2 -ax asm5 -t 32 --eqx ${refgenome} ${qrygenome}> HYZ_353.sam
```
syri -c HYZ_353.sam -r ${refgenome} -q ${qrygenome} -F S --prefix HYZ_353

Chr02	18345492	18384552	-	-	-	-	-	NOTAL129	-	NOTAL	-
![微信截图_20240613094246](https://github.com/schneebergerlab/syri/assets/137666181/f94fc0b5-8fc6-4e5c-a097-082874e8331d)

Chr09	43760031	44558535	-	-	-	-	-	NOTAL954	-	NOTAL	-
![微信截图_20240613094454](https://github.com/schneebergerlab/syri/assets/137666181/98d31c6b-c910-4845-abfa-45af78adb8f0)

Chr07	39308549	39722542	-	-	-	-	-	NOTAL726	-	NOTAL	-
![微信截图_20240613095701](https://github.com/schneebergerlab/syri/assets/137666181/77c30ae4-e8cc-4b79-9ac1-9ea354ea5d34)

Please give me some suggestions, thanks!

**Comment by mnshgl0110** [comment]
By default, syri filters out small alignments or alignment with low alignment identity. As a result, these alignments would be filtered out resulting in NOTAL. Using `-f` makes syri use the full list of alignments (without any filtering).

**Comment by ChuanzhengWei** [comment]
Thank you!
