### ISSUE TITLE
Question about output

### ISSUE THREAD

**Issue by mylena-s** [schneebergerlab/syri#258]
Hello!
thanks for developing this software, I used it in the past and was working perfectly.

I have a question regarding the output of the new version of the software.
I am running v.1.7 and I cant find the old output "syri.out" nor I understand how to plot the results.

the command I used:
minimap2 -ax asm5 --eqx refgenome qrygenom | samtools sort -O BAM - > out.bam #works ok

syri -r reference.fasta -q query.fasta -c alignment.bam -F B

both genomes and their alignemnt contain all chr (24 in this case). I get 6 files per chr named as following:

Chr16_dupOut.txt     Chr16_invDupOut.txt  Chr16_invOut.txt     Chr16_invTLOut.txt   Chr16_synOut.txt     Chr16_TLOut.txt    

while I was expecting only 1 "syri.filtered.out" to be able to plot it with the standard plotsr parameter:
plotsr --sr syri.filtered.out  --genomes genomes.txt
or 
plotsr syri.filtered.out refgenome qrygenome -H 8 -W 5 (following https://schneebergerlab.github.io/syri/pipeline.html)

I am sorry if the answer of this question is too obvious, but I could not decipher what is happening.

Thank you in advance!

**Comment by lorenalorenzo** [comment]
Hi! Sorry if this issue has been solved but I am facing exactly the same and I didn't found here anything about that. I really don't know how should I use every output for plotting. Did you manage to do it? 

Thanks in advance!

**Comment by mylena-s** [comment]
Hi!

I sincerely don't remember how i solved that time, but I am almost sure that there was something wrong with my input that was crashing the run. I had this error several times and most of the times the problem was that I was comparing different strands of one of the chromosomes or different number of chromosomes. I usually solve it by verifying homology and orientation before running syri with dgenies or fixchr..

I hope it helps, cheers

**Comment by lorenalorenzo** [comment]
Hi! Many many thanks for your reply. Maybe using the reference fasta with all chromosome and non-chromosome level scaffolds confound the analysis?? Because the aligned bam only considers chromosomes... Anyway, I will check everything then, I hope to make it work!
Cheers
