### ISSUE TITLE
How about make the figure based on the results!

### ISSUE THREAD

**Issue by sunnycqcn** [schneebergerlab/syri#26]
Hello,
I still can not understand how to make figure based on the results. Or what is the format of results?
Could you help me figure out it or do you update this function?
Thanks,
Fuyou

**Comment by mnshgl0110** [comment]
Hi Fuyou,
There is some information describing the output file format here: https://schneebergerlab.github.io/syri/fileformat.html
In case you have not read it, then I would suggest to give it a look. Please feel free to ask more questions, if any.
Best
Manish

**Comment by sunnycqcn** [comment]
Hello Manish,
I am much appreciated for your replying so fast. I have read the information. I also read your paper about syri. If I want to make a figure, which will I should do?
By the way, I met a other problem about with different scaffold-number. I set the parameter --no-chrmatch. However, I still met this issue. But I get good results with the same scaffold genome.
syri - WARNING - starting
Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - ERROR - Unequal number of chromosomes in the genomes. Exiting
syri - WARNING - starting
Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - WARNING - --no-chrmatch is set. Not matching chromosomes automatically.
Reading Coords - WARNING - UNSE01000006.1, UNSE01000014.1, UNSE01000020.1, UNSE01000002.1, UNSE01000021.1, UNSE01000023.1, UNSE01000007.1, UNSE01000010.1, UNSE01000025.1, UNSE01000012.1, UNSE01000008.1, UNSE01000019.1, UNSE01000026.1, UNSE01000016.1, UNSE01000032.1, UNSE01000009.1, UNSE01000004.1, UNSE01000003.1, UNSE01000018.1, UNSE01000001.1, UNSE01000011.1, UNSE01000013.1, UNSE01000005.1, UNSE01000024.1, UNSE01000015.1, UNSE01000017.1, UNSE01000022.1, UNSE01000033.1, UNSE01000031.1, UNSE01000028.1, scaffold00012, scaffold00011, scaffold00008, scaffold00001, scaffold00015, scaffold00016, scaffold00020, scaffold00005, scaffold00006, scaffold00004, scaffold00002, scaffold00014, scaffold00009, scaffold00013, scaffold00007, scaffold00018, scaffold00017, scaffold00010, scaffold00019, scaffold00003 present in only one genome. Removing corresponding alignments
Traceback (most recent call last):
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/syri/syri/bin/syri", line 128, in <module>
    chrlink = startSyri(args)
  File "syri/pyxFiles/synsearchFunctions.pyx", line 319, in syri.pyxFiles.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 728, in syri.pyxFiles.synsearchFunctions.outSyn
  File "/home/AAFC-AAC/fuf/miniconda3/envs/genome/lib/python3.5/site-packages/pandas/core/generic.py", line 4389, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/AAFC-AAC/fuf/miniconda3/envs/genome/lib/python3.5/site-packages/pandas/core/generic.py", line 646, in _set_axis
    self._data.set_axis(axis, labels)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/genome/lib/python3.5/site-packages/pandas/core/internals.py", line 3323, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 0 elements, new values have 7 elements

Thanks,
Fuyou

**Comment by mnshgl0110** [comment]
Hi Fuyou,

Could you please provide more information about what kind of plot do you require? In the syri output file (tsv), each row represents a genomic feature. So depending on which features you want in figure you can select them based on Column11.

Syri was designed using chromosomes in mind, so it provides best result for them. If you are comparing your assembly against a chromosome-level reference genome, then you can generate homology-based pseudo-chromosome level assembly (using tools like ntjoin, ragoo etc). And then use this assembly as a query genome (after selecting pseudo-chromosomes and removing unplaced contigs/scaffolds). If the reference genome is also incomplete, then you can use chroder to generate pseudo-chromosome like molecules by concatenating scaffolds in both reference and query genomes. In summary, SyRI expects that the two genomes consists of homologous DNA molecules (ideally with same ids) and that is best done with chromosomes.

Also, using --no-chrmatch stops syri from trying to match chromosome ids. Use this only when the chromosome IDs in the genomes are exactly matching.

Best
Manish

**Comment by sunnycqcn** [comment]
Hello Manish,
Thanks for your suggestions. I will figure out what I need. Then if I still have some problem, I will let you give me more suggestions.
I am much appreciated for your work.
Best,
Fuyou

**Comment by sunnycqcn** [comment]
Hello Manish,
I checked my results. I always can not get TSV format results. The error is as following:
syri - WARNING - starting
Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/miniconda3/envs/genome/bin/syri", line 192, in <module>
    getTSV(args.dir, args.prefix, args.ref.name)
  File "syri/pyxFiles/writeout.pyx", line 396, in syri.writeout.getTSV
  File "syri/pyxFiles/writeout.pyx", line 106, in syri.writeout.extractseq
  File "/home/AAFC-AAC/fuf/miniconda3/envs/genome/lib/python3.5/site-packages/Bio/Seq.py", line 250, in __getitem__
    return self._data[index]
IndexError: string index out of range
Then I checked my syri install and reinstalled
I found the error is as following:
gcc: error: unrecognized command line option ‘-fno-plt’ ays 
In fact, I met this error when I installed syri the first time. 
This error looks the gcc version is not correct.
Could you tell me which gcc version is correct for syri? I installed syri in conda environment. 
Thanks,
Fuyou

**Comment by sunnycqcn** [comment]
Hello Manish,
I have installed syri again. I did not met any error. However, I still met the error is as following with two genomes.
syri - WARNING - starting
Traceback (most recent call last):
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/syri/syri/bin/syri", line 192, in <module>
    getTSV(args.dir, args.prefix, args.ref.name)
  File "syri/pyxFiles/writeout.pyx", line 396, in syri.writeout.getTSV
  File "syri/pyxFiles/writeout.pyx", line 106, in syri.writeout.extractseq
  File "/home/AAFC-AAC/fuf/miniconda3/envs/syri/lib/python3.5/site-packages/Bio/Seq.py", line 250, in __getitem__
    return self._data[index]
IndexError: string index out of range
The results directory is as following:
(syri) [fuf@biocluster test]$ ls -ltrh pairwiseWGA/L022/LREF
total 11M
-rwxr-xr-x 1 fuf domain users 1004 Mar 11 18:09 LREF.L022invOut.txt
-rwxr-xr-x 1 fuf domain users 1.1K Mar 11 18:09 LREF.L022TLOut.txt
-rwxr-xr-x 1 fuf domain users  364 Mar 11 18:09 LREF.L022invTLOut.txt
-rwxr-xr-x 1 fuf domain users  12K Mar 11 18:09 LREF.L022dupOut.txt
-rwxr-xr-x 1 fuf domain users 3.4K Mar 11 18:09 LREF.L022invDupOut.txt
-rwxr-xr-x 1 fuf domain users  41K Mar 11 18:09 LREF.L022ctxOut.txt
-rwxr-xr-x 1 fuf domain users  99K Mar 11 18:09 LREF.L022synOut.txt
-rwxr-xr-x 1 fuf domain users 178K Mar 11 18:09 LREF.L022sv.txt
-rwxr-xr-x 1 fuf domain users  38K Mar 11 18:09 LREF.L022notAligned.txt
-rwxr-xr-x 1 fuf domain users 7.3M Mar 11 18:09 LREF.L022snps.txt

#####################################
I met other errors as following with other two genomes.
syri - WARNING - starting
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/miniconda3/envs/syri/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/AAFC-AAC/fuf/miniconda3/envs/syri/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "syri/pyxFiles/synsearchFunctions.pyx", line 359, in syri.pyxFiles.synsearchFunctions.syri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 697, in syri.pyxFiles.synsearchFunctions.getSynPath
ValueError: max() arg is an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/syri/syri/bin/syri", line 128, in <module>
    chrlink = startSyri(args)
  File "syri/pyxFiles/synsearchFunctions.pyx", line 308, in syri.pyxFiles.synsearchFunctions.startSyri
  File "syri/pyxFiles/synsearchFunctions.pyx", line 309, in syri.pyxFiles.synsearchFunctions.startSyri
  File "/home/AAFC-AAC/fuf/miniconda3/envs/syri/lib/python3.5/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/AAFC-AAC/fuf/miniconda3/envs/syri/lib/python3.5/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: max() arg is an empty sequence
**This results directory file is empty.**
I did not know what it is the reason.
In fact, all genome assembly were used the same methods with 45Mb size.
Thanks,
Fuyou

**Comment by mnshgl0110** [comment]
Hi,
The first error is weird. ```IndexError: string index out of range``` implies that there are alignments longer than the chromosome size. Could you please check the chromosome IDs and lengths in the input genomes and the alignments for consistency. This seems to be an input issue.
The second error is expected as there are scaffolds without any directed alignments (for example: scaffold00006, scaffold00008, scaffold00009 etc all have 0 forward alignments and hence, no syntenic regions can be identified). As I mentioned earlier, syri was designed using chromosome level assemblies in mind, so it expects that large portion of the homologous chromosomes would be syntenic. I would suggest that you filter out unplaced contigs and scaffolds and compare only large homologous sequences.
Best
Manish

**Comment by mnshgl0110** [comment]
Hi Fuyou,
Have you checked the chromosomes whether they have the same strand in the two genomes? If for same chromosome, the two assemblies have different strands then most of the alignments would be inverted. In highly conserved chromosomes, this could result in absence of any directed alignment. I wonder, whether this is the reason that there are six scaffolds that do not have any directed alignment with their homologous counterpart. To check for this, you can check the alignments of the scaffolds, and if you see only (majority) inverted alignments between homologous sequences, then probably they are from different strands. Reversing complementing one of the sequence (and then re-aligning) would solve this issue.
Could you please also tell me the length of these twenty molecules analysed here? That might give some hints about how to solve this problem.
Best
Manish

**Comment by sunnycqcn** [comment]
Hello Manish,
You are right. Some chromosome is inverted with reference genome.
I am thinking how to fix it. Because I have about 160 isolate's genome sequence, they assembled based on one reference genome.
Thanks,
Fuyou

**Comment by mnshgl0110** [comment]
Do you know which chromosomes are inverted? If yes, then you can use this https://github.com/schneebergerlab/syri/blob/master/syri/bin/chrrev.py script to generate reverse_complemented genomes.

**Comment by sunnycqcn** [comment]
Only can this one do one scaffold or whole genomes? If only is one, I can do it. I will check it.
Thanks,
