### ISSUE TITLE
Merging the bonobo chromosomes and then identifying structural variations with human chromosomes

### ISSUE THREAD

**Issue by leiwang567** [schneebergerlab/syri#268]
Hello, thank you for taking the time out of your busy schedule to respond to my inquiries. I have to admit that SyRI is a very efficient software for detecting structural variations. Now, I would like to use SyRI to identify structural variations between the chromosomes of primates, such as between humans and their close relatives, bonobos. However, during the evolutionary process, human chromosomes have undergone fusion compared to other primates. Ultimately, humans have 22 autosomes and XY sex chromosomes, while bonobos have 23 autosomes and XY sex chromosomes. Since SyRI requires the input of the same number of chromosomes for the two species and that they be homologous, I used TBtools to identify the homologous chromosome numbers between humans and bonobos and found that human chromosome 2 corresponds to bonobo chromosomes 12 and 13, a result that is also supported by literature. Based on this, I took the human genome as the reference genome and manually merged bonobo chromosomes 12 and 13 into one chromosome. I then used minimap2 and SyRI to identify structural variations between these two species and obtained good results. As I am inexperienced in this area, I am not quite sure if the method I described above is feasible and would like to hear your opinion.
![340944fb-74de-4c94-a1f7-e94f295266f9](https://github.com/user-attachments/assets/3230203f-713d-429e-99eb-9b06c5b02365)
![hum-panpan](https://github.com/user-attachments/assets/f56aaa40-3719-4ead-8839-888bf5d9225b)

**Comment by mnshgl0110** [comment]
Hi. Your approach is correct. I would assume that the null hypothesis is that the difference between Human:Chr2 and Bonobo:Chr12-Chr13 is one chromosome fission. This would mean that the Chr2 and Chr12+Chr13 should be mostly syntenic.
I am assuming that currently you concatenated Chr12+Chr13 and that the Chr12 is annotated as large inverted translocation and Chr13 is annotated as syntenic. You can probably improve this by concatenating Chr13 + reverse_compemented_Chr12.

**Comment by leiwang567** [comment]
I greatly appreciate your response, and I believe your suggestions are spot on. I have now concatenated the chimpanzee chromosome 13 (chr13) with the reverse complement of chromosome 12 (chr12) for the identification of structural variations (SVs). I currently have a query regarding the next steps: I need to assess which genes might be affected by the identified SVs, essentially annotating these SVs. Could you advise on the aspects I should consider or recommend any software and tools that could assist me in this process?

**Comment by mnshgl0110** [comment]
Unfortunately, from the top of my head I cannot recall tools for this, but I assume there would be some tools doing this. Basically you want something like SNPEff for SVs.
As the original issue is resolved now, I will close this.
