### ISSUE TITLE
Could syri plot local SVs？

### ISSUE THREAD

**Issue by Simple53** [schneebergerlab/syri#270]
Hi，I am courious whether syri could plot a zoom in version of local SVs in specific chromosomal region？Thanks.
![image](https://github.com/user-attachments/assets/afdf6b88-cfde-4601-9d7c-b16caadb021a)

**Comment by mnshgl0110** [comment]
Hi. Currently, there is no easy way to do this. You can try [plotsr](https://github.com/schneebergerlab/plotsr) with a markers.bed file but for very zoomed in views that might look weird.

**Comment by Simple53** [comment]
Ok, I will try. Thanks!
