### ISSUE TITLE
ImportError syri.pixFiles

### ISSUE THREAD

**Issue by aderzelle** [schneebergerlab/syri#32]
Hello,

trying to run syri  

```
./syri/syri/bin/syri -c out_m_i90_l100.coords -r ref.fasta -q contigs_k61.fa -d out_m_i90_l100.delta
```
but

```
Traceback (most recent call last):
  File "./syri/syri/bin/syri", line 148, in <module>
    from syri.pyxFiles.synsearchFunctions import readCoords
ImportError: No module named 'syri.pyxFiles'
```

thank you

**Comment by mnshgl0110** [comment]
Hi. It could be because syri is not installed properly. Please checkout the installation guide here: https://schneebergerlab.github.io/syri/install.html
Also, try using the following command: ```python3 ./syri/syri/bin/syri -c out_m_i90_l100.coords -r ref.fasta -q contigs_k61.fa -d out_m_i90_l100.delta```

**Comment by bitezhu** [comment]
> 
> 
> Hi. It could be because syri is not installed properly. Please checkout the installation guide here: https://schneebergerlab.github.io/syri/install.html
> Also, try using the following command: `python3 ./syri/syri/bin/syri -c out_m_i90_l100.coords -r ref.fasta -q contigs_k61.fa -d out_m_i90_l100.delta`

hi,  I met the same problem. But I did follow the instruction on the web page, everything went well. And also I set the PYTHONPATH, but stiil I got "ImportError" error message as follow.
`python3 ~/toolkit/syri/syri/bin/syri -c out.filtered.coords -d out.filtered.delta -r refgenome -q qrygenome
Traceback (most recent call last):
  File "./toolkit/syri/syri/bin/syri", line 148, in <module>
    from syri.pyxFiles.synsearchFunctions import readCoords
ImportError: No module named 'syri.pyxFiles.
`
I'm using python3.5.

**Comment by mnshgl0110** [comment]
Hi. This is a bit weird and as of now I am not sure why this could be happening. Can you please run this `python setup.py install > install.out 2> install.out` and share the install.out file, I would like to see if there is anything that might have not worked while installing. Few checks that I could think of:
1) Check that same python interpreter is being used for installing and running.
2) That you have write permission and you can install packages.
3) Search for the `site-packages` folder (https://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory) for your python and check if syri folder is in there. Inside this, are there different .so files? Specifically, you are looking for a file like `...../site-packages/syri-0.0.0-py3.5-linux-x86_64.egg/syri/pyxFiles/synsearchFunctions.cpython-35m-x86_64-linux-gnu.so' `.
4) If this file exists, then you can check whether you can load the package by opening a python console and using
```
import syri.pyxFiles.synsearchFunctions
from syri.pyxFiles.synsearchFunctions import readCoords
```
If the above commands work without error, then it would mean that syri is installed properly and there is something else that is not working.
Also, which operating system are you trying to use SyRI on?

**Comment by bitezhu** [comment]
Thanks for replying so soon! I just create a new conda environment, install all the python packages required, plus upgrade gcc4.8 to gcc7.1. Somehow it workd out! I‘m totally confused too.

**Comment by mnshgl0110** [comment]
Well, as long as it works. Thanks for letting me know. All the best.
