### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by jigaoxiang** [schneebergerlab/syri#33]
When i try syri using the *.sam(from minimap2) as an input file, there are some things wrong:
this is my code : 
                python3 ../syri/bin/syri -c out.bam -r refgenome -q qrygenome -k -F B
And then, there are somethings wrong, as follow:
Traceback (most recent call last):
  File "syri/pyxFiles/synsearchFunctions.pyx", line 155, in syri.pyxFiles.synsearchFunctions.readCoords
  File "syri/pyxFiles/synsearchFunctions.pyx", line 34, in syri.pyxFiles.synsearchFunctions.readSAMBAM
  File "/home/jgxiang/miniconda2/envs/py35/lib/python3.5/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../syri/bin/syri", line 153, in <module>
    coords, chrlink = readCoords(args.infile.name, args.chrmatch, args.dir, args.prefix, args, args.cigar)
  File "syri/pyxFiles/synsearchFunctions.pyx", line 157, in syri.pyxFiles.synsearchFunctions.readCoords
TypeError: Can't convert 'ImportError' object to str implicitly

**Comment by mnshgl0110** [comment]
Hi. It seems that one of the libraries (pysam) is not installed properly. Could you please try to reinstall it? Please check this: https://schneebergerlab.github.io/syri/install.html
Also, you can try running this test_example to check whether SyRI is correctly installed and running: https://schneebergerlab.github.io/syri/pipeline.html

**Comment by jigaoxiang** [comment]
Thank you for answer, but there are still some problem. I think the "pysam" was installed properly because When I try reinstall "pysam", there are some infomations about this:
conda install -c bioconda pysam
Collecting package metadata (current_repodata.json): done
Solving environment: done
# All requested packages already installed.
Yes, I also try example by "bash pipeline.sh",producing some results like "syri.vcf" and "syri.out". However, when I try "python3 ../syri/bin/syri -c out.sam -r refgenome -q qrygenome -k -F S", some wrong happened like what I described above. What make me more confused is when I try "python3 ../syri/bin/syri -c out.filtered.coords -d out.filtered.delta -r refgenome -q qrygenome", it work well. So I am not sure the SyRI install correctly. Maybe the results that named "syri.vcf" and "syri.out" were produced by the second code?

**Comment by jigaoxiang** [comment]
Thank you for answer, but there are still some problem. I think the "pysam" was installed properly because When I try reinstall "pysam", there are some infomations about this:
conda install -c bioconda pysam
Collecting package metadata (current_repodata.json): done
Solving environment: done
# All requested packages already installed.
Yes, I also try example by "bash pipeline.sh",producing some results like "syri.vcf" and "syri.out". However, when I try "python3 ../syri/bin/syri -c out.sam -r refgenome -q qrygenome -k -F S", some wrong happened like what I described above. What make me more confused is when I try "python3 ../syri/bin/syri -c out.filtered.coords -d out.filtered.delta -r refgenome -q qrygenome", it work well. So I am not sure the SyRI install correctly. Maybe the results that named "syri.vcf" and "syri.out" were produced by the second code?

**Comment by mnshgl0110** [comment]
Pysam is a python library that is used to read SAM/BAM file. So, when a table input is provided then pysam is not used and you were able to get output. This again suggests that this is a pysam issue. Did you install pysam now or was it installed on your system from earlier? There is some information here https://github.com/ContinuumIO/anaconda-issues/issues/2441 suggesting that this conda be a conda environment issue. Maybe you can try deleting the currently installed pysam and reinstall it. You can test whether pysam is correctly installed like this:
```
import pysam
samfile = pysam.AlignmentFile("ex1.bam", "rb")
```

**Comment by jigaoxiang** [comment]
Thank you very much！I deal with it using the link you give me. what I use is 
“conda install --override-channels -c conda-forge bzip2”
And then, I try below again. It working
python3 ../syri/bin/syri -c out.sam -r refgenome -q qrygenome -k -F S
That is useful. Thank  you again!

**Comment by jigaoxiang** [comment]
this another probelm meaning my refernce_id are too many?
reference_id -1 out of range 0<=tid<360

**Comment by mnshgl0110** [comment]
Can you please provide the full error message?

**Comment by jigaoxiang** [comment]
Yes, this is the full error message:
Reading BAM/SAM file - ERROR - Error in reading BAM/SAM file. reference_id -1 out of range 0<=tid<360

**Comment by jigaoxiang** [comment]
I also used numcer to attempt to get different inputfile for Syri, But this code take a long time:
"nucmer --maxmatch -c 100 -b 500 -l 50 refgenome qrygenome"
Actually, it is not finshed frome yesterday afternoon to now.
nucmer --maxmatch -c 100 -b 500 -l 50 refgenome qrygenome
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
# reading input file "out.ntref" of length 630729870
# construct suffix tree for sequence of length 630729870
# (maximum reference length is 2305843009213693948)
# (maximum query length is 18446744073709551615)
# process 6307298 characters per dot
#....................................................................................................
# CONSTRUCTIONTIME /home/jgxiang/software/MUMmer3.23/mummer out.ntref 656.58
# reading input file "/home/jgxiang/software/syri/example/BolHDEMvs013_ref/qrygenome" of length 554977188
# matching query-file "/home/jgxiang/software/syri/example/BolHDEMvs013_ref/qrygenome"
# against subject-file "out.ntref"
nucmer --maxmatch -c 100 -b 500 -l 50 refgenome qrygenome
COMPLETETIME /home/jgxiang/software/MUMmer3.23/mummer out.ntref 3648.82
# SPACE /home/jgxiang/software/MUMmer3.23/mummer out.ntref 1149.63
4: FINISHING DATA

**Comment by mnshgl0110** [comment]
I am not sure why you are getting this error message. Can you please share the syri.log file? That might have some information. Also, please ensure that your input SAM/BAM file is correct.
Regarding nucmer, it generates whole-genome alignments, and that can take time. Please read about it. You can try to change -c, -l, and -b parameters to make the alignment less sensitive which will make it finish quicker. http://mummer.sourceforge.net/manual/#nucmer

**Comment by jigaoxiang** [comment]
That is syri.log file
2020-05-17 09:52:56,870 - Reading Coords - INFO - <module>:153 - Reading input from SAM file
2020-05-17 09:55:00,917 - Reading BAM/SAM file - ERROR - <module>:153 - Error in reading BAM/SAM file. reference_id -1 out of range 0<=tid<360

**Comment by mnshgl0110** [comment]
Nothing informative here. Have you ensured that your alignment input file is correct? How big is it? Would it be possible for you to share it?

**Comment by jigaoxiang** [comment]
I think the inputfile is correct, which I get from minimap2 using "minimap2 -ax asm5 --eqx refgenome qrygenome > out.sam" .And the bam file is 12G. It is too big to share it with you.

**Comment by mnshgl0110** [comment]
Can you try to run SyRI on a subset of alignments? Try to select the first 1000 alignments and try to run SyRI with them. If you still get the same error, then you can share that smaller file. And if the smaller file do not give this error, then we would know that there is something else in the alignments that is resulting in this error.
Also, how many chromosomes are there in your species of interest? You can try to analyse single homologous chromosomes (ref.fasta contains only 1 chromosome, qry.fasta contains the corresponding homologous chromosome) and see if that works.

**Comment by jigaoxiang** [comment]
I removed all contig of my genomic sequence, only chromosomes were retained. And I rename the chromosome ID to the same name of each homologous chromosome. Then syri worked well. Thank you for your patience and kind. Best wished for you and your family.

**Comment by mnshgl0110** [comment]
Good to know that you were able to resolve the issue. All the best.
