### ISSUE TITLE
Analysing split and fusion genomes.

### ISSUE THREAD

**Issue by mnshgl0110** [schneebergerlab/syri#35]
What if my species' chromosome have undergone split and fission？How should I use SyRI, or just the one-to-one synteny chromosme?
![image](https://user-images.githubusercontent.com/20680150/82707967-bcdc8580-9caf-11ea-898f-cb93254b5c98.png)

_Originally posted by @baozg in https://github.com/schneebergerlab/syri/issues/34#issuecomment-632901642_

**Comment by mnshgl0110** [comment]
The pre-requisite is to have a one-to-one mapping between chromosomes. So, in such cases, you would want to concatenate chromosomes in one genome that together represent one larger chromosome in the other sample. For example, you would want to concatenate the 7th and the 14th chromosome in the lower genome. Similarly, chromosome 11 and 9 in the upper genome and chromosome 8 and 15 in the lower genome can be combined as well. However, it is important to remember that based on how you concatenate these chromosomes, you can get different rearrangements. So, here I would imagine that the Chr7 in the lower genome would need to be first reverse complemented and then concatenated to Chr14, otherwise it would just be annotated as one large inversion.

**Comment by baozg** [comment]
Thanks. I think I can reverse complemented the Chr7 and add 10k N between Chr7 and Chr14 to get a better annotation for SVs.

**Comment by baozg** [comment]
It works.
![image](https://user-images.githubusercontent.com/20680150/82753686-2072ca00-9dfa-11ea-9614-cd97fe3ca93c.png)

**Comment by mnshgl0110** [comment]
Great.
