### ISSUE TITLE
nucmer readCoords() takes at most 5 positional arguments (6 given)

### ISSUE THREAD

**Issue by yanqingwangxiuhua** [schneebergerlab/syri#36]
[out.filtered.coords.txt](https://github.com/schneebergerlab/syri/files/4686307/out.filtered.coords.txt)
Hello，
I have a small questions for the coords file by MUMmer3.23. I used the example for test. So I append the example coords. But I have an error : File "../syri/bin/syri", line 153, in <module>
    coords, chrlink = readCoords(args.infile.name, args.chrmatch, args.dir, args.prefix, args, args.cigar)
  File "syri/pyxFiles/synsearchFunctions.pyx", line 31, in syri.pyxFiles.synsearchFunctions.readCoords
TypeError: readCoords() takes at most 5 positional arguments (6 given).
I do need your help, please.
Hope to receive your answers. Thank you very much.

**Comment by mnshgl0110** [comment]
Hi. It could happen when a newer `../syri/bin/syri` is being used with an older installation of SyRI. Probably, something weird is happening in your current working python environment. Can you please try to install SyRI in a fresh environment? I would assume that would solve the issue.

**Comment by yanqingwangxiuhua** [comment]
Yes, I nstall SyRI in a fresh environment and the problem solved.  Thank you very much. Thank you! 
Best wishes!
