### ISSUE TITLE
failure to enter to the last step - Combining outputs

### ISSUE THREAD

**Issue by liu3zhenlab** [schneebergerlab/syri#38]
"snps.txt" was produced but no log report about "Combining outputs". Everything else looks fine. I use conda installation in CentOS Linux 7. Appreciate your guide to solve the problem. Thanks.

Below is the error:

~/.conda/envs/syri/lib/python3.5/site-packages/pandas/core/ops.py:1167: FutureWarning: elementwise comparison failed; returning scalar instead, 
but in the future will perform elementwise comparison
  result = method(y)
Traceback (most recent call last):
  File "~/software/syri/syri/bin/syri", line 255, in <module>
    getshv(args, coords, chrlink)
  File "syri/pyxFiles/findshv.pyx", line 196, in syri.findshv.getshv
  File "~/.conda/envs/syri/lib/python3.5/site-packages/pandas/core/ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "~/.conda/envs/syri/lib/python3.5/site-packages/pandas/core/ops.py", line 1169, in na_op
    raise TypeError("invalid type comparison")
TypeError: invalid type comparison

**Comment by mnshgl0110** [comment]
Hi Sanzhen,

What version of pandas are you using? As of now I would guess that this is a pandas version issue. You could refer to the installation guide [here](https://schneebergerlab.github.io/syri/install.html) to try and reinstall SyRI. You could also try creating a new python virtual environment and install syri there.

If the problem persists, then could you please run syri with the DEBUG mode and share the syri.log file? Also, it would be helpful to see the snps.txt file.

Best
Manish

**Comment by liu3zhenlab** [comment]
pandas version is 0.23.4. Is this the right version?

I skipped snp/indel calling using --nosnp but the final combination step had an error as well.

getTSV - ERROR - Error in finding parent for SV
Traceback (most recent call last):
  File "/homes/liu3zhen/software/syri/syri/bin/syri", line 269, in <module>
    getTSV(args.dir, args.prefix, args.ref.name)
  File "syri/pyxFiles/writeout.pyx", line 152, in syri.writeout.getTSV
AttributeError: 'Pandas' object has no attribute 'to_string'

**Comment by liu3zhenlab** [comment]
```
wc -l snps.txt 
```
23062458 snps.txt
```
head snps.txt
```
686	C	.	18753100	20	686	26	1	1	1	1	1
706	A	G	18753120	20	706	26	1	1	1	1	1
760	A	.	18753173	54	760	26	1	1	1	1	1
866	.	G	18753280	36	866	27	1	1	1	1	1
900	C	.	156185066	1	900	28	1	1	1	1	7
901	G	.	156185066	1	901	28	1	1	1	1	7
902	A	.	18753315	1	902	28	1	1	1	1	1
902	A	.	156185066	1	902	28	1	1	1	1	7
903	C	.	18753315	1	903	28	1	1	1	1	1
938	C	T	156185102	36	938	28	1	1	1	1	7

```
tail snps.txt 
```
159769419	G	C	116433981	1	364	0	6	1	-1	9	9
159769437	T	C	116433963	18	346	0	6	1	-1	9	9
159769556	A	G	116433844	24	227	0	6	1	-1	9	9
159769580	.	T	116433819	24	203	0	6	1	-1	9	9
159769617	T	G	116433782	24	166	0	6	1	-1	9	9
159769641	C	A	116433758	24	142	0	6	1	-1	9	9
159769676	T	G	116433723	8	107	0	6	1	-1	9	9
159769684	A	G	116433715	2	99	0	6	1	-1	9	9
159769686	.	A	116433712	2	97	0	6	1	-1	9	9
159769722	A	G	116433676	36	61	0	6	1	-1	9	9

**Comment by liu3zhenlab** [comment]
seems that chromosome ID in the snps.txt are not correct.

**Comment by mnshgl0110** [comment]
I think this could be happening because chromosome IDs are integers. Changing chromosome ids to 'chr1', 'chr2' etc might resolve this issue.

**Comment by liu3zhenlab** [comment]
Thank Manish. I will try as you suggested.

**Comment by liu3zhenlab** [comment]
Hi Manish,
I used the following commands to modify sequence names and the delta file. It ran successfully. Thank you very much for suggestions.
```
sed 's/^>\([0-9]\)/>chr\1/g'
sed 's/^>\([0-9]\{1,2\}\) \([0-9]\)/>chr\1 chr\2/g'
```
