### ISSUE TITLE
plotsr error

### ISSUE THREAD

**Issue by liu3zhenlab** [schneebergerlab/syri#39]
I was able to run syri successfully but plotsr returned an error. It would be nice to see how you visualize the result. Please help if you know the potential problem. Thanks.

Here is the code
```
plotsr -s 1000 -o pdf syri.out $ref $qry
```
Here is the error:

syri/lib/python3.5/site-packages/matplotlib/font_manager.py:229: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '
Traceback (most recent call last):
  File "syri/bin/plotsr", line 154, in <module>
    plt.switch_backend('Qt5Agg')
  File "syri/lib/python3.5/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'Qt5Agg' which requires the 'qt5' interactive framework, as 'headless' is currently running

**Comment by mnshgl0110** [comment]
Hi Sanzhen,

Are you trying to run this through a terminal or from something like Jupyter? There is some discussion about this error arising when trying to plot in Jupyter/Google Colab python environment. https://github.com/QuantEcon/MatchingMarkets.py/issues/1

So, I am wondering is the same thing happening here, or it is happening when you run this script directly from bash.

**Comment by liu3zhenlab** [comment]
plotsr was run in terminals. I have tested it in both CentOS and Ubuntu systems. Let me know if more information is needed.

**Comment by mnshgl0110** [comment]
Thanks for the information.

Could you please try to edit the plotsr script and change the line:
```
from matplotlib import pyplot as plt
```
to 
```
import matplotlib
matplotlib.use('Qt5Agg')
from matplotlib import pyplot as plt
```
Here, I just try to force matplotlib to use the correct plotting backend. Hopefully, it would work correctly after this. However, it is difficult to be sure as this seems to be an environment issue.

If this does not work, then could you also please try to open your python console and run:
```
import matplotlib
matplotlib.get_backend()
```
and let me know the output. Also, what version of matplotlib are you using?

**Comment by liu3zhenlab** [comment]
matplotlib 3.0.0 was used.

**Comment by mnshgl0110** [comment]
Did it work after adding those two lines?

**Comment by mnshgl0110** [comment]
And what was the output of `matplotlib.get_backend()`?

**Comment by liu3zhenlab** [comment]
'agg'

**Comment by liu3zhenlab** [comment]
I am working on that. Will update the result later.

**Comment by liu3zhenlab** [comment]
Not familiar with Python. some error occurred after modifying the script:

File "/homes/liu3zhen/software/syri/syri/bin/plotsr", line 155
    matplotlib.use('Qt5Agg')
                           ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by mnshgl0110** [comment]
Ok. In that case, please try with this version of plotsr https://github.com/schneebergerlab/syri/blob/V1.3/syri/bin/plotsr

**Comment by liu3zhenlab** [comment]
Thank Manish. But the problem remains.

Traceback (most recent call last):
  File "/homes/liu3zhen/software/syri/syri/bin/plotsr", line 156, in <module>
    plt.switch_backend('Qt5Agg')
  File "/homes/liu3zhen/.conda/envs/syri/lib/python3.5/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'Qt5Agg' which requires the 'qt5' interactive framework, as 'headless' is currently running

**Comment by mnshgl0110** [comment]
That's not good.
Maybe, the last thing to check would be to open a python console and run:
```
from matplotlib import pyplot as plt
plt.switch_backend('Qt5Agg')
```
I would expect that this would give the same error again. If so, then we can be sure that this is an environment issue. Maybe, you can also try deleting and reinstalling matplotlib.

Unfortunately, I am out of better ideas right now. I would try to find a solution and would let you know if I find something helpful.

**Comment by liu3zhenlab** [comment]
My lab member Ha Le suggested using "cario" rather than "Qt5Agg" as the matplotlib backend. It solved the problem. I have successfully produced the figure. Thanks a lot for your time and rapidly responses.

**Comment by mnshgl0110** [comment]
That's great. Thanks for sharing the solution.
