### ISSUE TITLE
0 length NOTAL

### ISSUE THREAD

**Issue by fergsc** [schneebergerlab/syri#43]
Hi, I have run syri sucessfully on a few genomes. I was looking into the sizes of the syri events in the .out file and noticed that I have some NOTAL that are 0 length.

eg.
```
Chr03   21182259        21182259        -       -       -       -       -       NOTAL425        -       NOTAL   -
```
thanks

**Comment by mnshgl0110** [comment]
The start and end bases are included in the annotation, i.e. this is a NOTAL of length 1bp  at position Chr03:21182259.

**Comment by fergsc** [comment]
Thanks, I should have realised that. Events include the numbered start and stop base.
