### ISSUE TITLE
What is HDR?

### ISSUE THREAD

**Issue by fergsc** [schneebergerlab/syri#44]
Hi, I have looked over your paper and sups and didn't see any definition of what a highly diverged region is. I was hoping you could help me in understanding how a HDR is defined.

thanks.

**Comment by mnshgl0110** [comment]
HDRs are defined in figure S8 in the supplementary material. Basically, they are regions with gaps in both genomes in-between two alignments of an annotation-block.

**Comment by fergsc** [comment]
Thanks, so they are regions that encompass {SYN - NOTAL - SYN} arrangements.

**Comment by mnshgl0110** [comment]
Not really.
SyRI first performs structural annotation of the genomes. Regions which are not aligned and are not part of any annotation block are called NOTAL. Within each annotation block, syri checks the overlaps and gaps between consecutive alignments (if any), and annotates sequence variations like CNVs, HDRs etc. The distinction between a NOTAL and HDR is that the HDRs have associated structural annotation (for example: a HDR within an overall syntenic/translocated region), whereas no structural annotation is possible for the NOTAL regions as they are unique to the genomes.
Please see the attached figure for a graphical description. 
![hdr_vs_notal](https://user-images.githubusercontent.com/16225647/90002704-4e4a0b00-dc93-11ea-825f-74fb6dedafa6.png)
