### ISSUE TITLE
chroder support for sam inputs

### ISSUE THREAD

**Issue by nate-d-olson** [schneebergerlab/syri#47]
I am interested in using the `chroder` function to get generate a pseudo-genome scale assembly. I used minimap2 to generate the reference-assembly alignment. Do you plan to modify `chroder` to support sam input files or have a script to convert sam files to the expected tsv file format for `chroder`? Alternatively, do you recommend using mummer3 to generate the appropriately formatted input file for `chroder`.

**Comment by mnshgl0110** [comment]
Hi Nate. Using mummer might be the easiest option. But, I guess the following python script might work as well:
```
from syri.pyxFiles.synsearchFunctions import samtocoords
import pandas as pd
al=samtocoords('PATH/TO/SAM/FILE')
al.to_csv('/PATH/TO/OUPUT/COORDS/FILE', sep='\t', index=False, header=False)

```

**Comment by mnshgl0110** [comment]
Support for SAM/BAM is added with https://github.com/schneebergerlab/syri/commit/95db3c6b7bdd0109b5cd7fd4b0a727b55dce2a99
