### ISSUE TITLE
one-to-one MAF alignments format

### ISSUE THREAD

**Issue by biozzq** [schneebergerlab/syri#50]
Hi @mnshgl0110 

Can we use one-to-one MAF alignments format to identify structural rearrangements using 'syri'?

Best,
zheng zhuqing

**Comment by mnshgl0110** [comment]
Hi Zheng,

Unfortunately, SyRI cannot read alignments in MAF format. You would need to convert them to SAM/BAM. You can try using [maf-covert](http://last.cbrc.jp/doc/maf-convert.html) for that.

Best
Manish

**Comment by biozzq** [comment]
Hi @mnshgl0110 

Thank you. I will have a try.

Best,
Zheng Zhuqing
