### ISSUE TITLE
How to set perfect alignment in chroder

### ISSUE THREAD

**Issue by wuxingbo1986** [schneebergerlab/syri#51]
Hi,

In chroder function, is there an argument to set the alignment between two assemblies to be 100% ?

Thanks.
Xingbo

**Comment by mnshgl0110** [comment]
Hi Xingbo. I am sorry, but I did not understand the question. Could you please explain it in more detail or with an example? Thanks.

**Comment by wuxingbo1986** [comment]
Hi, 

I was a little bit confused but I understand now.

I am having another issue. When I run **chroder** following the instruction (using mummer as the aligner), I am getting the error below:

 File "out_m_i100_l100.coords", line 1
    1   297832  23585   321416  297832  297832  100.00  1       1       HiC_scaffold_1  tig00010548|arrow|arrow
           ^
SyntaxError: invalid syntax

What is happening here?

Thanks.

**Comment by mnshgl0110** [comment]
What command are using?

**Comment by wuxingbo1986** [comment]
I used the following command:

python3 $PATH_TO_CHRODER  out_m_i100_l100.coords -n 1000 ref.fasta query.fasta

Here is the error message:
Traceback (most recent call last):
  File "/home/syri/bin/chroder", line 1128, in <module>
    from syri.pyxFiles.synsearchFunctions import readSAMBAM
  File "syri/pyxFiles/synsearchFunctions.pyx", line 9, in init syri.pyxFiles.synsearchFunctions
ModuleNotFoundError: No module named 'igraph'

Thanks.

**Comment by wuxingbo1986** [comment]
I know what is wrong. Thank you.

**Comment by wuxingbo1986** [comment]
Hi,

The chroder consume a lot of memory during process, the process has been killed many times. any recommendation?

Thanks.

**Comment by mnshgl0110** [comment]
Do you have the newest version of chroder? I recently added an improved implementation developed [here](https://doi.org/10.4230/LIPIcs.WABI.2020.6)

**Comment by wuxingbo1986** [comment]
That's great! Is the improved version called lrs?

Sorry I don't understand what the arguments are in this new program.

python3 lrs.py [naive|dp|ilp|dp2|ilp2]

Thanks.

**Comment by mnshgl0110** [comment]
You do not need to use lrs. Use chroder like normal, just make sure that you have the latest version of [chroder](https://github.com/schneebergerlab/syri/blob/master/syri/bin/chroder)

**Comment by wuxingbo1986** [comment]
Then yes, I am using the new version of chroder. But it quit after 8 hours of running.

**Comment by mnshgl0110** [comment]
It seems that for your assembly chroder is stucking in one of the worst-case scenarios for the algorithm. The only options that might work are either to run chroder on a machine with more available RAM or/and to remove smaller contigs/scaffolds.

**Comment by wuxingbo1986** [comment]
Thanks. I will try that.
