### ISSUE TITLE
run syri error

### ISSUE THREAD

**Issue by shiyi-pan** [schneebergerlab/syri#52]
Hi , as you write in readme.md ,I installed the syri. there are some warnings but I inatalled those python packages,but when I run syri with the test data in your example file , I met the following error:

Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - WARNING - Matching them automatically. For each reference genome, most similar query genome will be selected. Check mapids.txt for mapping used.
ShV - ERROR - Error in finding SNPs using show-snps: /bin/sh: show-snps: command not found

Could you help me fix the problem ? thank you very much.

**Comment by mnshgl0110** [comment]
Hi. You would need to provide the path to ```show-snps``` using the ```-s```. Please check the [Parameters for local variation identificaiton](https://schneebergerlab.github.io/syri/example.html) for more details.

**Comment by shiyi-pan** [comment]
Thank you very much. I provide the path to show-snps and run through it . Thank you a lot.
