### ISSUE TITLE
plotsr

### ISSUE THREAD

**Issue by jinshangkun** [schneebergerlab/syri#53]
Hi！
    Can plotsr show translocations between different chromosomes？And I think it would be great If you can add an option to arrange the chromosomes horizontally。Thank you！

**Comment by mnshgl0110** [comment]
Hi. Adding inter-chromosomal translocations/duplications generally makes the plot quite messy, so currently plotsr do not plot them. But I can see that it might be useful to have them in some cases. I will try to add this option.
Also, thanks for suggesting about changing chromosome orientation. I would give it a look.

**Comment by jinshangkun** [comment]
Thanks! I'm looking forward to it.

**Comment by mnshgl0110** [comment]
Plotsr is a separate package now and can plot inter-chromosomal rearrangements as well.
https://github.com/schneebergerlab/plotsr
