### ISSUE TITLE
Large InDel

### ISSUE THREAD

**Issue by jinshangkun** [schneebergerlab/syri#55]
Hi
I am confused that why ref_start > ref_end for Insertion  and qry_start >qry_end for Deletion.  Why not start = end for one of the genome? Thanks!

Program:
syri -c $coords -r $ref -q $qry -d $delta --dir $output --prefix $ref2qry

Output: 
Gbar_A01        435479  435475  -       -       A01     505991  510625  INS21   SYN5    INS     -
Gbar_A01        17314621     17314671        -       -       A01     16814440   16814439        DEL821  SYN242  DEL   -

**Comment by mnshgl0110** [comment]
Hi.

SyRI identifies Indels within aligned regions AND between two consecutive alignments of a structurally conserved region (please see figure S8 of the manuscript). In the later case, it is possible that the alignments bordering an indel have overlap of few bases (this is controlled by the --allow-offset parameter) and this overlap results in such annotations.

Basically, in the above insertion, position Gbar_A01:435479 maps to A01:505991 and Gbar_A01:435475 maps to A01: 510625. So, it is clear that there is an insertion in query genome but not clear whether it is right of Gbar_A01:435479 or left of Gbar_A01:435475.

In practice, you can either set --allow-offfset to 0 which would ensure that ref_start==ref_end but would change annotation of these region from indel to copy-number variation OR (preferably) select any of the ref_start or ref_end as the point of insertion.

**Comment by jinshangkun** [comment]
OK，Thank you for reply！
