### ISSUE TITLE
How to solve Genome Fusion?

### ISSUE THREAD

**Issue by hewm2008** [schneebergerlab/syri#56]
Dear author:
the  bad info  :"
Reading Coords - ERROR - CM022716.1 in genome B is best match for two chromosomes in genome A. Cannot assign chromosomes automatically.   "

how to set  assign chromosomes  by Manual？

**Comment by mnshgl0110** [comment]
Hi. For manual assignment,  please ensure that both genomes have same number of chromosomes, homologous chromosomes have same chromosome ID, and unplaced scaffolds and contigs are removed.

**Comment by hewm2008** [comment]
Reading Coords - WARNING - Reference chromosome scaffold9 has high fraction of inverted alignments with its homologous chromosome inthe query genome (CM022712.1). Ensure that same chromosome-strands are being compared in the two genomes, as different strand can result in unexpected errors.？

**Comment by mnshgl0110** [comment]
The homologous chromosomes in the two genomes need to represent the same strand. If the chromosomes are from different strands, then the alignments between these chromosomes would be inverted. As SyRI only checks directed alignments for syntenic region identification, it would not be able to find syntenic regions and can crash.
If the majority of alignments between homologous chromosomes are inverted, then the chromosome in the query genome needs to be reverse-complemented. Then the corrected query genome needs to be aligned against the reference genome.
