### ISSUE TITLE
error while install syri

### ISSUE THREAD

**Issue by Orz-CQ** [schneebergerlab/syri#59]
I used conda to create a envirment that python=3.5
and install requirements.
conda install cython numpy scipy pandas=0.23.4 biopython psutil matplotlib=3.0.0
conda install -c conda-forge python-igraph
conda install -c bioconda pysam

While doing "python setup.py install", it stopped with "error: command 'gcc' failed with exit status 1".
My  gcc is "4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)", and have done the "yum install python-devel"

Can you help me?

**Comment by Orz-CQ** [comment]
Here are the error message.

/home/software/anaconda3/envs/syri/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/local/include/assert.h:5:0,
                 from /home/software/anaconda3/envs/syri/include/python3.5m/Python.h:48,
                 from syri/pyxFiles/synsearchFunctions.cpp:18:
/usr/local/include/except.h:15:32: error: conflicting declaration ‘typedef struct Except_Frame_T* Except_Frame_T’
 typedef struct Except_Frame_T *Except_Frame_T;
                                ^
/usr/local/include/except.h:15:16: note: previous declaration as ‘struct Except_Frame_T’
 typedef struct Except_Frame_T *Except_Frame_T;
                ^
/usr/local/include/except.h:17:18: error: field ‘prev’ has incomplete type ‘Except_Frame_T’
   Except_Frame_T prev;
                  ^
syri/pyxFiles/synsearchFunctions.cpp:39045:18: warning: ‘PyObject* __pyx_pw_4syri_8pyxFiles_8function_1getOverlapWithSynBlocks(PyObject*, PyObject*, PyObject*)’ defined but not used [-Wunused-function]
 static PyObject *__pyx_pw_4syri_8pyxFiles_8function_1getOverlapWithSynBlocks(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
                  ^
syri/pyxFiles/synsearchFunctions.cpp:41336:18: warning: ‘PyObject* __pyx_pw_4syri_8pyxFiles_8function_3getmeblocks(PyObject*, PyObject*, PyObject*)’ defined but not used [-Wunused-function]
 static PyObject *__pyx_pw_4syri_8pyxFiles_8function_3getmeblocks(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
                  ^
syri/pyxFiles/synsearchFunctions.cpp:42178:18: warning: ‘PyObject* __pyx_pw_4syri_8pyxFiles_8function_5getConnectivityGraph(PyObject*, PyObject*)’ defined but not used [-Wunused-function]
 static PyObject *__pyx_pw_4syri_8pyxFiles_8function_5getConnectivityGraph(PyObject *__pyx_self, PyObject *__pyx_v_blocksList) {
                  ^
error: command 'gcc' failed with exit status 1

**Comment by mnshgl0110** [comment]
Hi. The error seems to be happening because of the broken /usr/local/include/except.h file. The most I can suggest is to do a clean install of everything and make sure that environment variables are used consistetly.

Also, I cannot recall any reason to do `yum install python-devel` when using conda. So, you can try to install without it.

**Comment by Orz-CQ** [comment]
Thanks for your kindness reply!

So how can I fix my /usr/local/include/except.h ？

**Comment by mnshgl0110** [comment]
Unfortunately, it is not possible for me to tell how to fix this. This is not a SyRI issue but an issue with the system files on your machine. Here is another example: https://groups.google.com/g/bedtools-discuss/c/CURWF19qBuA

I would close this issue now as it is not related to SyRI. If there are other problems, then please start a new issue.
