### ISSUE TITLE
Unequal number of chromosome error

### ISSUE THREAD

**Issue by cjy8709** [schneebergerlab/syri#6]
Hello syri developer

I had an error with syri that seems to indicate there's unequal number of chromosomes.
The following is the error message I have recieved

> syri — WARNING — starting
>Reading Coords — WARNING — Chromosomes IDs do not match.
>Reading Coords — ERROR — Unequal number of chromosomes in the genomes. Exiting

What I did was used a high quality reference genome that have been scaffolded to generate pseudomolecules, and used that to align my de novo assembled species genome. Note that my assembled genome has not been scaffolded so its a draft genome.

I then used nucmer to do the alignment, following the steps outlined in the github to generate the coord and delta file.
However I get the error message when I start syri with command:

python3 syri -c test.coords -ref.fa -q query.fa -d test.delta 

Any suggestions?

Thank you.

Jae

**Comment by PhDstuff** [comment]
I have the EXACT same issue
Would be glad to see this fixed!
Thanks
Samuel

**Comment by mnshgl0110** [comment]
To identify SRs, SyRI starts by identifying syntenic regions which in turn requires that the molecules in two assemblies are homologous and have one-to-one mapping.

You can get that by using `chroder` which can generate a homology based pseudo-chromosome level assembly from incomplete assembly which would have same number of chromosomes as in the reference. https://schneebergerlab.github.io/syri/scaforder.html

Once, you have the pseudo-chromosome level assembly, you can repeat whole-genome alignment, and generate fresh delta and coord file and run SyRI.

Additionally, I would recommend to select only large chromosome-scale molecules from the reference and filter out smaller unplaced molecules as they might introduce noise and affect pseudo-chromosome generation.

I hope this helps. Let me know if there are other issues.

**Comment by PhDstuff** [comment]
How would it be feasible to work with inter-chromosomal rearrangements?
For assemblies with an equal number of chromosomes I get this response due to a reciprocal translocation between two chromosomes

`Reading Coords — ERROR — chrVII_chrIV in genome B is best match for two chromosomes in genome A. Cannot assign chromosomes automatically.`

**Comment by pan-genome** [comment]
We have the same issue, even we have make sure the chromosomes are match:
grep ">" query.fa
>Chr1
>Chr2
>Chr3
>Chr4
>Chr5
>Chr6
>Chr7
>Chr8
>Chr9
>Chr10

grep ">" ref.fa
>Chr1
>Chr2
>Chr3
>Chr4
>Chr5
>Chr6
>Chr7
>Chr8
>Chr9
>Chr10


$ python3 /path/syri/bin/syri -c out_m_i90_l100.coords -r ref.fa -q query.fa -k
Namespace(TransUniCount=1000, TransUniPercent=0.5, all=False, bruteRunTime=60, chrmatch=False, cigar=False, delta=None, dir=None, fout='syri', ftype='T', increaseBy=1000, infile=<_io.TextIOWrapper name='out_m_i90_l100.coords' mode='r' encoding='UTF-8'>, keep=True, log='INFO', log_fin=<_io.TextIOWrapper name='syri.log' mode='w' encoding='UTF-8'>, nCores=1, nosnp=False, nosr=False, nosv=False, novcf=False, offset=5, prefix='', qry=<_io.TextIOWrapper name='query.fa' mode='r' encoding='UTF-8'>, ref=<_io.TextIOWrapper name='ref.fa' mode='r' encoding='UTF-8'>, seed=1, sspath='show-snps')
syri - WARNING - starting
/path/syri/bin/syri:115: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  chrlink = startSyri(args)
Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - ERROR - Unequal number of chromosomes in the genomes. Exiting

**Comment by mnshgl0110** [comment]
Are you using python version 3.5? Also, what version of pandas is used? From the warning message, it seems that you are using pandas0.24. Can you please try with pandas0.23.4?

**Comment by pan-genome** [comment]
I am using 3.6, I just downgraded my pandas to 0.23.4 but still have the same error.
$python3
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.__version__
'0.23.4'

I poked around a little bit add errorlog to print out the chromosome Ids both for ref and query, and got the following out:
Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - ERROR - ['Chr1' 'Chr10' 'Chr2' 'Chr3' 'Chr4' 'Chr5' 'Chr6' 'Chr7' 'Chr8' 'Chr9']
Reading Coords - ERROR - ['Chr10']
Reading Coords - ERROR - Unequal number of chromosomes in the genomes. query Exiting

looks it did not picked up the correct chromosome IDs from the bChr.

**Comment by mnshgl0110** [comment]
That's weird. Would it be possible for you to share the coords and the syri.log file?

**Comment by pan-genome** [comment]
here is log file:
$ cat syri.log
2020-03-03 16:05:05,773 - syri - WARNING - <module>:115 - starting
2020-03-03 16:05:05,774 - Reading Coords - INFO - <module>:115 - Reading input from .tsv file
2020-03-03 16:05:06,221 - Reading Coords - WARNING - <module>:115 - Chromosomes IDs do not match.
2020-03-03 16:05:06,393 - Reading Coords - ERROR - <module>:115 - ['Chr1' 'Chr10' 'Chr2' 'Chr3' 'Chr4' 'Chr5' 'Chr6' 'Chr7' 'Chr8' 'Chr9']
2020-03-03 16:05:06,457 - Reading Coords - ERROR - <module>:115 - ['Chr10']
2020-03-03 16:05:06,457 - Reading Coords - ERROR - <module>:115 - Unequal number of chromosomes in the genomes. Exiting

coords file is too large to attach, here is the head of it:
$ head out_m_i90_l100.coords
61339   70290   85411603        85420602        8952    9000    90.96   1       1       Chr1    Chr10
61339   70290   109173223       109182135       8952    8913    98.28   1       1       Chr1    Chr10
70291   79757   25442344        25451837        9467    9494    96.17   1       1       Chr1    Chr10
70291   79757   71593888        71603372        9467    9485    95.88   1       1       Chr1    Chr10
83313   87834   134677527       134672962       4522    4566    97.20   1       -1      Chr1    Chr10
83858   89979   147564054       147557874       6122    6181    96.39   1       -1      Chr1    Chr10
96055   107768  4269601 4257914 11714   11688   95.36   1       -1      Chr1    Chr10
126034  128267  125272008       125274241       2234    2234    98.03   1       1       Chr1    Chr10
161641  171166  98736920        98746430        9526    9511    96.45   1       1       Chr1    Chr10
161643  171169  118528608       118519084       9527    9525    96.04   1       -1      Chr1    Chr10

**Comment by mnshgl0110** [comment]
Here, I only see alignments to Chr10 on b-genome. Are there alignments to other bchrs in the coords file?

**Comment by pan-genome** [comment]
even I point both ref and query file to the same fa file, it can not parse the second (bChr) file correctly:
$ python3 /ngsprod/ke1777/syri/syri/bin/syri -c out_m_i90_l100.coords -r ref.fa -q ref.fa -k

syri - WARNING - starting
Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - ERROR - ['Chr1' 'Chr10' 'Chr2' 'Chr3' 'Chr4' 'Chr5' 'Chr6' 'Chr7' 'Chr8' 'Chr9']
Reading Coords - ERROR - ['Chr10']
Reading Coords - ERROR - Unequal number of chromosomes in the genomes. Exiting

**Comment by pan-genome** [comment]
the coord file looks good to me, 
$ tail out_m_i90_l100.coords
159430203       159435543       18999980        19005317        5341    5338    95.77   1       1       Chr9    Chr10
159436079       159438349       68799080        68796807        2271    2274    93.82   1       -1      Chr9    Chr10
159516495       159521901       66301210        66295770        5407    5441    93.27   1       -1      Chr9    Chr10
159516495       159521901       106054194       106059568       5407    5375    93.88   1       1       Chr9    Chr10
159536812       159546315       14112015        14121486        9504    9472    95.86   1       1       Chr9    Chr10
159568933       159573754       73877365        73882176        4822    4812    94.13   1       1       Chr9    Chr10
159569074       159575722       29367493        29360852        6649    6642    94.57   1       -1      Chr9    Chr10
159671157       159674059       20823209        20826121        2903    2913    96.10   1       1       Chr9    Chr10
159720567       159727921       27597229        27604576        7355    7348    94.21   1       1       Chr9    Chr10
159766857       159769782       79594575        79591665        2926    2911    94.66   1       -1      Chr9    Chr10

**Comment by mnshgl0110** [comment]
Not really.
In an following alignment,
159766857 159769782 79594575 79591665 2926 2911 94.66 1 -1 Chr9 Chr10
Chr9:159766857-159769782 is aligning to Chr10:79594575-79591665. But are there alignments (rows) to other bchrs? That is, the last coloumn is Chr1-9?

**Comment by pan-genome** [comment]
you are right looks the coord file only have Chr10,
cut -f11 out_m_i90_l100.coords | sort | uniq -c
 121277 Chr10

thanks for helping me figure out this! I will see what went wrong generating the coord files.

**Comment by mnshgl0110** [comment]
All the best.

**Comment by pan-genome** [comment]
maybe this should be a MuMmer question. but I am asking here just in case you've seen it before:

the input all.delta has all b chromosomes:
$grep "^>" all.delta | awk '{print $2}' | sort | uniq
Chr1
Chr10
Chr2
Chr3
Chr4
Chr5
Chr6
Chr7
Chr8
Chr9

but after filtering:
$mummer-4.0.0beta2/delta-filter -m -i 90 -l 100 all.delta > out_m_i90_l100.delta

the output file out_m_i90_l100.delta only have b chr10 left.
$ grep "^>" out_m_i90_l100.delta | awk '{print $2}' | sort | uniq
Chr10

**Comment by mnshgl0110** [comment]
Difficult for me to say. Maybe you can try to play with parameters (by not using -m or -i or -l). Also, you can try with mummer3 and its delta-filter.

**Comment by jtweir** [comment]
I have a similar problem when running syri:
Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - ERROR - Unequal number of chromosomes in the genomes. Exiting

In my case I am using pandas 0.23.4 and Python 3.5 and the syri.log file confirms:
"Python and Pandas version are ok"

Unlike pan-genome above I do not have any chromosomes filtered out by running the delta-filter (using nucmer from MUMmer3.23) and the syri error occurs whether or not I use the -m -i  -l options of mummers delta-filter.

I have verified that that my reference and query genomes have identical numbers of chromosomes and chromosome names. 

I have run syri now using an identical pipeline on 12 pairs of species genomes and in all cases except two it worked. Two give this error.

**Comment by jtweir** [comment]
I had a similar issue as pan-genome. One of my micro-chromosomes showed up when running:
$grep "^>" all.delta | awk '{print $2}' | sort | uniq
But not when running:
$grep "^>" all.delta | awk '{print $1}' | sort | uniq

I manually deleted a single line in the coords file involving this micro-chromosome and then syri worked.

**Comment by mnshgl0110** [comment]
Which version of MUMmer are you using?

**Comment by jtweir** [comment]
I am using MUMmer3.23 and pandas 0.23.4. Note that both species had identical chromosome numbers and names before running nucmer from mummer and it was nucmer that generate the issue for a very small chromosome. I have now run syri on several geneome pairs using an identical pipeline with this issue arising only in two of them, and always involving a very small micro-chromosome.

**Comment by jtweir** [comment]
Please drop me a link to the published piece when it is done.


######################################
Jason Weir

Professor
Dept. of Ecology and Evolution and Dept. Biological Sciences
University of Toronto
1265 Military Trail
Toronto, Ontario, Canada MIC 1A4
http://www.utsc.utoronto.ca/~jweir/ (reprints)
######################################



________________________________

**Comment by mnshgl0110** [comment]
So, if I understand correctly, this micro-choromome is present in both genomes but in one of the genomes it do not align with anything else on the other genome. This would mean that the micro-chromosomes are not homologous to each other and as such can be filtered out without any issues.

**Comment by jtweir** [comment]
I think this is indeed true. In one species pair, the reference had a small region from a different chromosome in the query genome align to this micro-chromosome but nothing from the same micro-chromosome in the query aligned. In another species pair, this pattern was reversed between query and reference. 

I am simply mentioning this here not as a bug in syri but rather to help others who obtain this issue troubleshoot what might be going on for them.

**Comment by mnshgl0110** [comment]
Yes, of course. This is indeed helpful, thanks.

**Comment by aaannaw** [comment]
Hello
@cjy8709 
I met the same problem. My two chromosome level genome has unequal pseduo-chromosome numbers. Could you share me any later resolutions with me? Thank you so much !

**Comment by LiuJeremy** [comment]
I found that read does not match the genome. The chromosome of read in the sam file is * mark
