### ISSUE TITLE
TypeError: invalid type comparison

### ISSUE THREAD

**Issue by zhiyongli1995** [schneebergerlab/syri#60]
Hi，
 When I using syri to genotype with mummer reasults, I got this error. It seems occur in step: "Finding SNPs and small indels" .
 This is my code:
`python3 /home/lizhiyong/callSV/syri/syri/bin/syri -c out_m_i90_l100.coords -d out_m_i90_l100.delta -r /xincunchu/CallSV/genomes/Zea_mays.AGPv4.dna.toplevel.2.fa -q /xincunchu/CallSV/genomes/mo17genome2.2.fa --prefix b37-mo17-chr2-snp. --lf b37-mo17-chr2-snp.log`
This is log file:
`/home/lizhiyong/miniconda3/envs/python35/lib/python3.5/site-packages/pandas/core/ops.py:1167: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)
ctxOut.txt is empty. Skipping analysing it.
ctxOut.txt is empty. Skipping analysing it.
ctxOut.txt is empty. Skipping analysing it.
Traceback (most recent call last):
  File "/home/lizhiyong/callSV/syri/syri/bin/syri", line 253, in <module>
    getshv(args, coords, chrlink)
  File "syri/pyxFiles/findshv.pyx", line 196, in syri.pyxFiles.findshv.getshv
  File "/home/lizhiyong/miniconda3/envs/python35/lib/python3.5/site-packages/pandas/core/ops.py", line 1283, in wrapper
    res = na_op(values, other)
  File "/home/lizhiyong/miniconda3/envs/python35/lib/python3.5/site-packages/pandas/core/ops.py", line 1169, in na_op
    raise TypeError("invalid type comparison")
TypeError: invalid type comparison`
I very much hope to solve this problem as soon as possible. Thank you and look forward to your reply!

**Comment by mnshgl0110** [comment]
Hi. Sorry for a late reply, I am on vacation. Could you please share the log file? Also, please make sure that the chromosome IDs in the input files are strings and not numbers. So, for chromosome 1, chromosome id can be `>Chr1`, but not ` >1`.

**Comment by zhiyongli1995** [comment]
Thank you very much,  this "chromosome id can be >Chr1, but not >1" really helpful. After I corrected my chromosome ID, the program is working very well.
