### ISSUE TITLE
Chrodder not assembling as expected

### ISSUE THREAD

**Issue by jtweir** [schneebergerlab/syri#61]
I tested chrodder to make sure it was behaving as expected.
I generated five ~4kb length sequences which I will labeled A to E.

For Species1 I made three scaffolds:
A       (Chr1_Sp1)
BCD  (Chr2_Sp1)
E       (Chr3_Sp1)

For Species 2 I made three scaffolds:
AB    (Chr1_Sp2)
CD    (Chr2_Sp2)
E       (Chr3_Sp2)

I expected to get two Pseuo-chromosomes from chrodder as follows for both my reference and query:
ABCD = (Chr1_Sp1, Chr2_Sp1) (Chr1_Sp2, Chr2_Sp2)
E = (Chr3_Sp1)(Chr3_Sp2)

Instead chrodder incorrectly outputs identical scaffolds as found in each input species. I checked nucmer's coordinate file and it correctly suggested that A to D all belonged to a single pseudo-chromosome. Here is the coordinates table:
1	4093	1	4093	4093	4093	100.00	1	1	Chr1_Sp2	Chr1_Sp1
4094	8186	1	4093	4093	4093	100.00	1	1	Chr1_Sp2	Chr2_Sp1
1	7473	4094	11566	7473	7473	100.00	1	1	Chr2_Sp2	Chr2_Sp1
1	4093	1	4093	4093	4093	100.00	1	1	Chr3_Sp2	Chr3_Sp1

So I am wondering why Chodder is not working as expected? My only guess is that perhaps scaffolds need to be a minimum size before chrodder will assemble them properly into Pseudo-chromosomes?

CODE:
   conda activate SYRI

   time /home/0_PROGRAMS/MUMmer3.23/nucmer --maxmatch -c 65 -b 500 -l 20 \
      "$GENOME2" \
      "$GENOME1" \
      -p NUCMER
      
        
   time /home/0_PROGRAMS/MUMmer3.23/show-coords -THrd \
       NUCMER.delta > CHRODER.delta.coords
       
   time python $PATH_TO_CHRODER -o CHRODER_pseudochromosomes\
      -noref \
      CHRODER.delta.coords \
      "$GENOME2" \
      "$GENOME1"

**Comment by mnshgl0110** [comment]
Hi. You are right regarding the minimum size. Anything below 10kb would not be considered. So, you would need to generate longer test scaffolds. Also, for real data, it is better to remove smaller scaffolds as they might result in too much memory usage.

**Comment by jtweir** [comment]
Great, everything works as expected now that I increase sequence length to >10kb
