### ISSUE TITLE
Do not have any output when using --novcf parameters!

### ISSUE THREAD

**Issue by zhiyongli1995** [schneebergerlab/syri#63]
Hi,
When I running the following codes, no results will be shown (such as *synOut.txt or *vcf).
`python3 $PATH_TO_SYRI -c mummertest.filtered.coords -d mummertest.filtered.delta -r refgenome -q qrygenome --novcf --prefix mummertest.syri`
I believe it's --novcf causes. However, --novcf is working very well with minimap2. Is this a BUG?
Looking forward to your reply.

**Comment by mnshgl0110** [comment]
Hi @zhiyongli1995, by using `--novcf` you have turned off the generation of the final output files, and because you do not use `-k` the intermediate files are deleted as well. So, it is expected that you do not see any output. Remove `--novcf` and add `-k` to get all output files.

**Comment by zhiyongli1995** [comment]
Hi @mnshgl0110, thanks for your reply, you  are quite right. I tried your method. Now I can get the intermediate output files. Thank you again. You guys are a really good team!
