### ISSUE TITLE
how to solve this error message

### ISSUE THREAD

**Issue by wuxingbo1986** [schneebergerlab/syri#64]
Hi,

I am getting this error message with _chorder_:

"Error: For contig  qrytig00009183|arrow|arrow  no matching contig was found. This could be a result of incorrect assembly or extensive repeats or  qrytig00009183|arrow|arrow  could be a novel region. Pseudo-genome cannot be generated. Try removing this contig."

I checked my coords and assembly files, this contig does exit, but only a portion of the sequence was aligned to the reference genome.

How do I solve this issue?

Thanks.

**Comment by mnshgl0110** [comment]
Hi @wuxingbo1986, it might be the case the alignment for this contig is too small to have sufficient information for generating pseudo-genome. So, I think the best option would be to just remove this contig. In general, when using chroder smaller contigs should be filtered out.

**Comment by wuxingbo1986** [comment]
Thank you. Those contigs were removed and the pseudo-chromsome was generated.

By comparing the coordinates file and _anno_ file generated by _chorder_, I noticed a few large contigs were also excluded. These contigs have full alignment with the reference. What could be the reason for it?

Thanks.

**Comment by mnshgl0110** [comment]
Difficult to say. One possibility is that there could be other longer contigs that map in the region and was therefore selected. Chroder do not break contigs, so if there are mis-assemblies then that might also result in this issue.

If you are trying to generate pseudo-chromosome using a chromosome-level reference assembly, then there are better tools available compared to chroder. Chroder is useful for the case when no chromosome-level reference genome is available.

**Comment by wuxingbo1986** [comment]
can you recommend other tools that I can use?

Thanks.
Xingbo

**Comment by mnshgl0110** [comment]
You can try [ntjoin](https://academic.oup.com/bioinformatics/article/36/12/3885/5822878?login=true) or [ragoo](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1829-6).
