### ISSUE TITLE
difference between INV and INVAL

### ISSUE THREAD

**Issue by shiyi-pan** [schneebergerlab/syri#65]
I'm confuse about INV ("Inversion") and INVAL("Inversion alignment").
here are two site of my syri outfile vcf file:

Chr01   14295851        INV3516 N       <INV>   .       PASS    END=14323781;ChrB=Chr01;StartB=14771183;EndB=14816184;Parent=.;VarType=SR;DupType=-
Chr01   14295851        INVAL49145      N       <INVAL> .       PASS    END=14304975;ChrB=Chr01;StartB=14816184;EndB=14806797;Parent=INV3516;VarType=.;DupType=.

the start points are same and the start points are different. So could you tell me  what's the difference between INV and INVAL ? Thank you very much.

**Comment by mnshgl0110** [comment]
Inversion (INV) is the annotation for the genomic region, whereas inverted alignments (INVAL) reports alignments that make the inversion. An INV can be made up of multiple INVAL.
