### ISSUE TITLE
output

### ISSUE THREAD

**Issue by jinshangkun** [schneebergerlab/syri#67]
Hi
I am confused about why the output file 'syri.out' contains CPL/G, TDM and DUP simultaneously, because I think CPL/G or TDM is  a type of DUP. 
A01        41726   41921   -       -       A01     42106   42152   CPL1    SYN1    CPL     -
A01        59486   59996   -       -       A01     58767   59020   CPL3    SYN1    CPL     -
A01        889333  890424  -       -       A01     935385  936476  DUP34228        -       DUP     copygain
A01        905125  924520  -       -       A01     1424944 1436163 DUP34231        -       DUP     copyloss
A01        9050412 9051495 -       -       A01     8277147 8277969 TDM522  SYN157  TDM     -

**Comment by mnshgl0110** [comment]
DUP is for larger structural rearrangements, whereas CPG/CPL and TDM corresponds to "local" structural variations identified within syntenic or structurally rearranged regions. So, it is possible, for example, to have a local TDM within a syntenic or a CPG within a translocation. Consider it like nested genomic variation identification, where first the genomes are divided into syntenic and structural rearrangements, followed by identification of structural variations (indels, TDM, HDR) within these syntenic and structural rearrangements.

**Comment by jinshangkun** [comment]
Thanks for your quick reply! I understand.
