### ISSUE TITLE
Syri for bacterial genome

### ISSUE THREAD

**Issue by rthapa1** [schneebergerlab/syri#69]
Hi,

I want to call SV from de novo assembled bacterial genome. Do we need to make same starting point for all genome to call SV?

Thanks

**Comment by mnshgl0110** [comment]
Ideally yes. Minor offsets in the starting position should be OK but might result in some false structure rearrangements where one end would be annotated as "translocated" to the other end. Large offsets might result in incorrect annotations as the algorithm cannot differentiate between actual structural rearrangements and offsets in circular DNA.

**Comment by rthapa1** [comment]
Thank you. When I checked the genome alignment with mauve, it looks like the attached figure. The orientation in one genome is different than other.
<img width="792" alt="Screen Shot 2021-02-09 at 10 32 57 PM" src="https://user-images.githubusercontent.com/61608522/107715601-a5aa5180-6c9d-11eb-82fd-bc43e0e2c59b.png">

**Comment by mnshgl0110** [comment]
Yes, this will affect syri's annotation. SyRI expect that both genomes (reference and query) would be highly syntenic and the same strands are being compared. If these genomes corresponds to different strands, then you would need to reverse complement them.
