### ISSUE TITLE
Duplications

### ISSUE THREAD

**Issue by fergsc** [schneebergerlab/syri#70]
Hi,
SyRI has identified a lot of DUPs and INVDUPs in my genomes. The documents state that:
Copy status describes whether the duplicated region in genome B (copygain, i.e. genome B has the extra copy) or in genome A (copyloss, i.e. genome A has the extra copy).

In this example it would appear as genome B has the extra copy, but is flagged as copyloss. Is this correct?

Chr04   1       21568   -       -       Chr04   25567509        25589248        INVDP40072      -       INVDP   copyloss
Chr04   1       21568   -       -       Chr04   25739294        25761018        INVDP40073      -       INVDP   copyloss

Are duplication events listed as two paired events within the out file? ie. the source location is the same in both events with a different end location.

Thanks.

**Comment by mnshgl0110** [comment]
Fixed in the new version.
