### ISSUE TITLE
Query naming in out files

### ISSUE THREAD

**Issue by ChriKub** [schneebergerlab/syri#71]
I'm running V1.4 (it is the same in V1.3) and all of the output file contain the reference sequence ID instead of the correct query ID. I'm using fasta files with different header names that are assigned by syri. The assignment in the mapids.txt file is correct.

e.g. TLOut.txt
`#       TAIR10_Chr1     8538913 8539719 -       TAIR10_Chr1     12301432        12302254`
instead of:
`#       TAIR10_Chr1     8538913 8539719 -       AT1741_Chr1     12301432        12302254`

**Comment by mnshgl0110** [comment]
The `syri.out` file is the final output file and it should contain the correct chromosome IDs for the query chromosomes. The `*Out.txt` files are intermediate files and use the IDs of the homologous reference chromosome as reported in `mapids.txt`. If the query IDs are required in the `*Out.txt` files, then they can be easily added using the information in `mapids.txt`.
