### ISSUE TITLE
No INVDP items in vcf file

### ISSUE THREAD

**Issue by cai1991** [schneebergerlab/syri#72]
Hi,

I used syri to identify SVs among my genomes and wanted to merge SVs from different individuals into a single vcf file. I found that there are no INVDP items in "syri.vcf" file. Is this caused by the "INVDUP" (expect INVDP and INVDPAL) in the following code?

            if line[10] in ["SYN", "INV", "TRANS", "INVTR", "DUP", "INVDUP"]:
                _info = ';'.join(['END='+line[2], 'ChrB='+line[5], 'StartB='+line[6], 'EndB='+line[7], 'Parent=.', 'VarType='+'SR', 'DupType='+line[11]])
                pos.append(_info)
                fout.write('\t'.join(pos) + '\n')

            elif line[10] == "NOTAL":
                if line[0] != "-":
                    _info = ';'.join(
                        ['END=' + line[2], 'ChrB=.', 'StartB=.', 'EndB=.', 'Parent=.', 'VarType=.', 'DupType=.'])
                    pos.append(_info)
                    fout.write('\t'.join(pos) + '\n')

            elif line[10] in ["SYNAL", "INVAL", "TRANSAL", "INVTRAL", "DUPAL", "INVDUPAL"]:
                _info = ';'.join(
                    ['END=' + line[2], 'ChrB='+line[5], 'StartB='+line[6], 'EndB='+line[7], 'Parent='+line[9], 'VarType=.', 'DupType=.'])
                pos.append(_info)
                fout.write('\t'.join(pos) + '\n')

Thanks a lot in advance for your help.

Best regards,
Chengcheng

**Comment by mnshgl0110** [comment]
Hi Chengcheng,
Thanks for pointing this out. It should be fixed now with commit https://github.com/schneebergerlab/syri/commit/4365a845237a6ac209f86b7686a81fa1d346e698
Best
Manish
