### ISSUE TITLE
Is genome A = refgenome and genome B = qrygenome?

### ISSUE THREAD

**Issue by ricardo-aaron** [schneebergerlab/syri#75]
Hello. Am I correct in assuming that genome A and genome B in https://schneebergerlab.github.io/syri/fileformat.html correspond to refgenome (A) and qrygenome (B) in https://schneebergerlab.github.io/syri/pipeline.html? I think it would be simpler to also use refgenome and qrygenome in https://schneebergerlab.github.io/syri/fileformat.html

**Comment by mnshgl0110** [comment]
Documentations updated https://github.com/schneebergerlab/syri/commit/d20811f747bea0e2b181bd8b94fc6b3b006eb7c5
