### ISSUE TITLE
Error in finding SNPs using show-snps: ERROR:  Could not open file  file1

### ISSUE THREAD

**Issue by sandipmkale** [schneebergerlab/syri#77]
Hello,

I am getting above error while running sari

"- ShV - ERROR - <module>:287 - Error in finding SNPs using show-snps: ERROR:  Could not open file  file1"

I have provided the absolute path of show_snps with -s

Can you please help

With best regards

Sandip

**Comment by mnshgl0110** [comment]
Hi Sandip,

Could you please run the working example to see that everything is
installed correctly. If that works correctly, then please share the command
that you are using and the syri.log file.

Manish

**Comment by sandipmkale** [comment]
Thanks alot Manish,

Sure, I will run the pipeline with example data. 

I have quick question, DO I need to use bam for SNP calling or .delta files will also be OK?

Here are my commands:
python="path to python3.5"
PATH_TO_SYRI ="PATH_TO_SYRI" 
snps="path to MUMmer/4.0.0beta2/bin/show-snps"
$python $PATH_TO_SYRI -c out.filtered.nochrUn.coords -s $snps
 -d out.filtered.delta -r ${fasta1} -q ${fasta2} --prefix $prefix --nc $threads --all 

with best regards

Sandip

**Comment by mnshgl0110** [comment]
SyRI uses `show-snps` to get SNPs from delta files produced my MUMmer, so you do not need BAM files. The commands look OK so it should work, but we would know more when you run the example analysis. You can try to run `show-snps` directly from terminal to see whether it is working correctly or not.
