### ISSUE TITLE
Python Library Versions to install?

### ISSUE THREAD

**Issue by ccmenard** [schneebergerlab/syri#81]
Hi can you please list out each individual package and their version that needs to be installed along with python 3.5 for this to work? I'm having trouble getting the python-igraph to work correctly. 

Thanks

**Comment by mnshgl0110** [comment]
Hi Claire,

There is some description for installing SyRI [here](https://schneebergerlab.github.io/syri/install.html). Have you checked this out? Generally, installing these libraries works well with the conda enviroment. 

For SyRI, I used python-igraph 0.7.1.post6. You can try installing this.

You can also share what exact error you are getting, though I am not sure how much I can help with installing this package. Maybe also check out the [python-igraph](https://github.com/igraph/python-igraph/issues) repo as the solution could already be there.

Best
Manish
