### ISSUE TITLE
What's the quantifying criterion to identifying a HDR?

### ISSUE THREAD

**Issue by xie-wei-hh** [schneebergerlab/syri#87]
Hi, I figure out the definition of HDR through this issue (https://github.com/schneebergerlab/syri/issues/44) and figure S8. But I still wonder about the quantifying criterion to identifying a HDR, was it the similarity between the query and reference assemblies, the relative content of different variation type in a SYN or something other ?

**Comment by mnshgl0110** [comment]
HDR stands for Highly Diverged Regions. So, HDR are basically regions that are 'different' (not aligned) within a structural unit (syntenic/SR blocks). So, when two consecutive alignments of a syntenic (or SR) block have gaps of >1 base pair on both the reference and query genome, then SyRI annotates these gaps as HDRs.

**Comment by xie-wei-hh** [comment]
Dose "have gaps of >1 base pair on both the reference and query genome" mean "SNP" ?

**Comment by xie-wei-hh** [comment]
Dose "have gaps of >1 base pair on both the reference and query genome" mean "indel" ?

**Comment by mnshgl0110** [comment]
As shown in figure S8, if only one genome has a gap, then it is annotated as indel but when both genomes have gaps then it is HDR. For some analysis it might be meaningful to consider HDRs as insertion+deletion at a location. But HDRs are more parsimonious as they explain the variation as one sequence divergence event rather than two indel events.

**Comment by xie-wei-hh** [comment]
I understand that. So, as the follow figure, which part of figure S8 was identified as HDR, the 1st, 2nd or the whole region show in the S8 or other region ?

&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "schneebergerlab/syri"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月18日(星期五) 下午5:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [schneebergerlab/syri] What's the quantifying criterion to identifying a HDR? (#87)





 
As shown in figure S8, if only one genome has a gap, then it is annotated as indel but when both genomes have gaps then it is HDR. For some analysis it might be meaningful to consider HDRs as insertion+deletion at a location. But HDRs are more parsimonious as they explain the variation as one sequence divergence event rather than two indel events.

**Comment by xie-wei-hh** [comment]
I understand that. So, as the follow figure, which part of figure S8 was identified as HDR, the 1st, 2nd or the whole region show in the S8 or other region ?
![1624009957(1)](https://user-images.githubusercontent.com/85665772/122543205-199aa300-d05e-11eb-8354-6157f117cfa8.jpg)

**Comment by mnshgl0110** [comment]
I am not sure what is the difference in 1st and 2nd figure. But, SyRI would annotate the black thin lines, both in reference and in query, as HDR.

**Comment by xie-wei-hh** [comment]
OK, I got that, thank you.

**Comment by liufy11** [comment]
HDR means high different region between reference and query. and both genomes have gaps ,or it will be annoted as indel. but in my result file(syri.out), I found many HDRs have no gaps in reference or query.  Can you tell me what' wrong?
I select such HDRs like following:
zs11_A01        10122805        10122805        Hic_asm_0       9836836 9837438 HDR486  SYN104
zs11_A01        12559586        12559586        Hic_asm_0       12226984        12227094        HDR570  SYN116
zs11_A01        29042834        29042834        Hic_asm_10      38242185        38243286        HDR902  TRANS5612
zs11_A01        30263213        30263213        Hic_asm_10      39404320        39404586        HDR999  TRANS5612
zs11_A01        30823267        30823267        Hic_asm_0       29614882        29615561        HDR1144 SYN205
zs11_A01        30823267        30823267        Hic_asm_10      39912929        39913608        HDR1040 TRANS5612

zs11_scaffoldA01        606266  606355  -       -       Hic_asm_0       383045  383045  HDR75   SYN7    HDR     -       
zs11_scaffoldA01        3676062 3678939 -       -       Hic_asm_0       3450194 3450194 HDR197  INV3929 HDR     -       
zs11_scaffoldA01        4763842 4765315 -       -       Hic_asm_0       4418824 4418824 HDR246  SYN45   HDR     -      
zs11_scaffoldA01        7105068 7105783 -       -       Hic_asm_0       6762446 6762446 HDR359  SYN70   HDR     -

**Comment by mnshgl0110** [comment]
The start and end bases of annotations are included in the gap. In the following annotation:
```zs11_A01 10122805 10122805 Hic_asm_0 9836836 9837438 HDR486 SYN104```
The reference has a 1bp gap at position zs11_A01:10122805.

Also, in the above discussion, I made an error (I wrote >1bp gaps whereas it should be >=1bp gap). I have edited that now.
