### ISSUE TITLE
what's the difference between copyloss/copgain of DUP and CPL/CPG?

### ISSUE THREAD

**Issue by xie-wei-hh** [schneebergerlab/syri#88]
Hi, I known that CPL/CPG refer to reference has the extra copy/query has the extra copy, but I wonder about the difference/relevance between that and copyloss/copgain of one DUP (Duplicated region)? Could you please help me?

**Comment by mnshgl0110** [comment]
Describe here: https://github.com/schneebergerlab/syri/issues/67

**Comment by xie-wei-hh** [comment]
Sorry and thanks, I forgot to search the history firstly.
