### ISSUE TITLE
what are the meanings of syntheitc blocks named CPG, CPL, and TDM?

### ISSUE THREAD

**Issue by comery** [schneebergerlab/syri#90]
Hi, 

I found some types of SYNs in my results, but I have no idea about their meanings. Could you give some descriptions for 
CPG, CPL, and TDM?

best wishes

**Comment by mnshgl0110** [comment]
There is information provided in the [manual](https://schneebergerlab.github.io/syri/fileformat.html), as well as in the [manuscript](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1911-0) (check figure S8). These are also discussed in https://github.com/schneebergerlab/syri/issues/67 and https://github.com/schneebergerlab/syri/issues/40

**Comment by comery** [comment]
Thanks!
