### ISSUE TITLE
Issue with python version (`SyRI uses Python3.5`)

### ISSUE THREAD

**Issue by MatteoSchiavinato** [schneebergerlab/syri#92]
I'm using Syri in an environment where my default is python3.8. I just got an error saying:

```
  Running SyRI - ERROR - 
  SyRI uses Python3.5. Currently using Python3.8. Exiting
```

Is this a bug, or do I have to specifically use python3.5 to use this tool? Isn't there a chance to use a newer python version too?

**Comment by mnshgl0110** [comment]
It is explained in README.

In short, current released/master-branch version does require python 3.5. An update to support python 3.8 is there which you can download and use, but it is under testing and might have some bugs.

**Comment by MatteoSchiavinato** [comment]
Wow, that was fast. Thanks!
