### ISSUE TITLE
What is the annotation bed file in plotsr -B option?

### ISSUE THREAD

**Issue by kunproj** [schneebergerlab/syri#93]
Hello，Nice work for SYRI !
I am using syri to detecte Structural variations and using plotsr for plotting, But always meeting error"
 plotsr  syri.out  $refgenome $qrygenome -o png -B bed

Incomplete data in BED file line:
'contig41', '129765', '141675', 'utg41', '58816', '70726', 'SYN', '1505', '1505'
Marker information (type, col, size) is necessary. Text annotation (text, col, size) is optional"

I  don't know what is the error of my bed file. Could you please give me a exmple bed format? 
Thank You very  !
@wen-biao @mnshgl0110 @HeQSun

**Comment by mnshgl0110** [comment]
Hello,
Plotsr can use a bed file to have additional annotation in the plot. But this is still **work in development and is not finalised** yet.
You can get a plot like this:
![image](https://user-images.githubusercontent.com/16225647/128841224-9b61fe7c-5683-4cf7-9eef-918e7c728f5f.png)
By parsing a BED file with this data:
```
Chr1	10000000	10000001	R	.	red	12
Chr2	5000000	5000001	Q	^	black	6	black marker	black	6
Chr3	12000000	12000010	R	,	#78AB46	12   
```
The columns of the BED file are:
```
Chromosome ID
0-based start coordinate
1-based end coordinate
Genome to annotatte (R/Q)
Marker (Similar to defined here: https://matplotlib.org/stable/api/markers_api.html)
Marker colour (Named color acceptable to matplotlib https://matplotlib.org/stable/gallery/color/named_colors.html or in hexadecimal)
Marker size
Annotations text (Optional)
Annotations text color (Optional, Named color acceptable to matplotlib https://matplotlib.org/stable/gallery/color/named_colors.html or in hexadecimal)
Annotations text size (Optional)
```
You can use it but please note that the BED file structure would change in future.

**Comment by kunproj** [comment]
Thank You very much！Great！
