### ISSUE TITLE
inquiries installation warning

### ISSUE THREAD

**Issue by theshowmustgolangon** [schneebergerlab/syri#96]
Hi,
I am installing syri(1.5) with python 3.8 on CentOS 7
and I encountered this warning at 6 files.
would it be fine?
FYI, I encountered the same errors with python version 3.5

syri/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h(17): warning #1224: #warning directive: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
  #warning "Using deprecated NumPy API, disable it with " \
   ^

at these 6 files.

syri/include/python3.8m -c syri/pyxFiles/synsearchFunctions.cpp -o build/temp.linux-x86_64-3.7/syri/pyxFiles/synsearchFunctions.o
syri/include/python3.8m -c syri/pyxFiles/inversions.cpp -o build/temp.linux-x86_64-3.7/syri/pyxFiles/inversions.o
syri/include/python3.8m -c syri/pyxFiles/tdfunc.cpp -o build/temp.linux-x86_64-3.7/syri/pyxFiles/tdfunc.o
syri/include/python3.8m -c syri/pyxFiles/writeout.cpp -o build/temp.linux-x86_64-3.7/syri/pyxFiles/writeout.o
/syri/include/python3.8m -c syri/pyxFiles/findsv.cpp -o build/temp.linux-x86_64-3.7/syri/pyxFiles/findsv.o
syri/include/python3.8m -c syri/pyxFiles/findshv.cpp -o build/temp.linux-x86_64-3.7/syri/pyxFiles/findshv.o

Thank you.

**Comment by mnshgl0110** [comment]
Yes, these warnings do not affect anything and can be ignored.
